
//
// tokens.h
//

// Do not edit directly
// Generated on Fri, 28 Oct 2022 20:42:48 GMT


#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

#define BrkInteractiveStandardOutlineColorFocus #0b5db7
#define BrkInteractiveInvertedOutlineColorFocus #24c1ff
#define BrkInteractiveOutlineWidth 2
#define BrkInteractiveOutlineOffset 2
#define BrkInteractiveOutlineBorderRadius 24
#define BrkButtonPrimaryBorderWidth 2
#define BrkButtonSecondaryBorderWidth 2
#define BrkButtonTertiaryBorderWidth 1
#define BrkButtonOpacityDisabled 50%
#define BrkButtonPrimarySmPaddingHorizontal 15
#define BrkButtonPrimarySmHeight 30
#define BrkButtonPrimarySmBorderRadius 15
#define BrkButtonPrimarySmIconSize 8
#define BrkButtonPrimarySmIconGap 2
#define BrkButtonPrimaryMdPaddingHorizontal 20
#define BrkButtonPrimaryMdHeight 40
#define BrkButtonPrimaryMdBorderRadius 20
#define BrkButtonPrimaryMdIconSize 10
#define BrkButtonPrimaryMdIconGap 4
#define BrkButtonPrimaryLgPaddingHorizontal 25
#define BrkButtonPrimaryLgHeight 50
#define BrkButtonPrimaryLgBorderRadius 25
#define BrkButtonPrimaryLgIconSize 12
#define BrkButtonPrimaryLgIconGap 6
#define BrkButtonPrimaryXlPaddingHorizontal 30
#define BrkButtonPrimaryXlHeight 60
#define BrkButtonPrimaryXlBorderRadius 30
#define BrkButtonPrimaryXlIconSize 14
#define BrkButtonPrimaryXlIconGap 8
#define BrkButtonPrimarySmLabelFontFamily Arial
#define BrkButtonPrimarySmLabelFontWeight Bold
#define BrkButtonPrimarySmLabelLineHeight 100%
#define BrkButtonPrimarySmLabelFontSize 13
#define BrkButtonPrimarySmLabelLetterSpacing 2%
#define BrkButtonPrimarySmLabelParagraphSpacing 
#define BrkButtonPrimarySmLabelTextDecoration none
#define BrkButtonPrimarySmLabelTextCase none
#define BrkButtonPrimaryMdLabelFontFamily Arial
#define BrkButtonPrimaryMdLabelFontWeight Bold
#define BrkButtonPrimaryMdLabelLineHeight 100%
#define BrkButtonPrimaryMdLabelFontSize 18
#define BrkButtonPrimaryMdLabelLetterSpacing 2%
#define BrkButtonPrimaryMdLabelParagraphSpacing 
#define BrkButtonPrimaryMdLabelTextDecoration none
#define BrkButtonPrimaryMdLabelTextCase none
#define BrkButtonPrimaryLgLabelFontFamily Arial
#define BrkButtonPrimaryLgLabelFontWeight Bold
#define BrkButtonPrimaryLgLabelLineHeight 100%
#define BrkButtonPrimaryLgLabelFontSize 22
#define BrkButtonPrimaryLgLabelLetterSpacing 2%
#define BrkButtonPrimaryLgLabelParagraphSpacing 
#define BrkButtonPrimaryLgLabelTextDecoration none
#define BrkButtonPrimaryLgLabelTextCase none
#define BrkButtonPrimaryXlLabelFontFamily Arial
#define BrkButtonPrimaryXlLabelFontWeight Bold
#define BrkButtonPrimaryXlLabelLineHeight 100%
#define BrkButtonPrimaryXlLabelFontSize 26
#define BrkButtonPrimaryXlLabelLetterSpacing 2%
#define BrkButtonPrimaryXlLabelParagraphSpacing 
#define BrkButtonPrimaryXlLabelTextDecoration none
#define BrkButtonPrimaryXlLabelTextCase none
#define BrkButtonPrimaryStandardSmBoxShadowDefault [object Object]
#define BrkButtonPrimaryStandardSmBoxShadowHover [object Object]
#define BrkButtonPrimaryStandardSmBoxShadowFocus [object Object]
#define BrkButtonPrimaryStandardFontColorDefault #192872
#define BrkButtonPrimaryStandardIconColorDefault #192872
#define BrkButtonPrimaryStandardBackgroundColorDefault #fdfe8b
#define BrkButtonPrimaryStandardBorderColorDefault #192872
#define BrkButtonPrimaryStandardFontColorHover #192872
#define BrkButtonPrimaryStandardIconColorHover #192872
#define BrkButtonPrimaryStandardBackgroundColorHover #fdfe8b
#define BrkButtonPrimaryStandardBorderColorHover #192872
#define BrkButtonPrimaryStandardFontColorFocus #192872
#define BrkButtonPrimaryStandardIconColorFocus #192872
#define BrkButtonPrimaryStandardBackgroundColorFocus #fdfe8b
#define BrkButtonPrimaryStandardBorderColorFocus #192872
#define BrkButtonPrimaryStandardMdBoxShadowDefault [object Object]
#define BrkButtonPrimaryStandardMdBoxShadowHover [object Object]
#define BrkButtonPrimaryStandardMdBoxShadowFocus [object Object]
#define BrkButtonPrimaryInvertedSmBoxShadowDefault [object Object]
#define BrkButtonPrimaryInvertedSmBoxShadowHover [object Object]
#define BrkButtonPrimaryInvertedSmBoxShadowFocus [object Object]
#define BrkButtonPrimaryInvertedFontColorDefault #0b5db7
#define BrkButtonPrimaryInvertedIconColorDefault #0b5db7
#define BrkButtonPrimaryInvertedBackgroundColorDefault #fdfe8b
#define BrkButtonPrimaryInvertedBorderColorDefault #0b5db7
#define BrkButtonPrimaryInvertedFontColorHover #0b5db7
#define BrkButtonPrimaryInvertedIconColorHover #0b5db7
#define BrkButtonPrimaryInvertedBackgroundColorHover #fdfe8b
#define BrkButtonPrimaryInvertedBorderColorHover #0b5db7
#define BrkButtonPrimaryInvertedFontColorFocus #0b5db7
#define BrkButtonPrimaryInvertedIconColorFocus #0b5db7
#define BrkButtonPrimaryInvertedBackgroundColorFocus #fdfe8b
#define BrkButtonPrimaryInvertedBorderColorFocus #0b5db7
#define BrkButtonPrimaryInvertedMdBoxShadowDefault [object Object]
#define BrkButtonPrimaryInvertedMdBoxShadowHover [object Object]
#define BrkButtonPrimaryInvertedMdBoxShadowFocus [object Object]
#define BrkButtonSecondarySmHeight 30
#define BrkButtonSecondarySmBorderRadius 15
#define BrkButtonSecondarySmPaddingHorizontal 15
#define BrkButtonSecondarySmIconSize 8
#define BrkButtonSecondarySmIconGap 2
#define BrkButtonSecondaryMdHeight 40
#define BrkButtonSecondaryMdBorderRadius 20
#define BrkButtonSecondaryMdPaddingHorizontal 20
#define BrkButtonSecondaryMdIconSize 10
#define BrkButtonSecondaryMdIconGap 4
#define BrkButtonSecondaryLgHeight 50
#define BrkButtonSecondaryLgBorderRadius 25
#define BrkButtonSecondaryLgPaddingHorizontal 25
#define BrkButtonSecondaryLgIconSize 12
#define BrkButtonSecondaryLgIconGap 6
#define BrkButtonSecondaryXlHeight 60
#define BrkButtonSecondaryXlBorderRadius 30
#define BrkButtonSecondaryXlPaddingHorizontal 30
#define BrkButtonSecondaryXlIconSize 14
#define BrkButtonSecondaryXlIconGap 8
#define BrkButtonSecondarySmLabelFontFamily Arial
#define BrkButtonSecondarySmLabelFontWeight Bold
#define BrkButtonSecondarySmLabelLineHeight 100%
#define BrkButtonSecondarySmLabelFontSize 13
#define BrkButtonSecondarySmLabelLetterSpacing 2%
#define BrkButtonSecondarySmLabelParagraphSpacing 
#define BrkButtonSecondarySmLabelTextDecoration none
#define BrkButtonSecondarySmLabelTextCase none
#define BrkButtonSecondaryMdLabelFontFamily Arial
#define BrkButtonSecondaryMdLabelFontWeight Bold
#define BrkButtonSecondaryMdLabelLineHeight 100%
#define BrkButtonSecondaryMdLabelFontSize 18
#define BrkButtonSecondaryMdLabelLetterSpacing 2%
#define BrkButtonSecondaryMdLabelParagraphSpacing 
#define BrkButtonSecondaryMdLabelTextDecoration none
#define BrkButtonSecondaryMdLabelTextCase none
#define BrkButtonSecondaryLgLabelFontFamily Arial
#define BrkButtonSecondaryLgLabelFontWeight Bold
#define BrkButtonSecondaryLgLabelLineHeight 100%
#define BrkButtonSecondaryLgLabelFontSize 22
#define BrkButtonSecondaryLgLabelLetterSpacing 2%
#define BrkButtonSecondaryLgLabelParagraphSpacing 
#define BrkButtonSecondaryLgLabelTextDecoration none
#define BrkButtonSecondaryLgLabelTextCase none
#define BrkButtonSecondaryXlLabelFontFamily Arial
#define BrkButtonSecondaryXlLabelFontWeight Bold
#define BrkButtonSecondaryXlLabelLineHeight 100%
#define BrkButtonSecondaryXlLabelFontSize 26
#define BrkButtonSecondaryXlLabelLetterSpacing 2%
#define BrkButtonSecondaryXlLabelParagraphSpacing 
#define BrkButtonSecondaryXlLabelTextDecoration none
#define BrkButtonSecondaryXlLabelTextCase none
#define BrkButtonSecondaryStandardFontColorDefault #000000
#define BrkButtonSecondaryStandardIconFillDefault #000000
#define BrkButtonSecondaryStandardSmBoxShadowDefault [object Object]
#define BrkButtonSecondaryStandardSmBoxShadowHover [object Object]
#define BrkButtonSecondaryStandardSmBoxShadowFocus [object Object]
#define BrkButtonSecondaryStandardBackgroundColorDefault #ffffff
#define BrkButtonSecondaryStandardBorderColorDefault #000000
#define BrkButtonSecondaryStandardFontColorHover #000000
#define BrkButtonSecondaryStandardIconColorHover #000000
#define BrkButtonSecondaryStandardBackgroundColorHover #ffffff
#define BrkButtonSecondaryStandardBorderColorHover #000000
#define BrkButtonSecondaryStandardFontColorFocus #000000
#define BrkButtonSecondaryStandardIconColorFocus #000000
#define BrkButtonSecondaryStandardBackgroundColorFocus #ffffff
#define BrkButtonSecondaryStandardBorderColorFocus #000000
#define BrkButtonSecondaryStandardMdBoxShadowDefault [object Object]
#define BrkButtonSecondaryStandardMdBoxShadowHover [object Object]
#define BrkButtonSecondaryStandardMdBoxShadowFocus [object Object]
#define BrkButtonSecondaryInvertedSmBoxShadowDefault [object Object]
#define BrkButtonSecondaryInvertedSmBoxShadowHover [object Object]
#define BrkButtonSecondaryInvertedSmBoxShadowFocus [object Object]
#define BrkButtonSecondaryInvertedFontColorDefault #ffffff
#define BrkButtonSecondaryInvertedIconColorDefault #ffffff
#define BrkButtonSecondaryInvertedBackgroundColorDefault #000000
#define BrkButtonSecondaryInvertedBorderColorDefault #ffffff
#define BrkButtonSecondaryInvertedFontColorHover #ffffff
#define BrkButtonSecondaryInvertedIconColorHover #ffffff
#define BrkButtonSecondaryInvertedBackgroundColorHover #000000
#define BrkButtonSecondaryInvertedBorderColorHover #ffffff
#define BrkButtonSecondaryInvertedFontColorFocus #ffffff
#define BrkButtonSecondaryInvertedIconColorFocus #ffffff
#define BrkButtonSecondaryInvertedBackgroundColorFocus #000000
#define BrkButtonSecondaryInvertedBorderColorFocus #ffffff
#define BrkButtonSecondaryInvertedMdBoxShadowDefault [object Object]
#define BrkButtonSecondaryInvertedMdBoxShadowHover [object Object]
#define BrkButtonSecondaryInvertedMdBoxShadowFocus [object Object]
#define BrkButtonTertiarySmLabelFontFamily Graphik
#define BrkButtonTertiarySmLabelFontWeight Bold
#define BrkButtonTertiarySmLabelLineHeight 100%
#define BrkButtonTertiarySmLabelFontSize 10
#define BrkButtonTertiarySmLabelLetterSpacing 0%
#define BrkButtonTertiarySmLabelParagraphSpacing 
#define BrkButtonTertiarySmLabelTextDecoration none
#define BrkButtonTertiarySmLabelTextCase uppercase
#define BrkButtonTertiaryMdLabelFontFamily Graphik
#define BrkButtonTertiaryMdLabelFontWeight Bold
#define BrkButtonTertiaryMdLabelLineHeight 100%
#define BrkButtonTertiaryMdLabelFontSize 14
#define BrkButtonTertiaryMdLabelLetterSpacing 0%
#define BrkButtonTertiaryMdLabelParagraphSpacing 
#define BrkButtonTertiaryMdLabelTextDecoration none
#define BrkButtonTertiaryMdLabelTextCase uppercase
#define BrkButtonTertiaryLgLabelFontFamily Graphik
#define BrkButtonTertiaryLgLabelFontWeight Bold
#define BrkButtonTertiaryLgLabelLineHeight 100%
#define BrkButtonTertiaryLgLabelFontSize 18
#define BrkButtonTertiaryLgLabelLetterSpacing 0%
#define BrkButtonTertiaryLgLabelParagraphSpacing 
#define BrkButtonTertiaryLgLabelTextDecoration none
#define BrkButtonTertiaryLgLabelTextCase uppercase
#define BrkButtonTertiaryXlLabelFontFamily Graphik
#define BrkButtonTertiaryXlLabelFontWeight Bold
#define BrkButtonTertiaryXlLabelLineHeight 100%
#define BrkButtonTertiaryXlLabelFontSize 22
#define BrkButtonTertiaryXlLabelLetterSpacing 0%
#define BrkButtonTertiaryXlLabelParagraphSpacing 
#define BrkButtonTertiaryXlLabelTextDecoration none
#define BrkButtonTertiaryXlLabelTextCase uppercase
#define BrkButtonTertiarySmPaddingHorizontal 15
#define BrkButtonTertiarySmHeight 30
#define BrkButtonTertiarySmBorderRadius 15
#define BrkButtonTertiarySmIconSize 8
#define BrkButtonTertiarySmIconGap 2
#define BrkButtonTertiaryMdPaddingHorizontal 20
#define BrkButtonTertiaryMdHeight 40
#define BrkButtonTertiaryMdBorderRadius 20
#define BrkButtonTertiaryMdIconSize 10
#define BrkButtonTertiaryMdIconGap 4
#define BrkButtonTertiaryLgPaddingHorizontal 25
#define BrkButtonTertiaryLgHeight 50
#define BrkButtonTertiaryLgBorderRadius 25
#define BrkButtonTertiaryLgIconSize 12
#define BrkButtonTertiaryLgIconGap 6
#define BrkButtonTertiaryXlPaddingHorizontal 30
#define BrkButtonTertiaryXlHeight 60
#define BrkButtonTertiaryXlBorderRadius 30
#define BrkButtonTertiaryXlIconSize 14
#define BrkButtonTertiaryXlIconGap 8
#define BrkButtonTertiaryStandardBoxShadowDefault [object Object]
#define BrkButtonTertiaryStandardBoxShadowHover [object Object]
#define BrkButtonTertiaryStandardBoxShadowFocus [object Object]
#define BrkButtonTertiaryStandardFontColorDefault #535353
#define BrkButtonTertiaryStandardIconFillDefault #535353
#define BrkButtonTertiaryStandardBackgroundColorDefault #ffffff
#define BrkButtonTertiaryStandardBorderColorDefault #e6e6e6
#define BrkButtonTertiaryStandardFontColorHover #1a1a1a
#define BrkButtonTertiaryStandardIconFillHover #1a1a1a
#define BrkButtonTertiaryStandardBackgroundColorHover #ffffff
#define BrkButtonTertiaryStandardBorderColorHover #535353
#define BrkButtonTertiaryStandardFontColorFocus #1a1a1a
#define BrkButtonTertiaryStandardIconFillFocus #1a1a1a
#define BrkButtonTertiaryStandardBackgroundColorFocus #ffffff
#define BrkButtonTertiaryStandardBorderColorFocus #535353
#define BrkButtonTertiaryInvertedBoxShadowDefault [object Object]
#define BrkButtonTertiaryInvertedBoxShadowHover [object Object]
#define BrkButtonTertiaryInvertedBoxShadowFocus [object Object]
#define BrkButtonTertiaryInvertedFontColorDefault #e6e6e6
#define BrkButtonTertiaryInvertedIconFillDefault #e6e6e6
#define BrkButtonTertiaryInvertedBackgroundColorDefault #1a1a1a
#define BrkButtonTertiaryInvertedBorderColorDefault #535353
#define BrkButtonTertiaryInvertedFontColorHover #ffffff
#define BrkButtonTertiaryInvertedIconFillHover #ffffff
#define BrkButtonTertiaryInvertedBackgroundColorHover #1a1a1a
#define BrkButtonTertiaryInvertedBorderColorHover #f2f2f2
#define BrkButtonTertiaryInvertedFontColorFocus #ffffff
#define BrkButtonTertiaryInvertedIconFillFocus #ffffff
#define BrkButtonTertiaryInvertedBackgroundColorFocus #1a1a1a
#define BrkButtonTertiaryInvertedBorderColorFocus #ffffff
#define BrkCardHeroBorderRadius 16
#define BrkCardHeroBorderWidth 1
#define BrkCardHeroSmPaddingHorizontal 10
#define BrkCardHeroSmPaddingVertical 10
#define BrkCardHeroSmHeadingMarginVertical 4
#define BrkCardHeroSmContentGap 16
#define BrkCardHeroSmPretitleFontFamily Graphik
#define BrkCardHeroSmPretitleFontWeight Bold
#define BrkCardHeroSmPretitleLineHeight 9
#define BrkCardHeroSmPretitleFontSize 9
#define BrkCardHeroSmPretitleLetterSpacing -2%
#define BrkCardHeroSmPretitleParagraphSpacing 
#define BrkCardHeroSmPretitleTextDecoration none
#define BrkCardHeroSmPretitleTextCase uppercase
#define BrkCardHeroSmHeadingFontFamily Graphik
#define BrkCardHeroSmHeadingFontWeight Bold
#define BrkCardHeroSmHeadingLineHeight 12
#define BrkCardHeroSmHeadingFontSize 12
#define BrkCardHeroSmHeadingLetterSpacing -2%
#define BrkCardHeroSmHeadingParagraphSpacing 
#define BrkCardHeroSmHeadingTextCase none
#define BrkCardHeroSmHeadingTextDecoration none
#define BrkCardHeroSmBodyFontFamily Arial
#define BrkCardHeroSmBodyFontWeight Regular
#define BrkCardHeroSmBodyLineHeight 100%
#define BrkCardHeroSmBodyFontSize 10
#define BrkCardHeroSmBodyLetterSpacing 0%
#define BrkCardHeroSmBodyParagraphSpacing 
#define BrkCardHeroSmBodyTextDecoration none
#define BrkCardHeroSmBodyTextCase none
#define BrkCardHeroSmImageHeight 180
#define BrkCardHeroMdPaddingHorizontal 16
#define BrkCardHeroMdPaddingVertical 16
#define BrkCardHeroMdHeadingMarginVertical 4
#define BrkCardHeroMdContentGap 24
#define BrkCardHeroMdPretitleFontFamily Graphik
#define BrkCardHeroMdPretitleFontWeight Bold
#define BrkCardHeroMdPretitleLineHeight 13
#define BrkCardHeroMdPretitleFontSize 13
#define BrkCardHeroMdPretitleLetterSpacing -2%
#define BrkCardHeroMdPretitleParagraphSpacing 
#define BrkCardHeroMdPretitleTextDecoration none
#define BrkCardHeroMdPretitleTextCase uppercase
#define BrkCardHeroMdHeadingFontFamily Graphik
#define BrkCardHeroMdHeadingFontWeight Bold
#define BrkCardHeroMdHeadingLineHeight 110%
#define BrkCardHeroMdHeadingFontSize 22
#define BrkCardHeroMdHeadingLetterSpacing -2%
#define BrkCardHeroMdHeadingParagraphSpacing 
#define BrkCardHeroMdHeadingTextCase none
#define BrkCardHeroMdHeadingTextDecoration none
#define BrkCardHeroMdBodyFontFamily Arial
#define BrkCardHeroMdBodyFontWeight Regular
#define BrkCardHeroMdBodyLineHeight 100%
#define BrkCardHeroMdBodyFontSize 13
#define BrkCardHeroMdBodyLetterSpacing 0%
#define BrkCardHeroMdBodyParagraphSpacing 
#define BrkCardHeroMdBodyTextDecoration none
#define BrkCardHeroMdBodyTextCase none
#define BrkCardHeroMdImageHeight 270
#define BrkCardHeroLgPaddingHorizontal 24
#define BrkCardHeroLgPaddingVertical 24
#define BrkCardHeroLgHeadingMarginVertical 8
#define BrkCardHeroLgContentGap 24
#define BrkCardHeroLgPretitleFontFamily Graphik
#define BrkCardHeroLgPretitleFontWeight Bold
#define BrkCardHeroLgPretitleLineHeight 16
#define BrkCardHeroLgPretitleFontSize 16
#define BrkCardHeroLgPretitleLetterSpacing -2%
#define BrkCardHeroLgPretitleParagraphSpacing 
#define BrkCardHeroLgPretitleTextDecoration none
#define BrkCardHeroLgPretitleTextCase uppercase
#define BrkCardHeroLgHeadingFontFamily Graphik
#define BrkCardHeroLgHeadingFontWeight Bold
#define BrkCardHeroLgHeadingLineHeight 110%
#define BrkCardHeroLgHeadingFontSize 24
#define BrkCardHeroLgHeadingLetterSpacing -2%
#define BrkCardHeroLgHeadingParagraphSpacing 
#define BrkCardHeroLgHeadingTextCase none
#define BrkCardHeroLgHeadingTextDecoration none
#define BrkCardHeroLgBodyFontFamily Arial
#define BrkCardHeroLgBodyFontWeight Regular
#define BrkCardHeroLgBodyLineHeight 100%
#define BrkCardHeroLgBodyFontSize 16
#define BrkCardHeroLgBodyLetterSpacing 0%
#define BrkCardHeroLgBodyParagraphSpacing 
#define BrkCardHeroLgBodyTextDecoration none
#define BrkCardHeroLgBodyTextCase none
#define BrkCardHeroLgImageHeight 270
#define BrkCardHeroXlPaddingHorizontal 24
#define BrkCardHeroXlPaddingVertical 24
#define BrkCardHeroXlHeadingMarginVertical 8
#define BrkCardHeroXlContentGap 16
#define BrkCardHeroXlPretitleFontFamily Graphik
#define BrkCardHeroXlPretitleFontWeight Bold
#define BrkCardHeroXlPretitleLineHeight 20
#define BrkCardHeroXlPretitleFontSize 20
#define BrkCardHeroXlPretitleLetterSpacing -2%
#define BrkCardHeroXlPretitleParagraphSpacing 
#define BrkCardHeroXlPretitleTextDecoration none
#define BrkCardHeroXlPretitleTextCase uppercase
#define BrkCardHeroXlHeadingFontFamily Graphik
#define BrkCardHeroXlHeadingFontWeight Bold
#define BrkCardHeroXlHeadingLineHeight 110%
#define BrkCardHeroXlHeadingFontSize 32
#define BrkCardHeroXlHeadingLetterSpacing -2%
#define BrkCardHeroXlHeadingParagraphSpacing 
#define BrkCardHeroXlHeadingTextCase none
#define BrkCardHeroXlHeadingTextDecoration none
#define BrkCardHeroXlBodyFontFamily Arial
#define BrkCardHeroXlBodyFontWeight Regular
#define BrkCardHeroXlBodyLineHeight 110%
#define BrkCardHeroXlBodyFontSize 20
#define BrkCardHeroXlBodyLetterSpacing 0%
#define BrkCardHeroXlBodyParagraphSpacing 
#define BrkCardHeroXlBodyTextDecoration none
#define BrkCardHeroXlBodyTextCase none
#define BrkCardHeroXlImageHeight 360
#define BrkCardHeroStandardBoxShadowDefault [object Object]
#define BrkCardHeroStandardBoxShadowHover [object Object]
#define BrkCardHeroStandardPretitleFontColor #535353
#define BrkCardHeroStandardHeadingFontColor #060606
#define BrkCardHeroStandardBodyFontColor #1a1a1a
#define BrkCardHeroStandardBackgroundColor #ffffff
#define BrkCardHeroStandardBorderColor #e6e6e6
#define BrkJackpotHeroSmPaddingHorizontal 10
#define BrkJackpotHeroSmAmountDigitMargin 1
#define BrkJackpotHeroSmAmountGroupMargin 4
#define BrkJackpotHeroSmContentGap 16
#define BrkJackpotHeroSmHeadingFontFamily Graphik
#define BrkJackpotHeroSmHeadingFontWeight Bold
#define BrkJackpotHeroSmHeadingLineHeight 110%
#define BrkJackpotHeroSmHeadingFontSize 10
#define BrkJackpotHeroSmHeadingLetterSpacing -2%
#define BrkJackpotHeroSmHeadingParagraphSpacing 
#define BrkJackpotHeroSmHeadingTextCase none
#define BrkJackpotHeroSmHeadingTextDecoration none
#define BrkJackpotHeroSmBodyFontFamily Arial
#define BrkJackpotHeroSmBodyFontWeight Bold
#define BrkJackpotHeroSmBodyLineHeight 100%
#define BrkJackpotHeroSmBodyFontSize 12
#define BrkJackpotHeroSmBodyLetterSpacing 0%
#define BrkJackpotHeroSmBodyParagraphSpacing 
#define BrkJackpotHeroSmBodyTextCase none
#define BrkJackpotHeroSmBodyTextDecoration none
#define BrkJackpotHeroSmHeight 36
#define BrkJackpotHeroSmAmountDigitHeight 20
#define BrkJackpotHeroSmAmountDigitWidth 14
#define BrkJackpotHeroMdPaddingHorizontal 16
#define BrkJackpotHeroMdAmountDigitMargin 2
#define BrkJackpotHeroMdAmountGroupMargin 5
#define BrkJackpotHeroMdContentGap 16
#define BrkJackpotHeroMdHeadingFontFamily Graphik
#define BrkJackpotHeroMdHeadingFontWeight Bold
#define BrkJackpotHeroMdHeadingLineHeight 110%
#define BrkJackpotHeroMdHeadingFontSize 16
#define BrkJackpotHeroMdHeadingLetterSpacing -2%
#define BrkJackpotHeroMdHeadingParagraphSpacing 
#define BrkJackpotHeroMdHeadingTextCase none
#define BrkJackpotHeroMdHeadingTextDecoration none
#define BrkJackpotHeroMdBodyFontFamily Arial
#define BrkJackpotHeroMdBodyFontWeight Bold
#define BrkJackpotHeroMdBodyLineHeight 100%
#define BrkJackpotHeroMdBodyFontSize 20
#define BrkJackpotHeroMdBodyLetterSpacing 0%
#define BrkJackpotHeroMdBodyParagraphSpacing 
#define BrkJackpotHeroMdBodyTextCase none
#define BrkJackpotHeroMdBodyTextDecoration none
#define BrkJackpotHeroMdHeight 60
#define BrkJackpotHeroMdAmountDigitHeight 28
#define BrkJackpotHeroMdAmountDigitWidth 20
#define BrkJackpotHeroLgPaddingHorizontal 24
#define BrkJackpotHeroLgAmountDigitMargin 3
#define BrkJackpotHeroLgAmountGroupMargin 6
#define BrkJackpotHeroLgContentGap 24
#define BrkJackpotHeroLgHeadingFontFamily Graphik
#define BrkJackpotHeroLgHeadingFontWeight Bold
#define BrkJackpotHeroLgHeadingLineHeight 110%
#define BrkJackpotHeroLgHeadingFontSize 20
#define BrkJackpotHeroLgHeadingLetterSpacing -2%
#define BrkJackpotHeroLgHeadingParagraphSpacing 
#define BrkJackpotHeroLgHeadingTextCase none
#define BrkJackpotHeroLgHeadingTextDecoration none
#define BrkJackpotHeroLgBodyFontFamily Arial
#define BrkJackpotHeroLgBodyFontWeight Bold
#define BrkJackpotHeroLgBodyLineHeight 100%
#define BrkJackpotHeroLgBodyFontSize 24
#define BrkJackpotHeroLgBodyLetterSpacing 2%
#define BrkJackpotHeroLgBodyParagraphSpacing 
#define BrkJackpotHeroLgBodyTextCase none
#define BrkJackpotHeroLgBodyTextDecoration none
#define BrkJackpotHeroLgHeight 72
#define BrkJackpotHeroLgAmountDigitHeight 40
#define BrkJackpotHeroLgAmountDigitWidth 30
#define BrkJackpotHeroXlPaddingHorizontal 24
#define BrkJackpotHeroXlAmountDigitMargin 4
#define BrkJackpotHeroXlAmountGroupMargin 8
#define BrkJackpotHeroXlContentGap 24
#define BrkJackpotHeroXlHeadingFontFamily Graphik
#define BrkJackpotHeroXlHeadingFontWeight Bold
#define BrkJackpotHeroXlHeadingLineHeight 110%
#define BrkJackpotHeroXlHeadingFontSize 20
#define BrkJackpotHeroXlHeadingLetterSpacing -2%
#define BrkJackpotHeroXlHeadingParagraphSpacing 
#define BrkJackpotHeroXlHeadingTextCase none
#define BrkJackpotHeroXlHeadingTextDecoration none
#define BrkJackpotHeroXlBodyFontFamily Arial
#define BrkJackpotHeroXlBodyFontWeight Bold
#define BrkJackpotHeroXlBodyLineHeight 110%
#define BrkJackpotHeroXlBodyFontSize 28
#define BrkJackpotHeroXlBodyLetterSpacing 0%
#define BrkJackpotHeroXlBodyParagraphSpacing 
#define BrkJackpotHeroXlBodyTextCase none
#define BrkJackpotHeroXlBodyTextDecoration none
#define BrkJackpotHeroXlHeight 72
#define BrkJackpotHeroXlAmountDigitHeight 44
#define BrkJackpotHeroXlAmountDigitWidth 30
#define BrkJackpotHeroAmountDigitBorderWidth 0
#define BrkJackpotHeroAmountDigitBorderRadius 4
#define BrkJackpotHeroStandardHeadingFontColor #ffffff
#define BrkJackpotHeroStandardBodyFontColor #090f2a
#define BrkJackpotHeroStandardBodyBoxBackgroundColor #ffffff
#define BrkJackpotHeroStandardBodyBoxBorderColor transparent
#define BrkJackpotHeroStandardBackgroundColor #060606
#define BrkJackpotHeroStandardSymbolFontColor #ffffff
#define BrkCardHighDensitySmImageHeight 42
#define BrkCardHighDensitySmCardHeight 50
#define BrkCardHighDensitySmContentGap 8
#define BrkCardHighDensitySmImageBorderRadius 10
#define BrkCardHighDensitySmHeadingFontFamily Graphik
#define BrkCardHighDensitySmHeadingFontWeight Bold
#define BrkCardHighDensitySmHeadingLineHeight 110%
#define BrkCardHighDensitySmHeadingFontSize 10
#define BrkCardHighDensitySmHeadingLetterSpacing -2%
#define BrkCardHighDensitySmHeadingParagraphSpacing 0
#define BrkCardHighDensitySmHeadingTextDecoration none
#define BrkCardHighDensitySmHeadingTextCase none
#define BrkCardHighDensitySmSubtitleFontFamily Graphik
#define BrkCardHighDensitySmSubtitleFontWeight Bold
#define BrkCardHighDensitySmSubtitleLineHeight 100%
#define BrkCardHighDensitySmSubtitleFontSize 11
#define BrkCardHighDensitySmSubtitleLetterSpacing -2%
#define BrkCardHighDensitySmSubtitleParagraphSpacing 0
#define BrkCardHighDensitySmSubtitleTextDecoration none
#define BrkCardHighDensitySmSubtitleTextCase none
#define BrkCardHighDensitySmBodyFontFamily Arial
#define BrkCardHighDensitySmBodyFontWeight Regular
#define BrkCardHighDensitySmBodyLineHeight 100%
#define BrkCardHighDensitySmBodyFontSize 10
#define BrkCardHighDensitySmBodyLetterSpacing 0%
#define BrkCardHighDensitySmBodyParagraphSpacing 0
#define BrkCardHighDensitySmBodyTextDecoration none
#define BrkCardHighDensitySmBodyTextCase none
#define BrkCardHighDensitySmHeadingMarginBottom 3
#define BrkCardHighDensitySmSubtitleMarginBottom 3
#define BrkCardHighDensityMdImageHeight 80
#define BrkCardHighDensityMdCardHeight 80
#define BrkCardHighDensityMdContentGap 20
#define BrkCardHighDensityMdImageBorderRadius 20
#define BrkCardHighDensityMdHeadingFontFamily Graphik
#define BrkCardHighDensityMdHeadingFontWeight Bold
#define BrkCardHighDensityMdHeadingLineHeight 110%
#define BrkCardHighDensityMdHeadingFontSize 20
#define BrkCardHighDensityMdHeadingLetterSpacing -2%
#define BrkCardHighDensityMdHeadingParagraphSpacing 0
#define BrkCardHighDensityMdHeadingTextDecoration none
#define BrkCardHighDensityMdHeadingTextCase none
#define BrkCardHighDensityMdSubtitleFontFamily Graphik
#define BrkCardHighDensityMdSubtitleFontWeight Bold
#define BrkCardHighDensityMdSubtitleLineHeight 100%
#define BrkCardHighDensityMdSubtitleFontSize 16
#define BrkCardHighDensityMdSubtitleLetterSpacing -2%
#define BrkCardHighDensityMdSubtitleParagraphSpacing 0
#define BrkCardHighDensityMdSubtitleTextDecoration none
#define BrkCardHighDensityMdSubtitleTextCase none
#define BrkCardHighDensityMdBodyFontFamily Arial
#define BrkCardHighDensityMdBodyFontWeight Regular
#define BrkCardHighDensityMdBodyLineHeight 100%
#define BrkCardHighDensityMdBodyFontSize 13
#define BrkCardHighDensityMdBodyLetterSpacing 0%
#define BrkCardHighDensityMdBodyParagraphSpacing 0
#define BrkCardHighDensityMdBodyTextDecoration none
#define BrkCardHighDensityMdBodyTextCase none
#define BrkCardHighDensityMdHeadingMarginBottom 3
#define BrkCardHighDensityMdSubtitleMarginBottom 3
#define BrkCardHighDensityLgImageHeight 90
#define BrkCardHighDensityLgCardHeight 90
#define BrkCardHighDensityLgContentGap 25
#define BrkCardHighDensityLgImageBorderRadius 25
#define BrkCardHighDensityLgHeadingFontFamily Graphik
#define BrkCardHighDensityLgHeadingFontWeight Bold
#define BrkCardHighDensityLgHeadingLineHeight 110%
#define BrkCardHighDensityLgHeadingFontSize 22
#define BrkCardHighDensityLgHeadingLetterSpacing -2%
#define BrkCardHighDensityLgHeadingParagraphSpacing 0
#define BrkCardHighDensityLgHeadingTextDecoration none
#define BrkCardHighDensityLgHeadingTextCase none
#define BrkCardHighDensityLgSubtitleFontFamily Graphik
#define BrkCardHighDensityLgSubtitleFontWeight Bold
#define BrkCardHighDensityLgSubtitleLineHeight 100%
#define BrkCardHighDensityLgSubtitleFontSize 20
#define BrkCardHighDensityLgSubtitleLetterSpacing -2%
#define BrkCardHighDensityLgSubtitleParagraphSpacing 0
#define BrkCardHighDensityLgSubtitleTextDecoration none
#define BrkCardHighDensityLgSubtitleTextCase none
#define BrkCardHighDensityLgBodyFontFamily Arial
#define BrkCardHighDensityLgBodyFontWeight Regular
#define BrkCardHighDensityLgBodyLineHeight 100%
#define BrkCardHighDensityLgBodyFontSize 16
#define BrkCardHighDensityLgBodyLetterSpacing 0%
#define BrkCardHighDensityLgBodyParagraphSpacing 0
#define BrkCardHighDensityLgBodyTextDecoration none
#define BrkCardHighDensityLgBodyTextCase none
#define BrkCardHighDensityLgHeadingMarginBottom 3
#define BrkCardHighDensityLgSubtitleMarginBottom 3
#define BrkCardHighDensityXlContentGap 30
#define BrkCardHighDensityXlHeadingMarginBottom 3
#define BrkCardHighDensityXlSubtitleMarginBottom 3
#define BrkCardHighDensityXlImageBorderRadius 30
#define BrkCardHighDensityXlHeadingFontFamily Graphik
#define BrkCardHighDensityXlHeadingFontWeight Bold
#define BrkCardHighDensityXlHeadingLineHeight 110%
#define BrkCardHighDensityXlHeadingFontSize 28
#define BrkCardHighDensityXlHeadingLetterSpacing -2%
#define BrkCardHighDensityXlHeadingParagraphSpacing 0
#define BrkCardHighDensityXlHeadingTextDecoration none
#define BrkCardHighDensityXlHeadingTextCase none
#define BrkCardHighDensityXlSubtitleFontFamily Graphik
#define BrkCardHighDensityXlSubtitleFontWeight Bold
#define BrkCardHighDensityXlSubtitleLineHeight 100%
#define BrkCardHighDensityXlSubtitleFontSize 25
#define BrkCardHighDensityXlSubtitleLetterSpacing -2%
#define BrkCardHighDensityXlSubtitleParagraphSpacing 0
#define BrkCardHighDensityXlSubtitleTextDecoration none
#define BrkCardHighDensityXlSubtitleTextCase none
#define BrkCardHighDensityXlBodyFontFamily Arial
#define BrkCardHighDensityXlBodyFontWeight Regular
#define BrkCardHighDensityXlBodyLineHeight 100%
#define BrkCardHighDensityXlBodyFontSize 20
#define BrkCardHighDensityXlBodyLetterSpacing 0%
#define BrkCardHighDensityXlBodyParagraphSpacing 0
#define BrkCardHighDensityXlBodyTextDecoration none
#define BrkCardHighDensityXlBodyTextCase none
#define BrkCardHighDensityXlImageHeight 115
#define BrkCardHighDensityXlCardHeight 115
#define BrkCardHighDensityStandardHeadingFontColor #060606
#define BrkCardHighDensityStandardSubtitleFontColor #285EB1
#define BrkCardHighDensityStandardBodyFontColor #1a1a1a
#define BrkCardHighDensityListBorderRadius 16
#define BrkCardHighDensityListBorderWidth 1
#define BrkCardHighDensityListSmPaddingVertical 15
#define BrkCardHighDensityListSmPaddingHorizontal 15
#define BrkCardHighDensityListSmSeparatorPaddingLeft 50
#define BrkCardHighDensityListSmSeparatorPaddingVertical 10
#define BrkCardHighDensityListMdPaddingVertical 20
#define BrkCardHighDensityListMdPaddingHorizontal 20
#define BrkCardHighDensityListMdSeparatorPaddingLeft 100
#define BrkCardHighDensityListMdSeparatorPaddingVertical 14
#define BrkCardHighDensityListLgPaddingVertical 20
#define BrkCardHighDensityListLgPaddingHorizontal 25
#define BrkCardHighDensityListLgSeparatorPaddingLeft 115
#define BrkCardHighDensityListLgSeparatorPaddingVertical 15
#define BrkCardHighDensityListXlPaddingVertical 30
#define BrkCardHighDensityListXlPaddingHorizontal 35
#define BrkCardHighDensityListXlSeparatorPaddingLeft 145
#define BrkCardHighDensityListXlSeparatorPaddingVertical 15
#define BrkCardHighDensityListSeparatorWidth 1
#define BrkCardHighDensityListStandardBackgroundColor #ffffff
#define BrkCardHighDensityListStandardBorderColor #e6e6e6
#define BrkCardHighDensityListStandardSeparatorColor #e6e6e6
#define BrkCardHighDensityListStandardBoxShadowDefault [object Object]
#define BrkCardHighDensityListStandardBoxShadowHover [object Object]
#define BrkPromoSecondaryBorderRadius 16
#define BrkPromoPrimaryBorderRadius 0
#define BrkPromoTertiaryBorderRadius 0
#define BrkPromoTertiaryFrameBorderRadius 16
#define BrkPromoPrimaryFrameBorderRadius 16
#define BrkPromoSecondaryFrameBorderRadius 16
#define BrkPromoPrimaryBorderWidth 1
#define BrkPromoSecondaryBorderWidth 1
#define BrkPromoTertiaryBorderWidth 1
#define BrkPromoPrimaryContentVerticalAlign center
#define BrkPromoSecondaryContentVerticalAlign center
#define BrkPromoTertiaryContentVerticalAlign flex-end
#define BrkPromoPrimarySmImageHeight 245
#define BrkPromoPrimarySmGradientHeight 61.25
#define BrkPromoPrimarySmPaddingHorizontal 16
#define BrkPromoPrimarySmPaddingVertical 16
#define BrkPromoPrimarySmContentGap 16
#define BrkPromoPrimarySmPretitleFontFamily Arial
#define BrkPromoPrimarySmPretitleFontWeight Bold
#define BrkPromoPrimarySmPretitleLineHeight 110%
#define BrkPromoPrimarySmPretitleFontSize 13
#define BrkPromoPrimarySmPretitleLetterSpacing 0%
#define BrkPromoPrimarySmPretitleParagraphSpacing 
#define BrkPromoPrimarySmPretitleTextDecoration none
#define BrkPromoPrimarySmPretitleTextCase none
#define BrkPromoPrimarySmPretitleMarginBottom 6
#define BrkPromoPrimarySmBodyMarginTop 8
#define BrkPromoPrimarySmHeadingFontFamily Graphik
#define BrkPromoPrimarySmHeadingFontWeight Super
#define BrkPromoPrimarySmHeadingLineHeight 110%
#define BrkPromoPrimarySmHeadingFontSize 28
#define BrkPromoPrimarySmHeadingLetterSpacing -2%
#define BrkPromoPrimarySmHeadingParagraphSpacing 
#define BrkPromoPrimarySmHeadingTextCase none
#define BrkPromoPrimarySmHeadingTextDecoration none
#define BrkPromoPrimarySmBodyFontFamily Arial
#define BrkPromoPrimarySmBodyFontWeight Regular
#define BrkPromoPrimarySmBodyLineHeight 120%
#define BrkPromoPrimarySmBodyFontSize 16
#define BrkPromoPrimarySmBodyLetterSpacing -2%
#define BrkPromoPrimarySmBodyParagraphSpacing 
#define BrkPromoPrimarySmBodyTextDecoration none
#define BrkPromoPrimarySmBodyTextCase none
#define BrkPromoPrimaryMdPaddingHorizontal 20
#define BrkPromoPrimaryMdPaddingVertical 20
#define BrkPromoPrimaryMdContentGap 16
#define BrkPromoPrimaryMdPretitleMarginBottom 6
#define BrkPromoPrimaryMdBodyMarginTop 12
#define BrkPromoPrimaryMdImageHeight 270
#define BrkPromoPrimaryMdGradientHeight 67.5
#define BrkPromoPrimaryMdPretitleFontFamily Arial
#define BrkPromoPrimaryMdPretitleFontWeight Bold
#define BrkPromoPrimaryMdPretitleLineHeight 110%
#define BrkPromoPrimaryMdPretitleFontSize 14
#define BrkPromoPrimaryMdPretitleLetterSpacing 0%
#define BrkPromoPrimaryMdPretitleParagraphSpacing 
#define BrkPromoPrimaryMdPretitleTextDecoration none
#define BrkPromoPrimaryMdPretitleTextCase none
#define BrkPromoPrimaryMdHeadingFontFamily Graphik
#define BrkPromoPrimaryMdHeadingFontWeight Super
#define BrkPromoPrimaryMdHeadingLineHeight 110%
#define BrkPromoPrimaryMdHeadingFontSize 28
#define BrkPromoPrimaryMdHeadingLetterSpacing -2%
#define BrkPromoPrimaryMdHeadingParagraphSpacing 
#define BrkPromoPrimaryMdHeadingTextCase none
#define BrkPromoPrimaryMdHeadingTextDecoration none
#define BrkPromoPrimaryMdBodyFontFamily Arial
#define BrkPromoPrimaryMdBodyFontWeight Regular
#define BrkPromoPrimaryMdBodyLineHeight 120%
#define BrkPromoPrimaryMdBodyFontSize 18
#define BrkPromoPrimaryMdBodyLetterSpacing -2%
#define BrkPromoPrimaryMdBodyParagraphSpacing 
#define BrkPromoPrimaryMdBodyTextDecoration none
#define BrkPromoPrimaryMdBodyTextCase none
#define BrkPromoPrimaryLgImageHeight 300
#define BrkPromoPrimaryLgGradientHeight 75
#define BrkPromoPrimaryLgPretitleFontFamily Arial
#define BrkPromoPrimaryLgPretitleFontWeight Bold
#define BrkPromoPrimaryLgPretitleLineHeight 110%
#define BrkPromoPrimaryLgPretitleFontSize 16
#define BrkPromoPrimaryLgPretitleLetterSpacing 0%
#define BrkPromoPrimaryLgPretitleParagraphSpacing 
#define BrkPromoPrimaryLgPretitleTextDecoration none
#define BrkPromoPrimaryLgPretitleTextCase none
#define BrkPromoPrimaryLgHeadingFontFamily Graphik
#define BrkPromoPrimaryLgHeadingFontWeight Super
#define BrkPromoPrimaryLgHeadingLineHeight 110%
#define BrkPromoPrimaryLgHeadingFontSize 32
#define BrkPromoPrimaryLgHeadingLetterSpacing -2%
#define BrkPromoPrimaryLgHeadingParagraphSpacing 
#define BrkPromoPrimaryLgHeadingTextCase none
#define BrkPromoPrimaryLgHeadingTextDecoration none
#define BrkPromoPrimaryLgBodyFontFamily Arial
#define BrkPromoPrimaryLgBodyFontWeight Regular
#define BrkPromoPrimaryLgBodyLineHeight 120%
#define BrkPromoPrimaryLgBodyFontSize 20
#define BrkPromoPrimaryLgBodyLetterSpacing -2%
#define BrkPromoPrimaryLgBodyParagraphSpacing 
#define BrkPromoPrimaryLgBodyTextDecoration none
#define BrkPromoPrimaryLgBodyTextCase none
#define BrkPromoPrimaryLgPaddingHorizontal 24
#define BrkPromoPrimaryLgPaddingVertical 24
#define BrkPromoPrimaryLgContentGap 16
#define BrkPromoPrimaryLgPretitleMarginBottom 6
#define BrkPromoPrimaryLgBodyMarginTop 10
#define BrkPromoPrimaryXlImageHeight 568
#define BrkPromoPrimaryXlGradientHeight 142
#define BrkPromoPrimaryXlContentWidth 40%
#define BrkPromoPrimaryXlContentMaxWidth 470
#define BrkPromoPrimaryXlPretitleFontFamily Arial
#define BrkPromoPrimaryXlPretitleFontWeight Bold
#define BrkPromoPrimaryXlPretitleLineHeight 110%
#define BrkPromoPrimaryXlPretitleFontSize 16
#define BrkPromoPrimaryXlPretitleLetterSpacing 0%
#define BrkPromoPrimaryXlPretitleParagraphSpacing 
#define BrkPromoPrimaryXlPretitleTextDecoration none
#define BrkPromoPrimaryXlPretitleTextCase none
#define BrkPromoPrimaryXlHeadingFontFamily Graphik
#define BrkPromoPrimaryXlHeadingFontWeight Super
#define BrkPromoPrimaryXlHeadingLineHeight 110%
#define BrkPromoPrimaryXlHeadingFontSize 42
#define BrkPromoPrimaryXlHeadingLetterSpacing -2%
#define BrkPromoPrimaryXlHeadingParagraphSpacing 
#define BrkPromoPrimaryXlHeadingTextCase none
#define BrkPromoPrimaryXlHeadingTextDecoration none
#define BrkPromoPrimaryXlBodyFontFamily Arial
#define BrkPromoPrimaryXlBodyFontWeight Regular
#define BrkPromoPrimaryXlBodyLineHeight 120%
#define BrkPromoPrimaryXlBodyFontSize 20
#define BrkPromoPrimaryXlBodyLetterSpacing -2%
#define BrkPromoPrimaryXlBodyParagraphSpacing 
#define BrkPromoPrimaryXlBodyTextDecoration none
#define BrkPromoPrimaryXlBodyTextCase none
#define BrkPromoPrimaryXlPaddingHorizontal 32
#define BrkPromoPrimaryXlPaddingVertical 32
#define BrkPromoPrimaryXlContentGap 16
#define BrkPromoPrimaryXlPretitleMarginBottom 6
#define BrkPromoPrimaryXlBodyMarginTop 16
#define BrkPromoPrimaryStandardPretitleFontColor #060606
#define BrkPromoPrimaryStandardHeadingFontColor #060606
#define BrkPromoPrimaryStandardBodyFontColor #060606
#define BrkPromoPrimaryStandardBackgroundColor #ffffff
#define BrkPromoPrimaryStandardBorderColor #e6e6e6
#define BrkPromoPrimaryStandardGradientColor linear-gradient(180deg, #ffffff00 0%, #ffffff 100%)
#define BrkPromoPrimaryStandardFrameColor transparent
#define BrkPromoPrimaryInvertedPretitleFontColor #ffffff
#define BrkPromoPrimaryInvertedHeadingFontColor #ffffff
#define BrkPromoPrimaryInvertedBodyFontColor #ffffff
#define BrkPromoPrimaryInvertedBackgroundColor #000000
#define BrkPromoPrimaryInvertedBorderColor #e6e6e6
#define BrkPromoPrimaryInvertedGradientColor linear-gradient(180deg, #00000000 0%, #000000 100%)
#define BrkPromoPrimaryInvertedFrameColor transparent
#define BrkPromoSecondarySmImageHeight 172
#define BrkPromoSecondarySmGradientHeight 43
#define BrkPromoSecondarySmPretitleFontFamily Arial
#define BrkPromoSecondarySmPretitleFontWeight Bold
#define BrkPromoSecondarySmPretitleLineHeight 110%
#define BrkPromoSecondarySmPretitleFontSize 8
#define BrkPromoSecondarySmPretitleLetterSpacing 0%
#define BrkPromoSecondarySmPretitleParagraphSpacing 
#define BrkPromoSecondarySmPretitleTextDecoration none
#define BrkPromoSecondarySmPretitleTextCase none
#define BrkPromoSecondarySmHeadingFontFamily Graphik
#define BrkPromoSecondarySmHeadingFontWeight Super
#define BrkPromoSecondarySmHeadingLineHeight 110%
#define BrkPromoSecondarySmHeadingFontSize 15
#define BrkPromoSecondarySmHeadingLetterSpacing -2%
#define BrkPromoSecondarySmHeadingParagraphSpacing 
#define BrkPromoSecondarySmHeadingTextCase none
#define BrkPromoSecondarySmHeadingTextDecoration none
#define BrkPromoSecondarySmPaddingHorizontal 16
#define BrkPromoSecondarySmPaddingVertical 15
#define BrkPromoSecondarySmContentGap 8
#define BrkPromoSecondarySmPretitleMarginBottom 4
#define BrkPromoSecondaryMdImageHeight 270
#define BrkPromoSecondaryMdGradientHeight 67.5
#define BrkPromoSecondaryMdPretitleFontFamily Arial
#define BrkPromoSecondaryMdPretitleFontWeight Bold
#define BrkPromoSecondaryMdPretitleLineHeight 110%
#define BrkPromoSecondaryMdPretitleFontSize 12
#define BrkPromoSecondaryMdPretitleLetterSpacing 0%
#define BrkPromoSecondaryMdPretitleParagraphSpacing 
#define BrkPromoSecondaryMdPretitleTextDecoration none
#define BrkPromoSecondaryMdPretitleTextCase none
#define BrkPromoSecondaryMdHeadingFontFamily Graphik
#define BrkPromoSecondaryMdHeadingFontWeight Super
#define BrkPromoSecondaryMdHeadingLineHeight 110%
#define BrkPromoSecondaryMdHeadingFontSize 28
#define BrkPromoSecondaryMdHeadingLetterSpacing -2%
#define BrkPromoSecondaryMdHeadingParagraphSpacing 
#define BrkPromoSecondaryMdHeadingTextCase none
#define BrkPromoSecondaryMdHeadingTextDecoration none
#define BrkPromoSecondaryMdPaddingHorizontal 20
#define BrkPromoSecondaryMdPaddingVertical 20
#define BrkPromoSecondaryMdContentGap 10
#define BrkPromoSecondaryMdPretitleMarginBottom 4
#define BrkPromoSecondaryLgImageHeight 300
#define BrkPromoSecondaryLgGradientHeight 75
#define BrkPromoSecondaryLgPretitleFontFamily Arial
#define BrkPromoSecondaryLgPretitleFontWeight Bold
#define BrkPromoSecondaryLgPretitleLineHeight 110%
#define BrkPromoSecondaryLgPretitleFontSize 13
#define BrkPromoSecondaryLgPretitleLetterSpacing 0%
#define BrkPromoSecondaryLgPretitleParagraphSpacing 
#define BrkPromoSecondaryLgPretitleTextDecoration none
#define BrkPromoSecondaryLgPretitleTextCase none
#define BrkPromoSecondaryLgHeadingFontFamily Graphik
#define BrkPromoSecondaryLgHeadingFontWeight Super
#define BrkPromoSecondaryLgHeadingLineHeight 110%
#define BrkPromoSecondaryLgHeadingFontSize 32
#define BrkPromoSecondaryLgHeadingLetterSpacing -2%
#define BrkPromoSecondaryLgHeadingParagraphSpacing 
#define BrkPromoSecondaryLgHeadingTextCase none
#define BrkPromoSecondaryLgHeadingTextDecoration none
#define BrkPromoSecondaryLgPaddingHorizontal 24
#define BrkPromoSecondaryLgPaddingVertical 20
#define BrkPromoSecondaryLgContentGap 12
#define BrkPromoSecondaryLgPretitleMarginBottom 4
#define BrkPromoSecondaryXlImageHeight 568
#define BrkPromoSecondaryXlGradientHeight 142
#define BrkPromoSecondaryXlContentWidth 50%
#define BrkPromoSecondaryXlPaddingHorizontal 32
#define BrkPromoSecondaryXlPaddingVertical 32
#define BrkPromoSecondaryXlContentGap 32
#define BrkPromoSecondaryXlPretitleMarginBottom 12
#define BrkPromoSecondaryXlPretitleFontFamily Arial
#define BrkPromoSecondaryXlPretitleFontWeight Bold
#define BrkPromoSecondaryXlPretitleLineHeight 110%
#define BrkPromoSecondaryXlPretitleFontSize 16
#define BrkPromoSecondaryXlPretitleLetterSpacing 0%
#define BrkPromoSecondaryXlPretitleParagraphSpacing 
#define BrkPromoSecondaryXlPretitleTextDecoration none
#define BrkPromoSecondaryXlPretitleTextCase none
#define BrkPromoSecondaryXlHeadingFontFamily Graphik
#define BrkPromoSecondaryXlHeadingFontWeight Super
#define BrkPromoSecondaryXlHeadingLineHeight 110%
#define BrkPromoSecondaryXlHeadingFontSize 42
#define BrkPromoSecondaryXlHeadingLetterSpacing -2%
#define BrkPromoSecondaryXlHeadingParagraphSpacing 
#define BrkPromoSecondaryXlHeadingTextCase none
#define BrkPromoSecondaryXlHeadingTextDecoration none
#define BrkPromoSecondaryStandardPretitleFontColor #000000
#define BrkPromoSecondaryStandardHeadingFontColor #000000
#define BrkPromoSecondaryStandardBodyFontColor #000000
#define BrkPromoSecondaryStandardBackgroundColor #ffffff
#define BrkPromoSecondaryStandardBorderColor #e6e6e6
#define BrkPromoSecondaryStandardGradientColor linear-gradient(180deg, #ffffff00 0%, #ffffff 100%)
#define BrkPromoSecondaryStandardBoxShadowDefault [object Object]
#define BrkPromoSecondaryStandardBoxShadowHover [object Object]
#define BrkPromoSecondaryStandardFrameColor transparent
#define BrkPromoSecondaryInvertedPretitleFontColor #ffffff
#define BrkPromoSecondaryInvertedHeadingFontColor #ffffff
#define BrkPromoSecondaryInvertedBodyFontColor #ffffff
#define BrkPromoSecondaryInvertedBackgroundColor #000000
#define BrkPromoSecondaryInvertedBorderColor #e6e6e6
#define BrkPromoSecondaryInvertedGradientColor linear-gradient(180deg, #00000000 0%, #000000 100%)
#define BrkPromoSecondaryInvertedFrameColor transparent
#define BrkPromoTertiarySmImageHeight 172
#define BrkPromoTertiarySmGradientHeight 43
#define BrkPromoTertiarySmPaddingHorizontal 16
#define BrkPromoTertiarySmPaddingVertical 16
#define BrkPromoTertiarySmFramePaddingHorizontal 16
#define BrkPromoTertiarySmFramePaddingVertical 16
#define BrkPromoTertiarySmContentGap 16
#define BrkPromoTertiarySmPretitleMarginBottom 4
#define BrkPromoTertiarySmPretitleFontFamily Arial
#define BrkPromoTertiarySmPretitleFontWeight Bold
#define BrkPromoTertiarySmPretitleLineHeight 110%
#define BrkPromoTertiarySmPretitleFontSize 13
#define BrkPromoTertiarySmPretitleLetterSpacing 0%
#define BrkPromoTertiarySmPretitleParagraphSpacing 
#define BrkPromoTertiarySmPretitleTextDecoration none
#define BrkPromoTertiarySmPretitleTextCase none
#define BrkPromoTertiarySmHeadingFontFamily Graphik
#define BrkPromoTertiarySmHeadingFontWeight Super
#define BrkPromoTertiarySmHeadingLineHeight 110%
#define BrkPromoTertiarySmHeadingFontSize 28
#define BrkPromoTertiarySmHeadingLetterSpacing -2%
#define BrkPromoTertiarySmHeadingParagraphSpacing 
#define BrkPromoTertiarySmHeadingTextCase none
#define BrkPromoTertiarySmHeadingTextDecoration none
#define BrkPromoTertiaryMdImageHeight 270
#define BrkPromoTertiaryMdGradientHeight 67.5
#define BrkPromoTertiaryMdPaddingHorizontal 20
#define BrkPromoTertiaryMdPaddingVertical 20
#define BrkPromoTertiaryMdFramePaddingHorizontal 20
#define BrkPromoTertiaryMdFramePaddingVertical 20
#define BrkPromoTertiaryMdContentGap 16
#define BrkPromoTertiaryMdPretitleMarginBottom 6
#define BrkPromoTertiaryMdPretitleFontFamily Arial
#define BrkPromoTertiaryMdPretitleFontWeight Bold
#define BrkPromoTertiaryMdPretitleLineHeight 110%
#define BrkPromoTertiaryMdPretitleFontSize 14
#define BrkPromoTertiaryMdPretitleLetterSpacing 0%
#define BrkPromoTertiaryMdPretitleParagraphSpacing 
#define BrkPromoTertiaryMdPretitleTextDecoration none
#define BrkPromoTertiaryMdPretitleTextCase none
#define BrkPromoTertiaryMdHeadingFontFamily Graphik
#define BrkPromoTertiaryMdHeadingFontWeight Super
#define BrkPromoTertiaryMdHeadingLineHeight 110%
#define BrkPromoTertiaryMdHeadingFontSize 28
#define BrkPromoTertiaryMdHeadingLetterSpacing -2%
#define BrkPromoTertiaryMdHeadingParagraphSpacing 
#define BrkPromoTertiaryMdHeadingTextCase none
#define BrkPromoTertiaryMdHeadingTextDecoration none
#define BrkPromoTertiaryLgImageHeight 300
#define BrkPromoTertiaryLgGradientHeight 75
#define BrkPromoTertiaryLgPaddingHorizontal 24
#define BrkPromoTertiaryLgPaddingVertical 24
#define BrkPromoTertiaryLgFramePaddingHorizontal 20
#define BrkPromoTertiaryLgFramePaddingVertical 20
#define BrkPromoTertiaryLgContentGap 16
#define BrkPromoTertiaryLgPretitleMarginBottom 6
#define BrkPromoTertiaryLgPretitleFontFamily Arial
#define BrkPromoTertiaryLgPretitleFontWeight Bold
#define BrkPromoTertiaryLgPretitleLineHeight 110%
#define BrkPromoTertiaryLgPretitleFontSize 16
#define BrkPromoTertiaryLgPretitleLetterSpacing 0%
#define BrkPromoTertiaryLgPretitleParagraphSpacing 
#define BrkPromoTertiaryLgPretitleTextDecoration none
#define BrkPromoTertiaryLgPretitleTextCase none
#define BrkPromoTertiaryLgHeadingFontFamily Graphik
#define BrkPromoTertiaryLgHeadingFontWeight Super
#define BrkPromoTertiaryLgHeadingLineHeight 110%
#define BrkPromoTertiaryLgHeadingFontSize 32
#define BrkPromoTertiaryLgHeadingLetterSpacing -2%
#define BrkPromoTertiaryLgHeadingParagraphSpacing 
#define BrkPromoTertiaryLgHeadingTextCase none
#define BrkPromoTertiaryLgHeadingTextDecoration none
#define BrkPromoTertiaryXlImageHeight 568
#define BrkPromoTertiaryXlGradientHeight 142
#define BrkPromoTertiaryXlContentWidth 40%
#define BrkPromoTertiaryXlContentMaxWidth 470
#define BrkPromoTertiaryXlPaddingHorizontal 32
#define BrkPromoTertiaryXlPaddingVertical 32
#define BrkPromoTertiaryXlFramePaddingHorizontal 10
#define BrkPromoTertiaryXlFramePaddingVertical 10
#define BrkPromoTertiaryXlContentGap 32
#define BrkPromoTertiaryXlPretitleMarginBottom 12
#define BrkPromoTertiaryXlPretitleFontFamily Arial
#define BrkPromoTertiaryXlPretitleFontWeight Bold
#define BrkPromoTertiaryXlPretitleLineHeight 110%
#define BrkPromoTertiaryXlPretitleFontSize 16
#define BrkPromoTertiaryXlPretitleLetterSpacing 0%
#define BrkPromoTertiaryXlPretitleParagraphSpacing 
#define BrkPromoTertiaryXlPretitleTextDecoration none
#define BrkPromoTertiaryXlPretitleTextCase none
#define BrkPromoTertiaryXlHeadingFontFamily Graphik
#define BrkPromoTertiaryXlHeadingFontWeight Super
#define BrkPromoTertiaryXlHeadingLineHeight 110%
#define BrkPromoTertiaryXlHeadingFontSize 42
#define BrkPromoTertiaryXlHeadingLetterSpacing -2%
#define BrkPromoTertiaryXlHeadingParagraphSpacing 
#define BrkPromoTertiaryXlHeadingTextCase none
#define BrkPromoTertiaryXlHeadingTextDecoration none
#define BrkPromoTertiaryStandardPretitleFontColor #000000
#define BrkPromoTertiaryStandardHeadingFontColor #000000
#define BrkPromoTertiaryStandardBodyFontColor #000000
#define BrkPromoTertiaryStandardBackgroundColor #000000
#define BrkPromoTertiaryStandardBorderColor #e6e6e6
#define BrkPromoTertiaryStandardGradientColor linear-gradient(180deg, #00000000 0%, #000000 100%)
#define BrkPromoTertiaryStandardFrameColor #ffffff
#define BrkPromoTertiaryInvertedPretitleFontColor #ffffff
#define BrkPromoTertiaryInvertedHeadingFontColor #ffffff
#define BrkPromoTertiaryInvertedBodyFontColor #ffffff
#define BrkPromoTertiaryInvertedBackgroundColor #ffffff
#define BrkPromoTertiaryInvertedBorderColor #e6e6e6
#define BrkPromoTertiaryInvertedGradientColor linear-gradient(180deg, #ffffff00 0%, #ffffff 100%)
#define BrkPromoTertiaryInvertedFrameColor #000000
#define BrkTemplateSmContentGapHorizontal 16
#define BrkTemplateSmContentGapVertical 24
#define BrkTemplateSmContentGapExtra 16
#define BrkTemplateSmMarginHorizontal 32
#define BrkTemplateSmMarginTop 0
#define BrkTemplateSmMarginBottom 48
#define BrkTemplateContentMaxWidth 1600
#define BrkHeaderMainStandardBackgroundColor #060606
#define BrkTextSmHeading1FontFamily Graphik
#define BrkTextSmHeading1FontWeight Super
#define BrkTextSmHeading1LineHeight 120%
#define BrkTextSmHeading1FontSize 32
#define BrkTextSmHeading1LetterSpacing -2%
#define BrkTextSmHeading1ParagraphSpacing 
#define BrkTextSmHeading1TextDecoration none
#define BrkTextSmHeading1TextCase none
#define BrkTextSmHeading2FontFamily Graphik
#define BrkTextSmHeading2FontWeight Super
#define BrkTextSmHeading2LineHeight 120%
#define BrkTextSmHeading2FontSize 28
#define BrkTextSmHeading2LetterSpacing -2%
#define BrkTextSmHeading2ParagraphSpacing 
#define BrkTextSmHeading2TextDecoration none
#define BrkTextSmHeading2TextCase none
#define BrkTextSmHeading3FontFamily Graphik
#define BrkTextSmHeading3FontWeight Super
#define BrkTextSmHeading3LineHeight 120%
#define BrkTextSmHeading3FontSize 26
#define BrkTextSmHeading3LetterSpacing -2%
#define BrkTextSmHeading3ParagraphSpacing 
#define BrkTextSmHeading3TextDecoration none
#define BrkTextSmHeading3TextCase none
#define BrkTextSmHeading4FontFamily Graphik
#define BrkTextSmHeading4FontWeight Super
#define BrkTextSmHeading4LineHeight 120%
#define BrkTextSmHeading4FontSize 22
#define BrkTextSmHeading4LetterSpacing -2%
#define BrkTextSmHeading4ParagraphSpacing 
#define BrkTextSmHeading4TextDecoration none
#define BrkTextSmHeading4TextCase none
#define BrkTextSmHeading5FontFamily Graphik
#define BrkTextSmHeading5FontWeight Super
#define BrkTextSmHeading5LineHeight 120%
#define BrkTextSmHeading5FontSize 20
#define BrkTextSmHeading5LetterSpacing -2%
#define BrkTextSmHeading5ParagraphSpacing 
#define BrkTextSmHeading5TextDecoration none
#define BrkTextSmHeading5TextCase none
#define BrkTextSmHeading6FontFamily Graphik
#define BrkTextSmHeading6FontWeight Super
#define BrkTextSmHeading6LineHeight 120%
#define BrkTextSmHeading6FontSize 18
#define BrkTextSmHeading6LetterSpacing -2%
#define BrkTextSmHeading6ParagraphSpacing 
#define BrkTextSmHeading6TextDecoration none
#define BrkTextSmHeading6TextCase none
#define BrkTextSmBody1FontFamily Arial
#define BrkTextSmBody1FontWeight Bold
#define BrkTextSmBody1LineHeight 160%
#define BrkTextSmBody1FontSize 18
#define BrkTextSmBody1LetterSpacing 0%
#define BrkTextSmBody1ParagraphSpacing 12%
#define BrkTextSmBody1TextDecoration none
#define BrkTextSmBody1TextCase none
#define BrkTextSmBody2FontFamily Arial
#define BrkTextSmBody2FontWeight Regular
#define BrkTextSmBody2LineHeight 160%
#define BrkTextSmBody2FontSize 16
#define BrkTextSmBody2LetterSpacing 0%
#define BrkTextSmBody2ParagraphSpacing 12%
#define BrkTextSmBody2TextDecoration none
#define BrkTextSmBody2TextCase none
#define BrkTextSmCaptionFontFamily Arial
#define BrkTextSmCaptionFontWeight Regular
#define BrkTextSmCaptionLineHeight 120%
#define BrkTextSmCaptionFontSize 12
#define BrkTextSmCaptionLetterSpacing 0%
#define BrkTextSmCaptionParagraphSpacing 
#define BrkTextSmCaptionTextDecoration none
#define BrkTextSmCaptionTextCase none
#define BrkTextMdHeading1FontFamily Graphik
#define BrkTextMdHeading1FontWeight Super
#define BrkTextMdHeading1LineHeight 120%
#define BrkTextMdHeading1FontSize 36
#define BrkTextMdHeading1LetterSpacing -2%
#define BrkTextMdHeading1ParagraphSpacing 
#define BrkTextMdHeading1TextDecoration none
#define BrkTextMdHeading1TextCase none
#define BrkTextMdHeading2FontFamily Graphik
#define BrkTextMdHeading2FontWeight Super
#define BrkTextMdHeading2LineHeight 120%
#define BrkTextMdHeading2FontSize 32
#define BrkTextMdHeading2LetterSpacing -2%
#define BrkTextMdHeading2ParagraphSpacing 
#define BrkTextMdHeading2TextDecoration none
#define BrkTextMdHeading2TextCase none
#define BrkTextMdHeading3FontFamily Graphik
#define BrkTextMdHeading3FontWeight Super
#define BrkTextMdHeading3LineHeight 120%
#define BrkTextMdHeading3FontSize 28
#define BrkTextMdHeading3LetterSpacing -2%
#define BrkTextMdHeading3ParagraphSpacing 
#define BrkTextMdHeading3TextDecoration none
#define BrkTextMdHeading3TextCase none
#define BrkTextMdHeading4FontFamily Graphik
#define BrkTextMdHeading4FontWeight Super
#define BrkTextMdHeading4LineHeight 120%
#define BrkTextMdHeading4FontSize 24
#define BrkTextMdHeading4LetterSpacing -2%
#define BrkTextMdHeading4ParagraphSpacing 
#define BrkTextMdHeading4TextDecoration none
#define BrkTextMdHeading4TextCase none
#define BrkTextMdHeading5FontFamily Graphik
#define BrkTextMdHeading5FontWeight Super
#define BrkTextMdHeading5LineHeight 120%
#define BrkTextMdHeading5FontSize 22
#define BrkTextMdHeading5LetterSpacing -2%
#define BrkTextMdHeading5ParagraphSpacing 
#define BrkTextMdHeading5TextDecoration none
#define BrkTextMdHeading5TextCase none
#define BrkTextMdHeading6FontFamily Graphik
#define BrkTextMdHeading6FontWeight Super
#define BrkTextMdHeading6LineHeight 120%
#define BrkTextMdHeading6FontSize 20
#define BrkTextMdHeading6LetterSpacing -2%
#define BrkTextMdHeading6ParagraphSpacing 
#define BrkTextMdHeading6TextDecoration none
#define BrkTextMdHeading6TextCase none
#define BrkTextMdBody1FontFamily Arial
#define BrkTextMdBody1FontWeight Bold
#define BrkTextMdBody1LineHeight 160%
#define BrkTextMdBody1FontSize 20
#define BrkTextMdBody1LetterSpacing 0%
#define BrkTextMdBody1ParagraphSpacing 12%
#define BrkTextMdBody1TextDecoration none
#define BrkTextMdBody1TextCase none
#define BrkTextMdBody2FontFamily Arial
#define BrkTextMdBody2FontWeight Regular
#define BrkTextMdBody2LineHeight 160%
#define BrkTextMdBody2FontSize 18
#define BrkTextMdBody2LetterSpacing 0%
#define BrkTextMdBody2ParagraphSpacing 12%
#define BrkTextMdBody2TextDecoration none
#define BrkTextMdBody2TextCase none
#define BrkTextMdCaptionFontFamily Arial
#define BrkTextMdCaptionFontWeight Regular
#define BrkTextMdCaptionLineHeight 120%
#define BrkTextMdCaptionFontSize 14
#define BrkTextMdCaptionLetterSpacing 0%
#define BrkTextMdCaptionParagraphSpacing 
#define BrkTextMdCaptionTextDecoration none
#define BrkTextMdCaptionTextCase none
#define BrkTextLgHeading1FontFamily Graphik
#define BrkTextLgHeading1FontWeight Super
#define BrkTextLgHeading1LineHeight 120%
#define BrkTextLgHeading1FontSize 42
#define BrkTextLgHeading1LetterSpacing -2%
#define BrkTextLgHeading1ParagraphSpacing 
#define BrkTextLgHeading1TextDecoration none
#define BrkTextLgHeading1TextCase none
#define BrkTextLgHeading2FontFamily Graphik
#define BrkTextLgHeading2FontWeight Super
#define BrkTextLgHeading2LineHeight 120%
#define BrkTextLgHeading2FontSize 36
#define BrkTextLgHeading2LetterSpacing -2%
#define BrkTextLgHeading2ParagraphSpacing 
#define BrkTextLgHeading2TextDecoration none
#define BrkTextLgHeading2TextCase none
#define BrkTextLgHeading3FontFamily Graphik
#define BrkTextLgHeading3FontWeight Super
#define BrkTextLgHeading3LineHeight 120%
#define BrkTextLgHeading3FontSize 32
#define BrkTextLgHeading3LetterSpacing -2%
#define BrkTextLgHeading3ParagraphSpacing 
#define BrkTextLgHeading3TextDecoration none
#define BrkTextLgHeading3TextCase none
#define BrkTextLgHeading4FontFamily Graphik
#define BrkTextLgHeading4FontWeight Super
#define BrkTextLgHeading4LineHeight 120%
#define BrkTextLgHeading4FontSize 28
#define BrkTextLgHeading4LetterSpacing -2%
#define BrkTextLgHeading4ParagraphSpacing 
#define BrkTextLgHeading4TextDecoration none
#define BrkTextLgHeading4TextCase none
#define BrkTextLgHeading5FontFamily Graphik
#define BrkTextLgHeading5FontWeight Super
#define BrkTextLgHeading5LineHeight 120%
#define BrkTextLgHeading5FontSize 26
#define BrkTextLgHeading5LetterSpacing -2%
#define BrkTextLgHeading5ParagraphSpacing 
#define BrkTextLgHeading5TextDecoration none
#define BrkTextLgHeading5TextCase none
#define BrkTextLgHeading6FontFamily Graphik
#define BrkTextLgHeading6FontWeight Super
#define BrkTextLgHeading6LineHeight 120%
#define BrkTextLgHeading6FontSize 22
#define BrkTextLgHeading6LetterSpacing -2%
#define BrkTextLgHeading6ParagraphSpacing 
#define BrkTextLgHeading6TextDecoration none
#define BrkTextLgHeading6TextCase none
#define BrkTextLgBody1FontFamily Arial
#define BrkTextLgBody1FontWeight Bold
#define BrkTextLgBody1LineHeight 160%
#define BrkTextLgBody1FontSize 22
#define BrkTextLgBody1LetterSpacing 0%
#define BrkTextLgBody1ParagraphSpacing 12%
#define BrkTextLgBody1TextDecoration none
#define BrkTextLgBody1TextCase none
#define BrkTextLgBody2FontFamily Arial
#define BrkTextLgBody2FontWeight Regular
#define BrkTextLgBody2LineHeight 160%
#define BrkTextLgBody2FontSize 20
#define BrkTextLgBody2LetterSpacing 0%
#define BrkTextLgBody2ParagraphSpacing 12%
#define BrkTextLgBody2TextDecoration none
#define BrkTextLgBody2TextCase none
#define BrkTextLgCaptionFontFamily Arial
#define BrkTextLgCaptionFontWeight Regular
#define BrkTextLgCaptionLineHeight 120%
#define BrkTextLgCaptionFontSize 16
#define BrkTextLgCaptionLetterSpacing 0%
#define BrkTextLgCaptionParagraphSpacing 
#define BrkTextLgCaptionTextDecoration none
#define BrkTextLgCaptionTextCase none
#define BrkTextXlHeading1FontFamily Graphik
#define BrkTextXlHeading1FontWeight Super
#define BrkTextXlHeading1LineHeight 120%
#define BrkTextXlHeading1FontSize 48
#define BrkTextXlHeading1LetterSpacing -2%
#define BrkTextXlHeading1ParagraphSpacing 
#define BrkTextXlHeading1TextDecoration none
#define BrkTextXlHeading1TextCase none
#define BrkTextXlHeading2FontFamily Graphik
#define BrkTextXlHeading2FontWeight Super
#define BrkTextXlHeading2LineHeight 120%
#define BrkTextXlHeading2FontSize 42
#define BrkTextXlHeading2LetterSpacing -2%
#define BrkTextXlHeading2ParagraphSpacing 
#define BrkTextXlHeading2TextDecoration none
#define BrkTextXlHeading2TextCase none
#define BrkTextXlHeading3FontFamily Graphik
#define BrkTextXlHeading3FontWeight Super
#define BrkTextXlHeading3LineHeight 120%
#define BrkTextXlHeading3FontSize 36
#define BrkTextXlHeading3LetterSpacing -2%
#define BrkTextXlHeading3ParagraphSpacing 
#define BrkTextXlHeading3TextDecoration none
#define BrkTextXlHeading3TextCase none
#define BrkTextXlHeading4FontFamily Graphik
#define BrkTextXlHeading4FontWeight Super
#define BrkTextXlHeading4LineHeight 120%
#define BrkTextXlHeading4FontSize 32
#define BrkTextXlHeading4LetterSpacing -2%
#define BrkTextXlHeading4ParagraphSpacing 
#define BrkTextXlHeading4TextDecoration none
#define BrkTextXlHeading4TextCase none
#define BrkTextXlHeading5FontFamily Graphik
#define BrkTextXlHeading5FontWeight Super
#define BrkTextXlHeading5LineHeight 120%
#define BrkTextXlHeading5FontSize 28
#define BrkTextXlHeading5LetterSpacing -2%
#define BrkTextXlHeading5ParagraphSpacing 
#define BrkTextXlHeading5TextDecoration none
#define BrkTextXlHeading5TextCase none
#define BrkTextXlHeading6FontFamily Graphik
#define BrkTextXlHeading6FontWeight Super
#define BrkTextXlHeading6LineHeight 120%
#define BrkTextXlHeading6FontSize 26
#define BrkTextXlHeading6LetterSpacing -2%
#define BrkTextXlHeading6ParagraphSpacing 
#define BrkTextXlHeading6TextDecoration none
#define BrkTextXlHeading6TextCase none
#define BrkTextXlBody1FontFamily Arial
#define BrkTextXlBody1FontWeight Bold
#define BrkTextXlBody1LineHeight 160%
#define BrkTextXlBody1FontSize 26
#define BrkTextXlBody1LetterSpacing 0%
#define BrkTextXlBody1ParagraphSpacing 12%
#define BrkTextXlBody1TextDecoration none
#define BrkTextXlBody1TextCase none
#define BrkTextXlBody2FontFamily Arial
#define BrkTextXlBody2FontWeight Regular
#define BrkTextXlBody2LineHeight 160%
#define BrkTextXlBody2FontSize 22
#define BrkTextXlBody2LetterSpacing 0%
#define BrkTextXlBody2ParagraphSpacing 12%
#define BrkTextXlBody2TextDecoration none
#define BrkTextXlBody2TextCase none
#define BrkTextXlCaptionFontFamily Arial
#define BrkTextXlCaptionFontWeight Regular
#define BrkTextXlCaptionLineHeight 120%
#define BrkTextXlCaptionFontSize 18
#define BrkTextXlCaptionLetterSpacing 0%
#define BrkTextXlCaptionParagraphSpacing 
#define BrkTextXlCaptionTextDecoration none
#define BrkTextXlCaptionTextCase none
#define BrkTextStandardHeading1FontColor #090f2a
#define BrkTextStandardHeading2FontColor #192872
#define BrkTextStandardHeading3FontColor #192872
#define BrkTextStandardHeading4FontColor #192872
#define BrkTextStandardHeading5FontColor #253aa7
#define BrkTextStandardHeading6FontColor #253aa7
#define BrkTextStandardBody1FontColor #121d54
#define BrkTextStandardBody2FontColor #090f2a
#define BrkTextStandardCaptionFontColor #090f2a
#define BrkTextInvertedHeading1FontColor #d5dbf6
#define BrkTextInvertedHeading2FontColor #abb6ed
#define BrkTextInvertedHeading3FontColor #abb6ed
#define BrkTextInvertedHeading4FontColor #abb6ed
#define BrkTextInvertedHeading5FontColor #2e49d1
#define BrkTextInvertedHeading6FontColor #2e49d1
#define BrkTextInvertedBody1FontColor #d5dbf6
#define BrkTextInvertedBody2FontColor #ffffff
#define BrkTextInvertedCaptionFontColor #ffffff
#define BrkHeaderMainSmHeight 138
#define BrkHeaderMainSmPaddingVertical 24
#define BrkHeaderMainMdHeight 172
#define BrkHeaderMainMdPaddingVertical 32

