
//
// tokens.h
//

// Do not edit directly
// Generated on Tue, 18 Oct 2022 13:56:55 GMT


#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

#define BrkButtonPrimaryBorderWidth 2
#define BrkButtonSecondaryBorderWidth 2
#define BrkButtonTertiaryBorderWidth 1
#define BrkButtonOpacityDisabled 50%
#define BrkButtonTertiaryStandardBoxShadowDefault [object Object]
#define BrkButtonTertiaryStandardBoxShadowHover [object Object]
#define BrkButtonTertiaryStandardBoxShadowFocus [object Object]
#define BrkButtonTertiaryStandardFontColorDefault #535353
#define BrkButtonTertiaryStandardIconFillDefault #535353
#define BrkButtonTertiaryStandardBackgroundColorDefault #ffffff
#define BrkButtonTertiaryStandardBorderColorDefault #e6e6e6
#define BrkButtonTertiaryStandardFontColorHover #1a1a1a
#define BrkButtonTertiaryStandardIconFillHover #1a1a1a
#define BrkButtonTertiaryStandardBackgroundColorHover #ffffff
#define BrkButtonTertiaryStandardBorderColorHover #535353
#define BrkButtonTertiaryStandardFontColorFocus #1a1a1a
#define BrkButtonTertiaryStandardIconFillFocus #1a1a1a
#define BrkButtonTertiaryStandardBackgroundColorFocus #ffffff
#define BrkButtonTertiaryStandardBorderColorFocus #535353
#define BrkButtonTertiaryInvertedBoxShadowDefault [object Object]
#define BrkButtonTertiaryInvertedBoxShadowHover [object Object]
#define BrkButtonTertiaryInvertedBoxShadowFocus [object Object]
#define BrkButtonTertiaryInvertedFontColorDefault #e6e6e6
#define BrkButtonTertiaryInvertedIconFillDefault #e6e6e6
#define BrkButtonTertiaryInvertedBackgroundColorDefault #1a1a1a
#define BrkButtonTertiaryInvertedBorderColorDefault #535353
#define BrkButtonTertiaryInvertedFontColorHover #ffffff
#define BrkButtonTertiaryInvertedIconFillHover #ffffff
#define BrkButtonTertiaryInvertedBackgroundColorHover #1a1a1a
#define BrkButtonTertiaryInvertedBorderColorHover #f2f2f2
#define BrkButtonTertiaryInvertedFontColorFocus #ffffff
#define BrkButtonTertiaryInvertedIconFillFocus #ffffff
#define BrkButtonTertiaryInvertedBackgroundColorFocus #1a1a1a
#define BrkButtonTertiaryInvertedBorderColorFocus #ffffff
#define BrkButtonPrimaryStandardSmBoxShadowDefault [object Object]
#define BrkButtonPrimaryStandardSmBoxShadowHover [object Object]
#define BrkButtonPrimaryStandardSmBoxShadowFocus [object Object]
#define BrkButtonPrimaryStandardFontColorDefault #000000
#define BrkButtonPrimaryStandardBackgroundColorDefault #fdfe8b
#define BrkButtonPrimaryStandardBorderColorDefault #000000
#define BrkButtonPrimaryStandardFontColorHover #1a1a1a
#define BrkButtonPrimaryStandardBackgroundColorHover #24c1ff
#define BrkButtonPrimaryStandardBorderColorHover #0b5db7
#define BrkButtonPrimaryStandardFontColorFocus #1a1a1a
#define BrkButtonPrimaryStandardBackgroundColorFocus #ffffff
#define BrkButtonPrimaryStandardBorderColorFocus #535353
#define BrkButtonPrimaryStandardMdBoxShadowDefault [object Object]
#define BrkButtonPrimaryStandardMdBoxShadowHover [object Object]
#define BrkButtonPrimaryStandardMdBoxShadowFocus [object Object]
#define BrkButtonPrimaryInvertedSmBoxShadowDefault [object Object]
#define BrkButtonPrimaryInvertedSmBoxShadowHover [object Object]
#define BrkButtonPrimaryInvertedSmBoxShadowFocus [object Object]
#define BrkButtonPrimaryInvertedFontColorDefault #000000
#define BrkButtonPrimaryInvertedBackgroundColorDefault #fdfe8b
#define BrkButtonPrimaryInvertedBorderColorDefault #ffffff
#define BrkButtonPrimaryInvertedFontColorHover #ffffff
#define BrkButtonPrimaryInvertedBackgroundColorHover #a6ecff
#define BrkButtonPrimaryInvertedBorderColorHover #eaedfa
#define BrkButtonPrimaryInvertedFontColorFocus #ffffff
#define BrkButtonPrimaryInvertedBackgroundColorFocus #1a1a1a
#define BrkButtonPrimaryInvertedBorderColorFocus #ffffff
#define BrkButtonPrimaryInvertedMdBoxShadowDefault [object Object]
#define BrkButtonPrimaryInvertedMdBoxShadowHover [object Object]
#define BrkButtonPrimaryInvertedMdBoxShadowFocus [object Object]
#define BrkButtonSecondaryStandardSmBoxShadowDefault [object Object]
#define BrkButtonSecondaryStandardSmBoxShadowHover [object Object]
#define BrkButtonSecondaryStandardSmBoxShadowFocus [object Object]
#define BrkButtonSecondaryStandardFontColorDefault #000000
#define BrkButtonSecondaryStandardBackgroundColorDefault #ffffff
#define BrkButtonSecondaryStandardBorderColorDefault #000000
#define BrkButtonSecondaryStandardFontColorHover #000000
#define BrkButtonSecondaryStandardBackgroundColorHover #ffffff
#define BrkButtonSecondaryStandardBorderColorHover #000000
#define BrkButtonSecondaryStandardFontColorFocus #000000
#define BrkButtonSecondaryStandardBackgroundColorFocus #ffffff
#define BrkButtonSecondaryStandardBorderColorFocus #000000
#define BrkButtonSecondaryStandardMdBoxShadowDefault [object Object]
#define BrkButtonSecondaryStandardMdBoxShadowHover [object Object]
#define BrkButtonSecondaryStandardMdBoxShadowFocus [object Object]
#define BrkButtonSecondaryInvertedSmBoxShadowDefault [object Object]
#define BrkButtonSecondaryInvertedSmBoxShadowHover [object Object]
#define BrkButtonSecondaryInvertedSmBoxShadowFocus [object Object]
#define BrkButtonSecondaryInvertedFontColorDefault #ffffff
#define BrkButtonSecondaryInvertedBackgroundColorDefault #000000
#define BrkButtonSecondaryInvertedBorderColorDefault #ffffff
#define BrkButtonSecondaryInvertedFontColorHover #ffffff
#define BrkButtonSecondaryInvertedBackgroundColorHover #0b5db7
#define BrkButtonSecondaryInvertedBorderColorHover #ffffff
#define BrkButtonSecondaryInvertedFontColorFocus #ffffff
#define BrkButtonSecondaryInvertedBackgroundColorFocus #1a1a1a
#define BrkButtonSecondaryInvertedBorderColorFocus #ffffff
#define BrkButtonSecondaryInvertedMdBoxShadowDefault [object Object]
#define BrkButtonSecondaryInvertedMdBoxShadowHover [object Object]
#define BrkButtonSecondaryInvertedMdBoxShadowFocus [object Object]
#define BrkButtonTertiarySmLabelFontFamily Graphik
#define BrkButtonTertiarySmLabelFontWeight Bold
#define BrkButtonTertiarySmLabelLineHeight 100%
#define BrkButtonTertiarySmLabelFontSize 10
#define BrkButtonTertiarySmLabelLetterSpacing 0%
#define BrkButtonTertiarySmLabelParagraphSpacing 
#define BrkButtonTertiarySmLabelTextDecoration none
#define BrkButtonTertiarySmLabelTextCase uppercase
#define BrkButtonTertiaryMdLabelFontFamily Graphik
#define BrkButtonTertiaryMdLabelFontWeight Bold
#define BrkButtonTertiaryMdLabelLineHeight 100%
#define BrkButtonTertiaryMdLabelFontSize 14
#define BrkButtonTertiaryMdLabelLetterSpacing 0%
#define BrkButtonTertiaryMdLabelParagraphSpacing 
#define BrkButtonTertiaryMdLabelTextDecoration none
#define BrkButtonTertiaryMdLabelTextCase uppercase
#define BrkButtonTertiaryLgLabelFontFamily Graphik
#define BrkButtonTertiaryLgLabelFontWeight Bold
#define BrkButtonTertiaryLgLabelLineHeight 100%
#define BrkButtonTertiaryLgLabelFontSize 18
#define BrkButtonTertiaryLgLabelLetterSpacing 0%
#define BrkButtonTertiaryLgLabelParagraphSpacing 
#define BrkButtonTertiaryLgLabelTextDecoration none
#define BrkButtonTertiaryLgLabelTextCase uppercase
#define BrkButtonTertiaryXlLabelFontFamily Graphik
#define BrkButtonTertiaryXlLabelFontWeight Bold
#define BrkButtonTertiaryXlLabelLineHeight 100%
#define BrkButtonTertiaryXlLabelFontSize 22
#define BrkButtonTertiaryXlLabelLetterSpacing 0%
#define BrkButtonTertiaryXlLabelParagraphSpacing 
#define BrkButtonTertiaryXlLabelTextDecoration none
#define BrkButtonTertiaryXlLabelTextCase uppercase
#define BrkButtonTertiarySmPaddingHorizontal 15
#define BrkButtonTertiarySmHeight 30
#define BrkButtonTertiarySmBorderRadius 15
#define BrkButtonTertiarySmIconSize 8
#define BrkButtonTertiarySmIconGap 2
#define BrkButtonTertiaryMdPaddingHorizontal 20
#define BrkButtonTertiaryMdHeight 40
#define BrkButtonTertiaryMdBorderRadius 20
#define BrkButtonTertiaryMdIconSize 10
#define BrkButtonTertiaryMdIconGap 4
#define BrkButtonTertiaryLgPaddingHorizontal 25
#define BrkButtonTertiaryLgHeight 50
#define BrkButtonTertiaryLgBorderRadius 25
#define BrkButtonTertiaryLgIconSize 12
#define BrkButtonTertiaryLgIconGap 6
#define BrkButtonTertiaryXlPaddingHorizontal 30
#define BrkButtonTertiaryXlHeight 60
#define BrkButtonTertiaryXlBorderRadius 30
#define BrkButtonTertiaryXlIconSize 14
#define BrkButtonTertiaryXlIconGap 8
#define BrkInteractiveStandardOutlineColorFocus #0b5db7
#define BrkInteractiveInvertedOutlineColorFocus #24c1ff
#define BrkInteractiveOutlineWidth 2
#define BrkInteractiveOutlineOffset 2
#define BrkInteractiveOutlineBorderRadius 24
#define BrkCardHeroBorderRadius 16
#define BrkCardHeroBorderWidth 1
#define BrkCardHeroSmPaddingHorizontal 10
#define BrkCardHeroSmPaddingVertical 10
#define BrkCardHeroSmHeadingMarginVertical 4
#define BrkCardHeroSmContentGap 16
#define BrkCardHeroSmPretitleFontFamily Graphik
#define BrkCardHeroSmPretitleFontWeight Bold
#define BrkCardHeroSmPretitleLineHeight 9
#define BrkCardHeroSmPretitleFontSize 9
#define BrkCardHeroSmPretitleLetterSpacing -2%
#define BrkCardHeroSmPretitleParagraphSpacing 
#define BrkCardHeroSmPretitleTextDecoration none
#define BrkCardHeroSmPretitleTextCase uppercase
#define BrkCardHeroSmHeadingFontFamily Graphik
#define BrkCardHeroSmHeadingFontWeight Bold
#define BrkCardHeroSmHeadingLineHeight 12
#define BrkCardHeroSmHeadingFontSize 12
#define BrkCardHeroSmHeadingLetterSpacing -2%
#define BrkCardHeroSmHeadingParagraphSpacing 
#define BrkCardHeroSmHeadingTextCase none
#define BrkCardHeroSmHeadingTextDecoration none
#define BrkCardHeroSmBodyFontFamily Arial
#define BrkCardHeroSmBodyFontWeight Regular
#define BrkCardHeroSmBodyLineHeight 100%
#define BrkCardHeroSmBodyFontSize 10
#define BrkCardHeroSmBodyLetterSpacing 0%
#define BrkCardHeroSmBodyParagraphSpacing 
#define BrkCardHeroSmBodyTextDecoration none
#define BrkCardHeroSmBodyTextCase none
#define BrkCardHeroSmImageHeight 180
#define BrkCardHeroMdPaddingHorizontal 16
#define BrkCardHeroMdPaddingVertical 16
#define BrkCardHeroMdHeadingMarginVertical 4
#define BrkCardHeroMdContentGap 24
#define BrkCardHeroMdPretitleFontFamily Graphik
#define BrkCardHeroMdPretitleFontWeight Bold
#define BrkCardHeroMdPretitleLineHeight 13
#define BrkCardHeroMdPretitleFontSize 13
#define BrkCardHeroMdPretitleLetterSpacing -2%
#define BrkCardHeroMdPretitleParagraphSpacing 
#define BrkCardHeroMdPretitleTextDecoration none
#define BrkCardHeroMdPretitleTextCase uppercase
#define BrkCardHeroMdHeadingFontFamily Graphik
#define BrkCardHeroMdHeadingFontWeight Bold
#define BrkCardHeroMdHeadingLineHeight 110%
#define BrkCardHeroMdHeadingFontSize 22
#define BrkCardHeroMdHeadingLetterSpacing -2%
#define BrkCardHeroMdHeadingParagraphSpacing 
#define BrkCardHeroMdHeadingTextCase none
#define BrkCardHeroMdHeadingTextDecoration none
#define BrkCardHeroMdBodyFontFamily Arial
#define BrkCardHeroMdBodyFontWeight Regular
#define BrkCardHeroMdBodyLineHeight 100%
#define BrkCardHeroMdBodyFontSize 13
#define BrkCardHeroMdBodyLetterSpacing 0%
#define BrkCardHeroMdBodyParagraphSpacing 
#define BrkCardHeroMdBodyTextDecoration none
#define BrkCardHeroMdBodyTextCase none
#define BrkCardHeroMdImageHeight 270
#define BrkCardHeroLgPaddingHorizontal 24
#define BrkCardHeroLgPaddingVertical 24
#define BrkCardHeroLgHeadingMarginVertical 8
#define BrkCardHeroLgContentGap 24
#define BrkCardHeroLgPretitleFontFamily Graphik
#define BrkCardHeroLgPretitleFontWeight Bold
#define BrkCardHeroLgPretitleLineHeight 16
#define BrkCardHeroLgPretitleFontSize 16
#define BrkCardHeroLgPretitleLetterSpacing -2%
#define BrkCardHeroLgPretitleParagraphSpacing 
#define BrkCardHeroLgPretitleTextDecoration none
#define BrkCardHeroLgPretitleTextCase uppercase
#define BrkCardHeroLgHeadingFontFamily Graphik
#define BrkCardHeroLgHeadingFontWeight Bold
#define BrkCardHeroLgHeadingLineHeight 110%
#define BrkCardHeroLgHeadingFontSize 24
#define BrkCardHeroLgHeadingLetterSpacing -2%
#define BrkCardHeroLgHeadingParagraphSpacing 
#define BrkCardHeroLgHeadingTextCase none
#define BrkCardHeroLgHeadingTextDecoration none
#define BrkCardHeroLgBodyFontFamily Arial
#define BrkCardHeroLgBodyFontWeight Regular
#define BrkCardHeroLgBodyLineHeight 100%
#define BrkCardHeroLgBodyFontSize 16
#define BrkCardHeroLgBodyLetterSpacing 0%
#define BrkCardHeroLgBodyParagraphSpacing 
#define BrkCardHeroLgBodyTextDecoration none
#define BrkCardHeroLgBodyTextCase none
#define BrkCardHeroLgImageHeight 270
#define BrkCardHeroXlPaddingHorizontal 24
#define BrkCardHeroXlPaddingVertical 24
#define BrkCardHeroXlHeadingMarginVertical 8
#define BrkCardHeroXlContentGap 16
#define BrkCardHeroXlPretitleFontFamily Graphik
#define BrkCardHeroXlPretitleFontWeight Bold
#define BrkCardHeroXlPretitleLineHeight 20
#define BrkCardHeroXlPretitleFontSize 20
#define BrkCardHeroXlPretitleLetterSpacing -2%
#define BrkCardHeroXlPretitleParagraphSpacing 
#define BrkCardHeroXlPretitleTextDecoration none
#define BrkCardHeroXlPretitleTextCase uppercase
#define BrkCardHeroXlHeadingFontFamily Graphik
#define BrkCardHeroXlHeadingFontWeight Bold
#define BrkCardHeroXlHeadingLineHeight 110%
#define BrkCardHeroXlHeadingFontSize 32
#define BrkCardHeroXlHeadingLetterSpacing -2%
#define BrkCardHeroXlHeadingParagraphSpacing 
#define BrkCardHeroXlHeadingTextCase none
#define BrkCardHeroXlHeadingTextDecoration none
#define BrkCardHeroXlBodyFontFamily Arial
#define BrkCardHeroXlBodyFontWeight Regular
#define BrkCardHeroXlBodyLineHeight 110%
#define BrkCardHeroXlBodyFontSize 20
#define BrkCardHeroXlBodyLetterSpacing 0%
#define BrkCardHeroXlBodyParagraphSpacing 
#define BrkCardHeroXlBodyTextDecoration none
#define BrkCardHeroXlBodyTextCase none
#define BrkCardHeroXlImageHeight 360
#define BrkPromoSecondaryBorderRadius 16
#define BrkPromoTertiaryFrameBorderRadius 16
#define BrkPromoPrimaryBorderWidth 1
#define BrkPromoSecondaryBorderWidth 1
#define BrkPromoTertiaryBorderWidth 1
#define BrkPromoSecondarySmImageHeight 172
#define BrkPromoSecondarySmGradientHeight 43
#define BrkPromoSecondarySmPretitleFontFamily Arial
#define BrkPromoSecondarySmPretitleFontWeight Bold
#define BrkPromoSecondarySmPretitleLineHeight 110%
#define BrkPromoSecondarySmPretitleFontSize 8
#define BrkPromoSecondarySmPretitleLetterSpacing 0%
#define BrkPromoSecondarySmPretitleParagraphSpacing 
#define BrkPromoSecondarySmPretitleTextDecoration none
#define BrkPromoSecondarySmPretitleTextCase none
#define BrkPromoSecondarySmHeadingFontFamily Graphik
#define BrkPromoSecondarySmHeadingFontWeight Super
#define BrkPromoSecondarySmHeadingLineHeight 110%
#define BrkPromoSecondarySmHeadingFontSize 15
#define BrkPromoSecondarySmHeadingLetterSpacing -2%
#define BrkPromoSecondarySmHeadingParagraphSpacing 
#define BrkPromoSecondarySmHeadingTextCase none
#define BrkPromoSecondarySmHeadingTextDecoration none
#define BrkPromoSecondarySmPaddingHorizontal 16
#define BrkPromoSecondarySmPaddingVertical 15
#define BrkPromoSecondarySmContentGap 8
#define BrkPromoSecondarySmPretitleMarginBottom 4
#define BrkPromoSecondaryMdImageHeight 270
#define BrkPromoSecondaryMdGradientHeight 67.5
#define BrkPromoSecondaryMdPretitleFontFamily Arial
#define BrkPromoSecondaryMdPretitleFontWeight Bold
#define BrkPromoSecondaryMdPretitleLineHeight 110%
#define BrkPromoSecondaryMdPretitleFontSize 12
#define BrkPromoSecondaryMdPretitleLetterSpacing 0%
#define BrkPromoSecondaryMdPretitleParagraphSpacing 
#define BrkPromoSecondaryMdPretitleTextDecoration none
#define BrkPromoSecondaryMdPretitleTextCase none
#define BrkPromoSecondaryMdHeadingFontFamily Graphik
#define BrkPromoSecondaryMdHeadingFontWeight Super
#define BrkPromoSecondaryMdHeadingLineHeight 110%
#define BrkPromoSecondaryMdHeadingFontSize 28
#define BrkPromoSecondaryMdHeadingLetterSpacing -2%
#define BrkPromoSecondaryMdHeadingParagraphSpacing 
#define BrkPromoSecondaryMdHeadingTextCase none
#define BrkPromoSecondaryMdHeadingTextDecoration none
#define BrkPromoSecondaryMdPaddingHorizontal 20
#define BrkPromoSecondaryMdPaddingVertical 20
#define BrkPromoSecondaryMdContentGap 10
#define BrkPromoSecondaryMdPretitleMarginBottom 4
#define BrkPromoSecondaryLgImageHeight 300
#define BrkPromoSecondaryLgGradientHeight 75
#define BrkPromoSecondaryLgPretitleFontFamily Arial
#define BrkPromoSecondaryLgPretitleFontWeight Bold
#define BrkPromoSecondaryLgPretitleLineHeight 110%
#define BrkPromoSecondaryLgPretitleFontSize 13
#define BrkPromoSecondaryLgPretitleLetterSpacing 0%
#define BrkPromoSecondaryLgPretitleParagraphSpacing 
#define BrkPromoSecondaryLgPretitleTextDecoration none
#define BrkPromoSecondaryLgPretitleTextCase none
#define BrkPromoSecondaryLgHeadingFontFamily Graphik
#define BrkPromoSecondaryLgHeadingFontWeight Super
#define BrkPromoSecondaryLgHeadingLineHeight 110%
#define BrkPromoSecondaryLgHeadingFontSize 32
#define BrkPromoSecondaryLgHeadingLetterSpacing -2%
#define BrkPromoSecondaryLgHeadingParagraphSpacing 
#define BrkPromoSecondaryLgHeadingTextCase none
#define BrkPromoSecondaryLgHeadingTextDecoration none
#define BrkPromoSecondaryLgPaddingHorizontal 24
#define BrkPromoSecondaryLgPaddingVertical 20
#define BrkPromoSecondaryLgContentGap 12
#define BrkPromoSecondaryLgPretitleMarginBottom 4
#define BrkPromoSecondaryXlImageHeight 568
#define BrkPromoSecondaryXlGradientHeight 142
#define BrkPromoSecondaryXlContentWidth 390
#define BrkPromoSecondaryXlPaddingHorizontal 32
#define BrkPromoSecondaryXlPaddingVertical 32
#define BrkPromoSecondaryXlContentGap 32
#define BrkPromoSecondaryXlPretitleMarginBottom 12
#define BrkPromoSecondaryXlPretitleFontFamily Arial
#define BrkPromoSecondaryXlPretitleFontWeight Bold
#define BrkPromoSecondaryXlPretitleLineHeight 110%
#define BrkPromoSecondaryXlPretitleFontSize 16
#define BrkPromoSecondaryXlPretitleLetterSpacing 0%
#define BrkPromoSecondaryXlPretitleParagraphSpacing 
#define BrkPromoSecondaryXlPretitleTextDecoration none
#define BrkPromoSecondaryXlPretitleTextCase none
#define BrkPromoSecondaryXlHeadingFontFamily Graphik
#define BrkPromoSecondaryXlHeadingFontWeight Super
#define BrkPromoSecondaryXlHeadingLineHeight 110%
#define BrkPromoSecondaryXlHeadingFontSize 42
#define BrkPromoSecondaryXlHeadingLetterSpacing -2%
#define BrkPromoSecondaryXlHeadingParagraphSpacing 
#define BrkPromoSecondaryXlHeadingTextCase none
#define BrkPromoSecondaryXlHeadingTextDecoration none
#define BrkPromoPrimarySmImageHeight 245
#define BrkPromoPrimarySmGradientHeight 61.25
#define BrkPromoPrimarySmPaddingHorizontal 16
#define BrkPromoPrimarySmPaddingVertical 16
#define BrkPromoPrimarySmContentGap 16
#define BrkPromoPrimarySmPretitleFontFamily Arial
#define BrkPromoPrimarySmPretitleFontWeight Bold
#define BrkPromoPrimarySmPretitleLineHeight 110%
#define BrkPromoPrimarySmPretitleFontSize 13
#define BrkPromoPrimarySmPretitleLetterSpacing 0%
#define BrkPromoPrimarySmPretitleParagraphSpacing 
#define BrkPromoPrimarySmPretitleTextDecoration none
#define BrkPromoPrimarySmPretitleTextCase none
#define BrkPromoPrimarySmPretitleMarginBottom 6
#define BrkPromoPrimarySmBodyMarginTop 8
#define BrkPromoPrimarySmHeadingFontFamily Graphik
#define BrkPromoPrimarySmHeadingFontWeight Super
#define BrkPromoPrimarySmHeadingLineHeight 110%
#define BrkPromoPrimarySmHeadingFontSize 28
#define BrkPromoPrimarySmHeadingLetterSpacing -2%
#define BrkPromoPrimarySmHeadingParagraphSpacing 
#define BrkPromoPrimarySmHeadingTextCase none
#define BrkPromoPrimarySmHeadingTextDecoration none
#define BrkPromoPrimarySmBodyFontFamily Arial
#define BrkPromoPrimarySmBodyFontWeight Regular
#define BrkPromoPrimarySmBodyLineHeight 120%
#define BrkPromoPrimarySmBodyFontSize 16
#define BrkPromoPrimarySmBodyLetterSpacing -2%
#define BrkPromoPrimarySmBodyParagraphSpacing 
#define BrkPromoPrimarySmBodyTextDecoration none
#define BrkPromoPrimarySmBodyTextCase none
#define BrkPromoPrimaryMdPaddingHorizontal 20
#define BrkPromoPrimaryMdPaddingVertical 20
#define BrkPromoPrimaryMdContentGap 16
#define BrkPromoPrimaryMdPretitleMarginBottom 6
#define BrkPromoPrimaryMdBodyMarginTop 12
#define BrkPromoPrimaryMdImageHeight 270
#define BrkPromoPrimaryMdGradientHeight 67.5
#define BrkPromoPrimaryMdPretitleFontFamily Arial
#define BrkPromoPrimaryMdPretitleFontWeight Bold
#define BrkPromoPrimaryMdPretitleLineHeight 110%
#define BrkPromoPrimaryMdPretitleFontSize 14
#define BrkPromoPrimaryMdPretitleLetterSpacing 0%
#define BrkPromoPrimaryMdPretitleParagraphSpacing 
#define BrkPromoPrimaryMdPretitleTextDecoration none
#define BrkPromoPrimaryMdPretitleTextCase none
#define BrkPromoPrimaryMdHeadingFontFamily Graphik
#define BrkPromoPrimaryMdHeadingFontWeight Super
#define BrkPromoPrimaryMdHeadingLineHeight 110%
#define BrkPromoPrimaryMdHeadingFontSize 28
#define BrkPromoPrimaryMdHeadingLetterSpacing -2%
#define BrkPromoPrimaryMdHeadingParagraphSpacing 
#define BrkPromoPrimaryMdHeadingTextCase none
#define BrkPromoPrimaryMdHeadingTextDecoration none
#define BrkPromoPrimaryMdBodyFontFamily Arial
#define BrkPromoPrimaryMdBodyFontWeight Regular
#define BrkPromoPrimaryMdBodyLineHeight 120%
#define BrkPromoPrimaryMdBodyFontSize 18
#define BrkPromoPrimaryMdBodyLetterSpacing -2%
#define BrkPromoPrimaryMdBodyParagraphSpacing 
#define BrkPromoPrimaryMdBodyTextDecoration none
#define BrkPromoPrimaryMdBodyTextCase none
#define BrkPromoPrimaryLgImageHeight 300
#define BrkPromoPrimaryLgGradientHeight 75
#define BrkPromoPrimaryLgPretitleFontFamily Arial
#define BrkPromoPrimaryLgPretitleFontWeight Bold
#define BrkPromoPrimaryLgPretitleLineHeight 110%
#define BrkPromoPrimaryLgPretitleFontSize 16
#define BrkPromoPrimaryLgPretitleLetterSpacing 0%
#define BrkPromoPrimaryLgPretitleParagraphSpacing 
#define BrkPromoPrimaryLgPretitleTextDecoration none
#define BrkPromoPrimaryLgPretitleTextCase none
#define BrkPromoPrimaryLgHeadingFontFamily Graphik
#define BrkPromoPrimaryLgHeadingFontWeight Super
#define BrkPromoPrimaryLgHeadingLineHeight 110%
#define BrkPromoPrimaryLgHeadingFontSize 32
#define BrkPromoPrimaryLgHeadingLetterSpacing -2%
#define BrkPromoPrimaryLgHeadingParagraphSpacing 
#define BrkPromoPrimaryLgHeadingTextCase none
#define BrkPromoPrimaryLgHeadingTextDecoration none
#define BrkPromoPrimaryLgBodyFontFamily Arial
#define BrkPromoPrimaryLgBodyFontWeight Regular
#define BrkPromoPrimaryLgBodyLineHeight 120%
#define BrkPromoPrimaryLgBodyFontSize 20
#define BrkPromoPrimaryLgBodyLetterSpacing -2%
#define BrkPromoPrimaryLgBodyParagraphSpacing 
#define BrkPromoPrimaryLgBodyTextDecoration none
#define BrkPromoPrimaryLgBodyTextCase none
#define BrkPromoPrimaryLgPaddingHorizontal 24
#define BrkPromoPrimaryLgPaddingVertical 24
#define BrkPromoPrimaryLgContentGap 16
#define BrkPromoPrimaryLgPretitleMarginBottom 6
#define BrkPromoPrimaryLgBodyMarginTop 10
#define BrkPromoPrimaryXlImageHeight 568
#define BrkPromoPrimaryXlGradientHeight 142
#define BrkPromoPrimaryXlContentWidth 312
#define BrkPromoPrimaryXlContentWidthPercentTest 40%
#define BrkPromoPrimaryXlContentMaxWidth 470
#define BrkPromoPrimaryXlPretitleFontFamily Arial
#define BrkPromoPrimaryXlPretitleFontWeight Bold
#define BrkPromoPrimaryXlPretitleLineHeight 110%
#define BrkPromoPrimaryXlPretitleFontSize 16
#define BrkPromoPrimaryXlPretitleLetterSpacing 0%
#define BrkPromoPrimaryXlPretitleParagraphSpacing 
#define BrkPromoPrimaryXlPretitleTextDecoration none
#define BrkPromoPrimaryXlPretitleTextCase none
#define BrkPromoPrimaryXlHeadingFontFamily Graphik
#define BrkPromoPrimaryXlHeadingFontWeight Super
#define BrkPromoPrimaryXlHeadingLineHeight 110%
#define BrkPromoPrimaryXlHeadingFontSize 42
#define BrkPromoPrimaryXlHeadingLetterSpacing -2%
#define BrkPromoPrimaryXlHeadingParagraphSpacing 
#define BrkPromoPrimaryXlHeadingTextCase none
#define BrkPromoPrimaryXlHeadingTextDecoration none
#define BrkPromoPrimaryXlBodyFontFamily Arial
#define BrkPromoPrimaryXlBodyFontWeight Regular
#define BrkPromoPrimaryXlBodyLineHeight 120%
#define BrkPromoPrimaryXlBodyFontSize 20
#define BrkPromoPrimaryXlBodyLetterSpacing -2%
#define BrkPromoPrimaryXlBodyParagraphSpacing 
#define BrkPromoPrimaryXlBodyTextDecoration none
#define BrkPromoPrimaryXlBodyTextCase none
#define BrkPromoPrimaryXlPaddingHorizontal 32
#define BrkPromoPrimaryXlPaddingVertical 32
#define BrkPromoPrimaryXlContentGap 16
#define BrkPromoPrimaryXlPretitleMarginBottom 6
#define BrkPromoPrimaryXlBodyMarginTop 16
#define BrkTemplateSmSubheadingFontFamily Graphik
#define BrkTemplateSmSubheadingFontWeight Super
#define BrkTemplateSmSubheadingLineHeight 110%
#define BrkTemplateSmSubheadingFontSize 20
#define BrkTemplateSmSubheadingLetterSpacing -2%
#define BrkTemplateSmSubheadingParagraphSpacing 
#define BrkTemplateSmSubheadingTextCase none
#define BrkTemplateSmSubheadingTextDecoration none
#define BrkTemplateSmContentGapHorizontal 16
#define BrkTemplateSmContentGapVertical 24
#define BrkTemplateSmContentGapExtra 16
#define BrkTemplateSmMarginHorizontal 32
#define BrkTemplateSmMarginTop 0
#define BrkTemplateSmMarginBottom 48
#define BrkCardHeroStandardBoxShadowDefault [object Object]
#define BrkCardHeroStandardBoxShadowHover [object Object]
#define BrkCardHeroStandardPretitleFontColor #535353
#define BrkCardHeroStandardHeadingFontColor #060606
#define BrkCardHeroStandardBodyFontColor #1a1a1a
#define BrkCardHeroStandardBackgroundColor #ffffff
#define BrkCardHeroStandardBorderColor #e6e6e6
#define BrkJackpotHeroSmPaddingHorizontal 10
#define BrkJackpotHeroSmAmountDigitMargin 1
#define BrkJackpotHeroSmAmountGroupMargin 4
#define BrkJackpotHeroSmContentGap 16
#define BrkJackpotHeroSmHeadingFontFamily Graphik
#define BrkJackpotHeroSmHeadingFontWeight Bold
#define BrkJackpotHeroSmHeadingLineHeight 110%
#define BrkJackpotHeroSmHeadingFontSize 10
#define BrkJackpotHeroSmHeadingLetterSpacing -2%
#define BrkJackpotHeroSmHeadingParagraphSpacing 
#define BrkJackpotHeroSmHeadingTextCase none
#define BrkJackpotHeroSmHeadingTextDecoration none
#define BrkJackpotHeroSmBodyFontFamily Arial
#define BrkJackpotHeroSmBodyFontWeight Bold
#define BrkJackpotHeroSmBodyLineHeight 100%
#define BrkJackpotHeroSmBodyFontSize 12
#define BrkJackpotHeroSmBodyLetterSpacing 0%
#define BrkJackpotHeroSmBodyParagraphSpacing 
#define BrkJackpotHeroSmBodyTextCase none
#define BrkJackpotHeroSmBodyTextDecoration none
#define BrkJackpotHeroSmHeight 36
#define BrkJackpotHeroSmAmountDigitHeight 20
#define BrkJackpotHeroSmAmountDigitWidth 14
#define BrkJackpotHeroMdPaddingHorizontal 16
#define BrkJackpotHeroMdAmountDigitMargin 2
#define BrkJackpotHeroMdAmountGroupMargin 5
#define BrkJackpotHeroMdContentGap 16
#define BrkJackpotHeroMdHeadingFontFamily Graphik
#define BrkJackpotHeroMdHeadingFontWeight Bold
#define BrkJackpotHeroMdHeadingLineHeight 110%
#define BrkJackpotHeroMdHeadingFontSize 16
#define BrkJackpotHeroMdHeadingLetterSpacing -2%
#define BrkJackpotHeroMdHeadingParagraphSpacing 
#define BrkJackpotHeroMdHeadingTextCase none
#define BrkJackpotHeroMdHeadingTextDecoration none
#define BrkJackpotHeroMdBodyFontFamily Arial
#define BrkJackpotHeroMdBodyFontWeight Bold
#define BrkJackpotHeroMdBodyLineHeight 100%
#define BrkJackpotHeroMdBodyFontSize 20
#define BrkJackpotHeroMdBodyLetterSpacing 0%
#define BrkJackpotHeroMdBodyParagraphSpacing 
#define BrkJackpotHeroMdBodyTextCase none
#define BrkJackpotHeroMdBodyTextDecoration none
#define BrkJackpotHeroMdHeight 60
#define BrkJackpotHeroMdAmountDigitHeight 28
#define BrkJackpotHeroMdAmountDigitWidth 20
#define BrkJackpotHeroLgPaddingHorizontal 24
#define BrkJackpotHeroLgAmountDigitMargin 3
#define BrkJackpotHeroLgAmountGroupMargin 6
#define BrkJackpotHeroLgContentGap 24
#define BrkJackpotHeroLgHeadingFontFamily Graphik
#define BrkJackpotHeroLgHeadingFontWeight Bold
#define BrkJackpotHeroLgHeadingLineHeight 110%
#define BrkJackpotHeroLgHeadingFontSize 20
#define BrkJackpotHeroLgHeadingLetterSpacing -2%
#define BrkJackpotHeroLgHeadingParagraphSpacing 
#define BrkJackpotHeroLgHeadingTextCase none
#define BrkJackpotHeroLgHeadingTextDecoration none
#define BrkJackpotHeroLgBodyFontFamily Arial
#define BrkJackpotHeroLgBodyFontWeight Bold
#define BrkJackpotHeroLgBodyLineHeight 100%
#define BrkJackpotHeroLgBodyFontSize 24
#define BrkJackpotHeroLgBodyLetterSpacing 2%
#define BrkJackpotHeroLgBodyParagraphSpacing 
#define BrkJackpotHeroLgBodyTextCase none
#define BrkJackpotHeroLgBodyTextDecoration none
#define BrkJackpotHeroLgHeight 72
#define BrkJackpotHeroLgAmountDigitHeight 40
#define BrkJackpotHeroLgAmountDigitWidth 30
#define BrkJackpotHeroXlPaddingHorizontal 24
#define BrkJackpotHeroXlAmountDigitMargin 4
#define BrkJackpotHeroXlAmountGroupMargin 8
#define BrkJackpotHeroXlContentGap 24
#define BrkJackpotHeroXlHeadingFontFamily Graphik
#define BrkJackpotHeroXlHeadingFontWeight Bold
#define BrkJackpotHeroXlHeadingLineHeight 110%
#define BrkJackpotHeroXlHeadingFontSize 20
#define BrkJackpotHeroXlHeadingLetterSpacing -2%
#define BrkJackpotHeroXlHeadingParagraphSpacing 
#define BrkJackpotHeroXlHeadingTextCase none
#define BrkJackpotHeroXlHeadingTextDecoration none
#define BrkJackpotHeroXlBodyFontFamily Arial
#define BrkJackpotHeroXlBodyFontWeight Bold
#define BrkJackpotHeroXlBodyLineHeight 110%
#define BrkJackpotHeroXlBodyFontSize 28
#define BrkJackpotHeroXlBodyLetterSpacing 0%
#define BrkJackpotHeroXlBodyParagraphSpacing 
#define BrkJackpotHeroXlBodyTextCase none
#define BrkJackpotHeroXlBodyTextDecoration none
#define BrkJackpotHeroXlHeight 72
#define BrkJackpotHeroXlAmountDigitHeight 44
#define BrkJackpotHeroXlAmountDigitWidth 30
#define BrkJackpotHeroAmountDigitBorderWidth 0
#define BrkJackpotHeroAmountDigitBorderRadius 4
#define BrkJackpotHeroStandardHeadingFontColor #ffffff
#define BrkJackpotHeroStandardBodyFontColor #090f2a
#define BrkJackpotHeroStandardBodyBoxBackgroundColor #ffffff
#define BrkJackpotHeroStandardBodyBoxBorderColor transparent
#define BrkJackpotHeroStandardBackgroundColor #060606
#define BrkJackpotHeroStandardSymbolFontColor #ffffff
#define BrkButtonPrimarySmPaddingHorizontal 15
#define BrkButtonPrimarySmHeight 30
#define BrkButtonPrimarySmBorderRadius 15
#define BrkButtonPrimarySmIconHeight 12
#define BrkButtonPrimarySmIconGap 4
#define BrkButtonPrimaryMdPaddingHorizontal 32
#define BrkButtonPrimaryMdHeight 40
#define BrkButtonPrimaryMdBorderRadius 20
#define BrkButtonPrimaryMdIconHeight 16
#define BrkButtonPrimaryMdIconGap 6
#define BrkButtonPrimaryLgPaddingHorizontal 32
#define BrkButtonPrimaryLgHeight 50
#define BrkButtonPrimaryLgBorderRadius 25
#define BrkButtonPrimaryLgIconHeight 20
#define BrkButtonPrimaryLgIconGap 8
#define BrkButtonPrimaryXlPaddingHorizontal 40
#define BrkButtonPrimaryXlHeight 60
#define BrkButtonPrimaryXlBorderRadius 30
#define BrkButtonPrimaryXlIconHeight 24
#define BrkButtonPrimaryXlIconGap 10
#define BrkButtonPrimarySmLabelFontFamily Arial
#define BrkButtonPrimarySmLabelFontWeight Bold
#define BrkButtonPrimarySmLabelLineHeight 100%
#define BrkButtonPrimarySmLabelFontSize 13
#define BrkButtonPrimarySmLabelLetterSpacing 2%
#define BrkButtonPrimarySmLabelParagraphSpacing 
#define BrkButtonPrimarySmLabelTextDecoration none
#define BrkButtonPrimarySmLabelTextCase none
#define BrkButtonPrimaryMdLabelFontFamily Arial
#define BrkButtonPrimaryMdLabelFontWeight Bold
#define BrkButtonPrimaryMdLabelLineHeight 100%
#define BrkButtonPrimaryMdLabelFontSize 18
#define BrkButtonPrimaryMdLabelLetterSpacing 2%
#define BrkButtonPrimaryMdLabelParagraphSpacing 
#define BrkButtonPrimaryMdLabelTextDecoration none
#define BrkButtonPrimaryMdLabelTextCase uppercase
#define BrkButtonPrimaryLgLabelFontFamily Arial
#define BrkButtonPrimaryLgLabelFontWeight Bold
#define BrkButtonPrimaryLgLabelLineHeight 100%
#define BrkButtonPrimaryLgLabelFontSize 22
#define BrkButtonPrimaryLgLabelLetterSpacing 2%
#define BrkButtonPrimaryLgLabelParagraphSpacing 
#define BrkButtonPrimaryLgLabelTextDecoration none
#define BrkButtonPrimaryLgLabelTextCase uppercase
#define BrkButtonPrimaryXlLabelFontFamily Arial
#define BrkButtonPrimaryXlLabelFontWeight Bold
#define BrkButtonPrimaryXlLabelLineHeight 100%
#define BrkButtonPrimaryXlLabelFontSize 26
#define BrkButtonPrimaryXlLabelLetterSpacing 2%
#define BrkButtonPrimaryXlLabelParagraphSpacing 
#define BrkButtonPrimaryXlLabelTextDecoration none
#define BrkButtonPrimaryXlLabelTextCase uppercase
#define BrkButtonSecondarySmHeight 30
#define BrkButtonSecondarySmBorderRadius 15
#define BrkButtonSecondarySmPaddingHorizontal 15
#define BrkButtonSecondarySmIconHeight 12
#define BrkButtonSecondarySmIconGap 4
#define BrkButtonSecondaryMdHeight 40
#define BrkButtonSecondaryMdBorderRadius 20
#define BrkButtonSecondaryMdPaddingHorizontal 20
#define BrkButtonSecondaryMdIconHeight 16
#define BrkButtonSecondaryMdIconGap 6
#define BrkButtonSecondaryLgHeight 50
#define BrkButtonSecondaryLgBorderRadius 25
#define BrkButtonSecondaryLgPaddingHorizontal 25
#define BrkButtonSecondaryLgIconHeight 20
#define BrkButtonSecondaryLgIconGap 8
#define BrkButtonSecondaryXlHeight 60
#define BrkButtonSecondaryXlBorderRadius 30
#define BrkButtonSecondaryXlPaddingHorizontal 30
#define BrkButtonSecondaryXlIconHeight 24
#define BrkButtonSecondaryXlIconGap 10
#define BrkButtonSecondarySmLabelFontFamily Arial
#define BrkButtonSecondarySmLabelFontWeight Bold
#define BrkButtonSecondarySmLabelLineHeight 100%
#define BrkButtonSecondarySmLabelFontSize 11
#define BrkButtonSecondarySmLabelLetterSpacing 0%
#define BrkButtonSecondarySmLabelParagraphSpacing 
#define BrkButtonSecondarySmLabelTextDecoration none
#define BrkButtonSecondarySmLabelTextCase none
#define BrkButtonSecondaryMdLabelFontFamily Arial
#define BrkButtonSecondaryMdLabelFontWeight Bold
#define BrkButtonSecondaryMdLabelLineHeight 100%
#define BrkButtonSecondaryMdLabelFontSize 15
#define BrkButtonSecondaryMdLabelLetterSpacing 0%
#define BrkButtonSecondaryMdLabelParagraphSpacing 
#define BrkButtonSecondaryMdLabelTextDecoration none
#define BrkButtonSecondaryMdLabelTextCase none
#define BrkButtonSecondaryLgLabelFontFamily Arial
#define BrkButtonSecondaryLgLabelFontWeight Bold
#define BrkButtonSecondaryLgLabelLineHeight 100%
#define BrkButtonSecondaryLgLabelFontSize 18
#define BrkButtonSecondaryLgLabelLetterSpacing 0%
#define BrkButtonSecondaryLgLabelParagraphSpacing 
#define BrkButtonSecondaryLgLabelTextDecoration none
#define BrkButtonSecondaryLgLabelTextCase none
#define BrkButtonSecondaryXlLabelFontFamily Arial
#define BrkButtonSecondaryXlLabelFontWeight Bold
#define BrkButtonSecondaryXlLabelLineHeight 100%
#define BrkButtonSecondaryXlLabelFontSize 20
#define BrkButtonSecondaryXlLabelLetterSpacing 0%
#define BrkButtonSecondaryXlLabelParagraphSpacing 
#define BrkButtonSecondaryXlLabelTextDecoration none
#define BrkButtonSecondaryXlLabelTextCase none
#define BrkPromoSecondaryStandardPretitleFontColor #000000
#define BrkPromoSecondaryStandardHeadingFontColor #000000
#define BrkPromoSecondaryStandardBodyFontColor #000000
#define BrkPromoSecondaryStandardBackgroundColor #ffffff
#define BrkPromoSecondaryStandardBorderColor #e6e6e6
#define BrkPromoSecondaryStandardGradientColor linear-gradient(180deg, #ffffff00 0%, #ffffff 100%)
#define BrkPromoSecondaryStandardBoxShadowDefault [object Object]
#define BrkPromoSecondaryStandardBoxShadowHover [object Object]
#define BrkPromoSecondaryInvertedPretitleFontColor #ffffff
#define BrkPromoSecondaryInvertedHeadingFontColor #ffffff
#define BrkPromoSecondaryInvertedBodyFontColor #ffffff
#define BrkPromoSecondaryInvertedBackgroundColor #000000
#define BrkPromoSecondaryInvertedBorderColor #e6e6e6
#define BrkPromoSecondaryInvertedGradientColor linear-gradient(180deg, #00000000 0%, #000000 100%)
#define BrkPromoPrimaryInvertedPretitleFontColor #ffffff
#define BrkPromoPrimaryInvertedHeadingFontColor #ffffff
#define BrkPromoPrimaryInvertedBodyFontColor #ffffff
#define BrkPromoPrimaryInvertedBackgroundColor #000000
#define BrkPromoPrimaryInvertedBorderColor #e6e6e6
#define BrkPromoPrimaryInvertedGradientColor linear-gradient(180deg, #00000000 0%, #000000 100%)
#define BrkPromoPrimaryStandardPretitleFontColor #060606
#define BrkPromoPrimaryStandardHeadingFontColor #060606
#define BrkPromoPrimaryStandardBodyFontColor #060606
#define BrkPromoPrimaryStandardBackgroundColor #ffffff
#define BrkPromoPrimaryStandardBorderColor #e6e6e6
#define BrkPromoPrimaryStandardGradientColor linear-gradient(180deg, #ffffff00 0%, #ffffff 100%)
#define BrkPromoTertiaryInvertedPretitleFontColor #000000
#define BrkPromoTertiaryInvertedHeadingFontColor #000000
#define BrkPromoTertiaryInvertedBodyFontColor #000000
#define BrkPromoTertiaryInvertedBackgroundColor #000000
#define BrkPromoTertiaryInvertedBorderColor #e6e6e6
#define BrkPromoTertiaryInvertedGradientColor linear-gradient(180deg, #00000000 0%, #000000 100%)
#define BrkPromoTertiaryInvertedFrameColor #ffffff
#define BrkPromoTertiaryStandardPretitleFontColor #ffffff
#define BrkPromoTertiaryStandardHeadingFontColor #ffffff
#define BrkPromoTertiaryStandardBodyFontColor #ffffff
#define BrkPromoTertiaryStandardBackgroundColor #ffffff
#define BrkPromoTertiaryStandardBorderColor #e6e6e6
#define BrkPromoTertiaryStandardGradientColor linear-gradient(180deg, #ffffff00 0%, #ffffff 100%)
#define BrkPromoTertiaryStandardFrameColor #000000
#define BrkPromoTertiarySmImageHeight 172
#define BrkPromoTertiarySmGradientHeight 43
#define BrkPromoTertiarySmPaddingHorizontal 16
#define BrkPromoTertiarySmPaddingVertical 16
#define BrkPromoTertiarySmFramePaddingHorizontal 16
#define BrkPromoTertiarySmFramePaddingVertical 16
#define BrkPromoTertiarySmContentGap 16
#define BrkPromoTertiarySmPretitleMarginBottom 4
#define BrkPromoTertiarySmPretitleFontFamily Arial
#define BrkPromoTertiarySmPretitleFontWeight Bold
#define BrkPromoTertiarySmPretitleLineHeight 110%
#define BrkPromoTertiarySmPretitleFontSize 13
#define BrkPromoTertiarySmPretitleLetterSpacing 0%
#define BrkPromoTertiarySmPretitleParagraphSpacing 
#define BrkPromoTertiarySmPretitleTextDecoration none
#define BrkPromoTertiarySmPretitleTextCase none
#define BrkPromoTertiarySmHeadingFontFamily Graphik
#define BrkPromoTertiarySmHeadingFontWeight Super
#define BrkPromoTertiarySmHeadingLineHeight 110%
#define BrkPromoTertiarySmHeadingFontSize 28
#define BrkPromoTertiarySmHeadingLetterSpacing -2%
#define BrkPromoTertiarySmHeadingParagraphSpacing 
#define BrkPromoTertiarySmHeadingTextCase none
#define BrkPromoTertiarySmHeadingTextDecoration none
#define BrkPromoTertiaryMdImageHeight 270
#define BrkPromoTertiaryMdGradientHeight 67.5
#define BrkPromoTertiaryMdPaddingHorizontal 20
#define BrkPromoTertiaryMdPaddingVertical 20
#define BrkPromoTertiaryMdFramePaddingHorizontal 20
#define BrkPromoTertiaryMdFramePaddingVertical 20
#define BrkPromoTertiaryMdContentGap 16
#define BrkPromoTertiaryMdPretitleMarginBottom 6
#define BrkPromoTertiaryMdPretitleFontFamily Arial
#define BrkPromoTertiaryMdPretitleFontWeight Bold
#define BrkPromoTertiaryMdPretitleLineHeight 110%
#define BrkPromoTertiaryMdPretitleFontSize 14
#define BrkPromoTertiaryMdPretitleLetterSpacing 0%
#define BrkPromoTertiaryMdPretitleParagraphSpacing 
#define BrkPromoTertiaryMdPretitleTextDecoration none
#define BrkPromoTertiaryMdPretitleTextCase none
#define BrkPromoTertiaryMdHeadingFontFamily Graphik
#define BrkPromoTertiaryMdHeadingFontWeight Super
#define BrkPromoTertiaryMdHeadingLineHeight 110%
#define BrkPromoTertiaryMdHeadingFontSize 28
#define BrkPromoTertiaryMdHeadingLetterSpacing -2%
#define BrkPromoTertiaryMdHeadingParagraphSpacing 
#define BrkPromoTertiaryMdHeadingTextCase none
#define BrkPromoTertiaryMdHeadingTextDecoration none
#define BrkPromoTertiaryLgImageHeight 300
#define BrkPromoTertiaryLgGradientHeight 75
#define BrkPromoTertiaryLgPaddingHorizontal 24
#define BrkPromoTertiaryLgPaddingVertical 24
#define BrkPromoTertiaryLgFramePaddingHorizontal 20
#define BrkPromoTertiaryLgFramePaddingVertical 20
#define BrkPromoTertiaryLgContentGap 16
#define BrkPromoTertiaryLgPretitleMarginBottom 6
#define BrkPromoTertiaryLgPretitleFontFamily Arial
#define BrkPromoTertiaryLgPretitleFontWeight Bold
#define BrkPromoTertiaryLgPretitleLineHeight 110%
#define BrkPromoTertiaryLgPretitleFontSize 16
#define BrkPromoTertiaryLgPretitleLetterSpacing 0%
#define BrkPromoTertiaryLgPretitleParagraphSpacing 
#define BrkPromoTertiaryLgPretitleTextDecoration none
#define BrkPromoTertiaryLgPretitleTextCase none
#define BrkPromoTertiaryLgHeadingFontFamily Graphik
#define BrkPromoTertiaryLgHeadingFontWeight Super
#define BrkPromoTertiaryLgHeadingLineHeight 110%
#define BrkPromoTertiaryLgHeadingFontSize 32
#define BrkPromoTertiaryLgHeadingLetterSpacing -2%
#define BrkPromoTertiaryLgHeadingParagraphSpacing 
#define BrkPromoTertiaryLgHeadingTextCase none
#define BrkPromoTertiaryLgHeadingTextDecoration none
#define BrkPromoTertiaryXlImageHeight 568
#define BrkPromoTertiaryXlGradientHeight 142
#define BrkPromoTertiaryXlContentWidth 312
#define BrkPromoTertiaryXlContentMaxWidth 470
#define BrkPromoTertiaryXlPaddingHorizontal 32
#define BrkPromoTertiaryXlPaddingVertical 32
#define BrkPromoTertiaryXlFramePaddingHorizontal 10
#define BrkPromoTertiaryXlFramePaddingVertical 10
#define BrkPromoTertiaryXlContentGap 32
#define BrkPromoTertiaryXlPretitleMarginBottom 12
#define BrkPromoTertiaryXlPretitleFontFamily Arial
#define BrkPromoTertiaryXlPretitleFontWeight Bold
#define BrkPromoTertiaryXlPretitleLineHeight 110%
#define BrkPromoTertiaryXlPretitleFontSize 16
#define BrkPromoTertiaryXlPretitleLetterSpacing 0%
#define BrkPromoTertiaryXlPretitleParagraphSpacing 
#define BrkPromoTertiaryXlPretitleTextDecoration none
#define BrkPromoTertiaryXlPretitleTextCase none
#define BrkPromoTertiaryXlHeadingFontFamily Graphik
#define BrkPromoTertiaryXlHeadingFontWeight Super
#define BrkPromoTertiaryXlHeadingLineHeight 110%
#define BrkPromoTertiaryXlHeadingFontSize 42
#define BrkPromoTertiaryXlHeadingLetterSpacing -2%
#define BrkPromoTertiaryXlHeadingParagraphSpacing 
#define BrkPromoTertiaryXlHeadingTextCase none
#define BrkPromoTertiaryXlHeadingTextDecoration none
#define BrkButtonIconInvertedBoxShadowDefault [object Object]
#define BrkButtonIconInvertedBoxShadowHover [object Object]
#define BrkButtonIconInvertedBoxShadowFocus [object Object]
#define BrkPageStandardSubheadingFontColor #000000

