
//
// tokens.h
//

// Do not edit directly
// Generated on Thu, 20 Oct 2022 20:41:46 GMT


#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

#define BrkInteractiveStandardOutlineColorFocus #192872
#define BrkInteractiveInvertedOutlineColorFocus #abb6ed
#define BrkInteractiveOutlineWidth 2
#define BrkInteractiveOutlineOffset 5
#define BrkInteractiveOutlineBorderRadius 4
#define BrkButtonOpacityDisabled 50%
#define BrkButtonPrimaryBorderWidth 0
#define BrkButtonSecondaryBorderWidth 2
#define BrkButtonTertiaryBorderWidth 0
#define BrkButtonTertiaryStandardBoxShadowDefault [object Object]
#define BrkButtonTertiaryStandardBoxShadowHover [object Object]
#define BrkButtonTertiaryStandardBoxShadowFocus [object Object]
#define BrkButtonTertiaryStandardFontColorDefault #253aa7
#define BrkButtonTertiaryStandardIconFillDefault #253aa7
#define BrkButtonTertiaryStandardBackgroundColorDefault #eaedfa
#define BrkButtonTertiaryStandardBorderColorDefault transparent
#define BrkButtonTertiaryStandardFontColorHover #ffffff
#define BrkButtonTertiaryStandardIconFillHover #ffffff
#define BrkButtonTertiaryStandardBackgroundColorHover #2e49d1
#define BrkButtonTertiaryStandardBorderColorHover transparent
#define BrkButtonTertiaryStandardFontColorFocus #ffffff
#define BrkButtonTertiaryStandardIconFillFocus #ffffff
#define BrkButtonTertiaryStandardBackgroundColorFocus #2e49d1
#define BrkButtonTertiaryStandardBorderColorFocus transparent
#define BrkButtonTertiaryInvertedBoxShadowDefault [object Object]
#define BrkButtonTertiaryInvertedBoxShadowHover [object Object]
#define BrkButtonTertiaryInvertedBoxShadowFocus [object Object]
#define BrkButtonTertiaryInvertedFontColorDefault #192872
#define BrkButtonTertiaryInvertedIconFillDefault #192872
#define BrkButtonTertiaryInvertedBackgroundColorDefault #ffffff
#define BrkButtonTertiaryInvertedBorderColorDefault transparent
#define BrkButtonTertiaryInvertedFontColorHover #ffffff
#define BrkButtonTertiaryInvertedIconFillHover #ffffff
#define BrkButtonTertiaryInvertedBackgroundColorHover #2e49d1
#define BrkButtonTertiaryInvertedBorderColorHover transparent
#define BrkButtonTertiaryInvertedFontColorFocus #ffffff
#define BrkButtonTertiaryInvertedIconFillFocus #ffffff
#define BrkButtonTertiaryInvertedBackgroundColorFocus #2e49d1
#define BrkButtonTertiaryInvertedBorderColorFocus transparent
#define BrkButtonTertiarySmLabelFontFamily Arial
#define BrkButtonTertiarySmLabelFontWeight Bold
#define BrkButtonTertiarySmLabelLineHeight 85%
#define BrkButtonTertiarySmLabelFontSize 10
#define BrkButtonTertiarySmLabelLetterSpacing 2%
#define BrkButtonTertiarySmLabelParagraphSpacing 
#define BrkButtonTertiarySmLabelTextCase uppercase
#define BrkButtonTertiarySmLabelTextDecoration none
#define BrkButtonTertiaryMdLabelFontFamily Arial
#define BrkButtonTertiaryMdLabelFontWeight Bold
#define BrkButtonTertiaryMdLabelLineHeight 85%
#define BrkButtonTertiaryMdLabelFontSize 14
#define BrkButtonTertiaryMdLabelLetterSpacing 2%
#define BrkButtonTertiaryMdLabelParagraphSpacing 
#define BrkButtonTertiaryMdLabelTextCase uppercase
#define BrkButtonTertiaryMdLabelTextDecoration none
#define BrkButtonTertiaryLgLabelFontFamily Arial
#define BrkButtonTertiaryLgLabelFontWeight Bold
#define BrkButtonTertiaryLgLabelLineHeight 85%
#define BrkButtonTertiaryLgLabelFontSize 18
#define BrkButtonTertiaryLgLabelLetterSpacing 2%
#define BrkButtonTertiaryLgLabelParagraphSpacing 
#define BrkButtonTertiaryLgLabelTextCase uppercase
#define BrkButtonTertiaryLgLabelTextDecoration none
#define BrkButtonTertiaryXlLabelFontFamily Arial
#define BrkButtonTertiaryXlLabelFontWeight Bold
#define BrkButtonTertiaryXlLabelLineHeight 85%
#define BrkButtonTertiaryXlLabelFontSize 22
#define BrkButtonTertiaryXlLabelLetterSpacing 2%
#define BrkButtonTertiaryXlLabelParagraphSpacing 
#define BrkButtonTertiaryXlLabelTextCase uppercase
#define BrkButtonTertiaryXlLabelTextDecoration none
#define BrkButtonTertiarySmPaddingHorizontal 15
#define BrkButtonTertiarySmBorderRadius 4
#define BrkButtonTertiarySmHeight 30
#define BrkButtonTertiarySmIconSize 8
#define BrkButtonTertiarySmIconGap 4
#define BrkButtonTertiaryMdPaddingHorizontal 20
#define BrkButtonTertiaryMdBorderRadius 6
#define BrkButtonTertiaryMdHeight 40
#define BrkButtonTertiaryMdIconSize 10
#define BrkButtonTertiaryMdIconGap 6
#define BrkButtonTertiaryLgPaddingHorizontal 30
#define BrkButtonTertiaryLgBorderRadius 8
#define BrkButtonTertiaryLgHeight 50
#define BrkButtonTertiaryLgIconSize 12
#define BrkButtonTertiaryLgIconGap 8
#define BrkButtonTertiaryXlPaddingHorizontal 36
#define BrkButtonTertiaryXlBorderRadius 8
#define BrkButtonTertiaryXlHeight 60
#define BrkButtonTertiaryXlIconSize 14
#define BrkButtonTertiaryXlIconGap 10
#define BrkJackpotHeroSmHeadingFontFamily Graphik
#define BrkJackpotHeroSmHeadingFontWeight Bold
#define BrkJackpotHeroSmHeadingLineHeight 110%
#define BrkJackpotHeroSmHeadingFontSize 8
#define BrkJackpotHeroSmHeadingLetterSpacing -2%
#define BrkJackpotHeroSmHeadingParagraphSpacing 
#define BrkJackpotHeroSmHeadingTextCase uppercase
#define BrkJackpotHeroSmHeadingTextDecoration none
#define BrkJackpotHeroSmBodyFontFamily Arial
#define BrkJackpotHeroSmBodyFontWeight Bold
#define BrkJackpotHeroSmBodyLineHeight 100%
#define BrkJackpotHeroSmBodyFontSize 12
#define BrkJackpotHeroSmBodyLetterSpacing 2%
#define BrkJackpotHeroSmBodyParagraphSpacing 
#define BrkJackpotHeroSmBodyTextCase uppercase
#define BrkJackpotHeroSmBodyTextDecoration none
#define BrkJackpotHeroSmHeight 36
#define BrkJackpotHeroSmAmountDigitHeight 20
#define BrkJackpotHeroSmAmountDigitWidth 14
#define BrkJackpotHeroSmContentGap 16
#define BrkJackpotHeroSmPaddingHorizontal 10
#define BrkJackpotHeroSmAmountDigitMargin 1
#define BrkJackpotHeroSmAmountGroupMargin 4
#define BrkJackpotHeroMdHeadingFontFamily Graphik
#define BrkJackpotHeroMdHeadingFontWeight Bold
#define BrkJackpotHeroMdHeadingLineHeight 110%
#define BrkJackpotHeroMdHeadingFontSize 14
#define BrkJackpotHeroMdHeadingLetterSpacing -2%
#define BrkJackpotHeroMdHeadingParagraphSpacing 
#define BrkJackpotHeroMdHeadingTextCase uppercase
#define BrkJackpotHeroMdHeadingTextDecoration none
#define BrkJackpotHeroMdBodyFontFamily Arial
#define BrkJackpotHeroMdBodyFontWeight Bold
#define BrkJackpotHeroMdBodyLineHeight 100%
#define BrkJackpotHeroMdBodyFontSize 20
#define BrkJackpotHeroMdBodyLetterSpacing 2%
#define BrkJackpotHeroMdBodyParagraphSpacing 
#define BrkJackpotHeroMdBodyTextCase uppercase
#define BrkJackpotHeroMdBodyTextDecoration none
#define BrkJackpotHeroMdHeight 60
#define BrkJackpotHeroMdAmountDigitHeight 28
#define BrkJackpotHeroMdAmountDigitWidth 20
#define BrkJackpotHeroMdContentGap 16
#define BrkJackpotHeroMdPaddingHorizontal 16
#define BrkJackpotHeroMdAmountDigitMargin 2
#define BrkJackpotHeroMdAmountGroupMargin 5
#define BrkJackpotHeroLgHeadingFontFamily Graphik
#define BrkJackpotHeroLgHeadingFontWeight Bold
#define BrkJackpotHeroLgHeadingLineHeight 110%
#define BrkJackpotHeroLgHeadingFontSize 18
#define BrkJackpotHeroLgHeadingLetterSpacing -2%
#define BrkJackpotHeroLgHeadingParagraphSpacing 
#define BrkJackpotHeroLgHeadingTextCase uppercase
#define BrkJackpotHeroLgHeadingTextDecoration none
#define BrkJackpotHeroLgBodyFontFamily Arial
#define BrkJackpotHeroLgBodyFontWeight Bold
#define BrkJackpotHeroLgBodyLineHeight 100%
#define BrkJackpotHeroLgBodyFontSize 24
#define BrkJackpotHeroLgBodyLetterSpacing 2%
#define BrkJackpotHeroLgBodyParagraphSpacing 
#define BrkJackpotHeroLgBodyTextCase uppercase
#define BrkJackpotHeroLgBodyTextDecoration none
#define BrkJackpotHeroLgHeight 72
#define BrkJackpotHeroLgAmountDigitHeight 40
#define BrkJackpotHeroLgAmountDigitWidth 30
#define BrkJackpotHeroLgContentGap 24
#define BrkJackpotHeroLgPaddingHorizontal 24
#define BrkJackpotHeroLgAmountDigitMargin 3
#define BrkJackpotHeroLgAmountGroupMargin 6
#define BrkJackpotHeroXlHeadingFontFamily Graphik
#define BrkJackpotHeroXlHeadingFontWeight Bold
#define BrkJackpotHeroXlHeadingLineHeight 110%
#define BrkJackpotHeroXlHeadingFontSize 18
#define BrkJackpotHeroXlHeadingLetterSpacing -2%
#define BrkJackpotHeroXlHeadingParagraphSpacing 
#define BrkJackpotHeroXlHeadingTextCase uppercase
#define BrkJackpotHeroXlHeadingTextDecoration none
#define BrkJackpotHeroXlBodyFontFamily Arial
#define BrkJackpotHeroXlBodyFontWeight Bold
#define BrkJackpotHeroXlBodyLineHeight 100%
#define BrkJackpotHeroXlBodyFontSize 28
#define BrkJackpotHeroXlBodyLetterSpacing 2%
#define BrkJackpotHeroXlBodyParagraphSpacing 
#define BrkJackpotHeroXlBodyTextCase uppercase
#define BrkJackpotHeroXlBodyTextDecoration none
#define BrkJackpotHeroXlHeight 72
#define BrkJackpotHeroXlAmountDigitHeight 44
#define BrkJackpotHeroXlAmountDigitWidth 30
#define BrkJackpotHeroXlContentGap 24
#define BrkJackpotHeroXlPaddingHorizontal 24
#define BrkJackpotHeroXlAmountDigitMargin 4
#define BrkJackpotHeroXlAmountGroupMargin 8
#define BrkJackpotHeroAmountDigitBorderRadius 1
#define BrkJackpotHeroAmountDigitBorderWidth 0
#define BrkJackpotHeroStandardHeadingFontColor #eaedfa
#define BrkJackpotHeroStandardBodyFontColor #000000
#define BrkJackpotHeroStandardBodyBoxBackgroundColor #ffffff
#define BrkJackpotHeroStandardBodyBoxBorderColor transparent
#define BrkJackpotHeroStandardBackgroundColor #121d54
#define BrkJackpotHeroStandardSymbolFontColor #ffffff
#define BrkCardHeroSmPretitleFontFamily Graphik
#define BrkCardHeroSmPretitleFontWeight Bold
#define BrkCardHeroSmPretitleLineHeight 8
#define BrkCardHeroSmPretitleFontSize 8
#define BrkCardHeroSmPretitleLetterSpacing -2%
#define BrkCardHeroSmPretitleParagraphSpacing 
#define BrkCardHeroSmPretitleTextCase uppercase
#define BrkCardHeroSmPretitleTextDecoration none
#define BrkCardHeroSmImageHeight 180
#define BrkCardHeroSmPaddingHorizontal 10
#define BrkCardHeroSmPaddingVertical 10
#define BrkCardHeroSmHeadingMarginVertical 4
#define BrkCardHeroSmContentGap 16
#define BrkCardHeroSmHeadingFontFamily Arial
#define BrkCardHeroSmHeadingFontWeight Regular
#define BrkCardHeroSmHeadingLineHeight 100%
#define BrkCardHeroSmHeadingFontSize 14
#define BrkCardHeroSmHeadingLetterSpacing -2%
#define BrkCardHeroSmHeadingParagraphSpacing 
#define BrkCardHeroSmHeadingTextCase none
#define BrkCardHeroSmHeadingTextDecoration none
#define BrkCardHeroSmBodyFontFamily Arial
#define BrkCardHeroSmBodyFontWeight Regular
#define BrkCardHeroSmBodyLineHeight 85%
#define BrkCardHeroSmBodyFontSize 9
#define BrkCardHeroSmBodyLetterSpacing 2%
#define BrkCardHeroSmBodyParagraphSpacing 
#define BrkCardHeroSmBodyTextCase none
#define BrkCardHeroSmBodyTextDecoration none
#define BrkCardHeroLgPretitleFontFamily Graphik
#define BrkCardHeroLgPretitleFontWeight Bold
#define BrkCardHeroLgPretitleLineHeight 14
#define BrkCardHeroLgPretitleFontSize 14
#define BrkCardHeroLgPretitleLetterSpacing -2%
#define BrkCardHeroLgPretitleParagraphSpacing 
#define BrkCardHeroLgPretitleTextCase uppercase
#define BrkCardHeroLgPretitleTextDecoration none
#define BrkCardHeroLgImageHeight 270
#define BrkCardHeroLgPaddingHorizontal 24
#define BrkCardHeroLgPaddingVertical 24
#define BrkCardHeroLgHeadingMarginVertical 8
#define BrkCardHeroLgContentGap 24
#define BrkCardHeroLgHeadingFontFamily Arial
#define BrkCardHeroLgHeadingFontWeight Regular
#define BrkCardHeroLgHeadingLineHeight 100%
#define BrkCardHeroLgHeadingFontSize 30
#define BrkCardHeroLgHeadingLetterSpacing -2%
#define BrkCardHeroLgHeadingParagraphSpacing 
#define BrkCardHeroLgHeadingTextCase none
#define BrkCardHeroLgHeadingTextDecoration none
#define BrkCardHeroLgBodyFontFamily Arial
#define BrkCardHeroLgBodyFontWeight Regular
#define BrkCardHeroLgBodyLineHeight 85%
#define BrkCardHeroLgBodyFontSize 15
#define BrkCardHeroLgBodyLetterSpacing 2%
#define BrkCardHeroLgBodyParagraphSpacing 
#define BrkCardHeroLgBodyTextCase none
#define BrkCardHeroLgBodyTextDecoration none
#define BrkCardHeroXlPretitleFontFamily Graphik
#define BrkCardHeroXlPretitleFontWeight Bold
#define BrkCardHeroXlPretitleLineHeight 18
#define BrkCardHeroXlPretitleFontSize 18
#define BrkCardHeroXlPretitleLetterSpacing -2%
#define BrkCardHeroXlPretitleParagraphSpacing 
#define BrkCardHeroXlPretitleTextCase uppercase
#define BrkCardHeroXlPretitleTextDecoration none
#define BrkCardHeroXlImageHeight 320
#define BrkCardHeroXlPaddingHorizontal 24
#define BrkCardHeroXlPaddingVertical 24
#define BrkCardHeroXlHeadingMarginVertical 8
#define BrkCardHeroXlContentGap 16
#define BrkCardHeroXlHeadingFontFamily Arial
#define BrkCardHeroXlHeadingFontWeight Regular
#define BrkCardHeroXlHeadingLineHeight 100%
#define BrkCardHeroXlHeadingFontSize 40
#define BrkCardHeroXlHeadingLetterSpacing -2%
#define BrkCardHeroXlHeadingParagraphSpacing 
#define BrkCardHeroXlHeadingTextCase none
#define BrkCardHeroXlHeadingTextDecoration none
#define BrkCardHeroXlBodyFontFamily Arial
#define BrkCardHeroXlBodyFontWeight Regular
#define BrkCardHeroXlBodyLineHeight 85%
#define BrkCardHeroXlBodyFontSize 18
#define BrkCardHeroXlBodyLetterSpacing 2%
#define BrkCardHeroXlBodyParagraphSpacing 
#define BrkCardHeroXlBodyTextCase none
#define BrkCardHeroXlBodyTextDecoration none
#define BrkCardHeroMdPretitleFontFamily Graphik
#define BrkCardHeroMdPretitleFontWeight Bold
#define BrkCardHeroMdPretitleLineHeight 12
#define BrkCardHeroMdPretitleFontSize 12
#define BrkCardHeroMdPretitleLetterSpacing -2%
#define BrkCardHeroMdPretitleParagraphSpacing 
#define BrkCardHeroMdPretitleTextCase uppercase
#define BrkCardHeroMdPretitleTextDecoration none
#define BrkCardHeroMdImageHeight 270
#define BrkCardHeroMdPaddingHorizontal 16
#define BrkCardHeroMdPaddingVertical 16
#define BrkCardHeroMdHeadingMarginVertical 4
#define BrkCardHeroMdContentGap 16
#define BrkCardHeroMdHeadingFontFamily Arial
#define BrkCardHeroMdHeadingFontWeight Regular
#define BrkCardHeroMdHeadingLineHeight 100%
#define BrkCardHeroMdHeadingFontSize 25
#define BrkCardHeroMdHeadingLetterSpacing -2%
#define BrkCardHeroMdHeadingParagraphSpacing 
#define BrkCardHeroMdHeadingTextCase none
#define BrkCardHeroMdHeadingTextDecoration none
#define BrkCardHeroMdBodyFontFamily Arial
#define BrkCardHeroMdBodyFontWeight Regular
#define BrkCardHeroMdBodyLineHeight 85%
#define BrkCardHeroMdBodyFontSize 14
#define BrkCardHeroMdBodyLetterSpacing 2%
#define BrkCardHeroMdBodyParagraphSpacing 
#define BrkCardHeroMdBodyTextCase none
#define BrkCardHeroMdBodyTextDecoration none
#define BrkCardHeroBorderWidth 1
#define BrkCardHeroBorderRadius 4
#define BrkPromoPrimaryBorderWidth 1
#define BrkPromoSecondaryBorderWidth 1
#define BrkPromoTertiaryBorderWidth 1
#define BrkPromoSecondaryBorderRadius 4
#define BrkPromoTertiaryFrameBorderRadius 4
#define BrkPromoSecondarySmPaddingHorizontal 12
#define BrkPromoSecondarySmPaddingVertical 12
#define BrkPromoSecondarySmContentGap 10
#define BrkPromoSecondarySmPretitleMarginBottom 4
#define BrkPromoSecondarySmImageHeight 172
#define BrkPromoSecondarySmPretitleFontFamily Graphik
#define BrkPromoSecondarySmPretitleFontWeight Bold
#define BrkPromoSecondarySmPretitleLineHeight 8
#define BrkPromoSecondarySmPretitleFontSize 8
#define BrkPromoSecondarySmPretitleLetterSpacing -2%
#define BrkPromoSecondarySmPretitleParagraphSpacing 
#define BrkPromoSecondarySmPretitleTextCase uppercase
#define BrkPromoSecondarySmPretitleTextDecoration none
#define BrkPromoSecondarySmHeadingFontFamily Arial
#define BrkPromoSecondarySmHeadingFontWeight Regular
#define BrkPromoSecondarySmHeadingLineHeight 100%
#define BrkPromoSecondarySmHeadingFontSize 18
#define BrkPromoSecondarySmHeadingLetterSpacing -2%
#define BrkPromoSecondarySmHeadingParagraphSpacing 
#define BrkPromoSecondarySmHeadingTextCase none
#define BrkPromoSecondarySmHeadingTextDecoration none
#define BrkPromoSecondarySmGradientHeight 43
#define BrkPromoSecondaryMdImageHeight 270
#define BrkPromoSecondaryMdGradientHeight 67.5
#define BrkPromoSecondaryMdPaddingHorizontal 20
#define BrkPromoSecondaryMdPaddingVertical 20
#define BrkPromoSecondaryMdContentGap 20
#define BrkPromoSecondaryMdPretitleMarginBottom 6
#define BrkPromoSecondaryMdPretitleFontFamily Graphik
#define BrkPromoSecondaryMdPretitleFontWeight Bold
#define BrkPromoSecondaryMdPretitleLineHeight 100%
#define BrkPromoSecondaryMdPretitleFontSize 12
#define BrkPromoSecondaryMdPretitleLetterSpacing -2%
#define BrkPromoSecondaryMdPretitleParagraphSpacing 
#define BrkPromoSecondaryMdPretitleTextCase uppercase
#define BrkPromoSecondaryMdPretitleTextDecoration none
#define BrkPromoSecondaryMdHeadingFontFamily Arial
#define BrkPromoSecondaryMdHeadingFontWeight Regular
#define BrkPromoSecondaryMdHeadingLineHeight 100%
#define BrkPromoSecondaryMdHeadingFontSize 30
#define BrkPromoSecondaryMdHeadingLetterSpacing -2%
#define BrkPromoSecondaryMdHeadingParagraphSpacing 
#define BrkPromoSecondaryMdHeadingTextCase none
#define BrkPromoSecondaryMdHeadingTextDecoration none
#define BrkPromoSecondaryLgImageHeight 300
#define BrkPromoSecondaryLgGradientHeight 75
#define BrkPromoSecondaryLgPaddingHorizontal 24
#define BrkPromoSecondaryLgPaddingVertical 20
#define BrkPromoSecondaryLgContentGap 12
#define BrkPromoSecondaryLgPretitleMarginBottom 6
#define BrkPromoSecondaryLgPretitleFontFamily Graphik
#define BrkPromoSecondaryLgPretitleFontWeight Bold
#define BrkPromoSecondaryLgPretitleLineHeight 100%
#define BrkPromoSecondaryLgPretitleFontSize 13
#define BrkPromoSecondaryLgPretitleLetterSpacing -2%
#define BrkPromoSecondaryLgPretitleParagraphSpacing 
#define BrkPromoSecondaryLgPretitleTextCase uppercase
#define BrkPromoSecondaryLgPretitleTextDecoration none
#define BrkPromoSecondaryLgHeadingFontFamily Arial
#define BrkPromoSecondaryLgHeadingFontWeight Regular
#define BrkPromoSecondaryLgHeadingLineHeight 100%
#define BrkPromoSecondaryLgHeadingFontSize 36
#define BrkPromoSecondaryLgHeadingLetterSpacing -2%
#define BrkPromoSecondaryLgHeadingParagraphSpacing 
#define BrkPromoSecondaryLgHeadingTextCase none
#define BrkPromoSecondaryLgHeadingTextDecoration none
#define BrkPromoSecondaryXlImageHeight 568
#define BrkPromoSecondaryXlGradientHeight 142
#define BrkPromoSecondaryXlPaddingHorizontal 32
#define BrkPromoSecondaryXlPaddingVertical 32
#define BrkPromoSecondaryXlContentGap 16
#define BrkPromoSecondaryXlPretitleMarginBottom 16
#define BrkPromoSecondaryXlPretitleFontFamily Graphik
#define BrkPromoSecondaryXlPretitleFontWeight Bold
#define BrkPromoSecondaryXlPretitleLineHeight 100%
#define BrkPromoSecondaryXlPretitleFontSize 15
#define BrkPromoSecondaryXlPretitleLetterSpacing -2%
#define BrkPromoSecondaryXlPretitleParagraphSpacing 
#define BrkPromoSecondaryXlPretitleTextCase uppercase
#define BrkPromoSecondaryXlPretitleTextDecoration none
#define BrkPromoSecondaryXlHeadingFontFamily Arial
#define BrkPromoSecondaryXlHeadingFontWeight Regular
#define BrkPromoSecondaryXlHeadingLineHeight 100%
#define BrkPromoSecondaryXlHeadingFontSize 40
#define BrkPromoSecondaryXlHeadingLetterSpacing -2%
#define BrkPromoSecondaryXlHeadingParagraphSpacing 
#define BrkPromoSecondaryXlHeadingTextCase none
#define BrkPromoSecondaryXlHeadingTextDecoration none
#define BrkPromoSecondaryXlContentWidth 50%
#define BrkCardHeroStandardHeadingFontColor #2e49d1
#define BrkCardHeroStandardPretitleFontColor #192872
#define BrkCardHeroStandardBodyFontColor #192872
#define BrkCardHeroStandardBackgroundColor #ffffff
#define BrkCardHeroStandardBorderColor #eaedfa
#define BrkCardHeroStandardBoxShadowDefault [object Object]
#define BrkCardHeroStandardBoxShadowHover [object Object]
#define BrkButtonPrimarySmLabelFontFamily Arial
#define BrkButtonPrimarySmLabelFontWeight Bold
#define BrkButtonPrimarySmLabelLineHeight 100%
#define BrkButtonPrimarySmLabelFontSize 13
#define BrkButtonPrimarySmLabelLetterSpacing 2%
#define BrkButtonPrimarySmLabelParagraphSpacing 
#define BrkButtonPrimarySmLabelTextCase none
#define BrkButtonPrimarySmLabelTextDecoration none
#define BrkButtonPrimaryMdLabelFontFamily Arial
#define BrkButtonPrimaryMdLabelFontWeight Bold
#define BrkButtonPrimaryMdLabelLineHeight 100%
#define BrkButtonPrimaryMdLabelFontSize 18
#define BrkButtonPrimaryMdLabelLetterSpacing 2%
#define BrkButtonPrimaryMdLabelParagraphSpacing 
#define BrkButtonPrimaryMdLabelTextCase none
#define BrkButtonPrimaryMdLabelTextDecoration none
#define BrkButtonPrimaryLgLabelFontFamily Arial
#define BrkButtonPrimaryLgLabelFontWeight Bold
#define BrkButtonPrimaryLgLabelLineHeight 100%
#define BrkButtonPrimaryLgLabelFontSize 22
#define BrkButtonPrimaryLgLabelLetterSpacing 2%
#define BrkButtonPrimaryLgLabelParagraphSpacing 
#define BrkButtonPrimaryLgLabelTextCase none
#define BrkButtonPrimaryLgLabelTextDecoration none
#define BrkButtonPrimaryXlLabelFontFamily Arial
#define BrkButtonPrimaryXlLabelFontWeight Bold
#define BrkButtonPrimaryXlLabelLineHeight 100%
#define BrkButtonPrimaryXlLabelFontSize 26
#define BrkButtonPrimaryXlLabelLetterSpacing 2%
#define BrkButtonPrimaryXlLabelParagraphSpacing 
#define BrkButtonPrimaryXlLabelTextCase none
#define BrkButtonPrimaryXlLabelTextDecoration none
#define BrkButtonPrimarySmHeight 30
#define BrkButtonPrimarySmIconSize 8
#define BrkButtonPrimarySmPaddingHorizontal 15
#define BrkButtonPrimarySmIconGap 4
#define BrkButtonPrimarySmBorderRadius 4
#define BrkButtonPrimaryMdHeight 40
#define BrkButtonPrimaryMdIconSize 10
#define BrkButtonPrimaryMdPaddingHorizontal 20
#define BrkButtonPrimaryMdIconGap 6
#define BrkButtonPrimaryMdBorderRadius 6
#define BrkButtonPrimaryLgHeight 50
#define BrkButtonPrimaryLgIconSize 12
#define BrkButtonPrimaryLgPaddingHorizontal 25
#define BrkButtonPrimaryLgIconGap 8
#define BrkButtonPrimaryLgBorderRadius 8
#define BrkButtonPrimaryXlHeight 60
#define BrkButtonPrimaryXlIconSize 14
#define BrkButtonPrimaryXlPaddingHorizontal 30
#define BrkButtonPrimaryXlIconGap 10
#define BrkButtonPrimaryXlBorderRadius 8
#define BrkButtonSecondarySmPaddingHorizontal 15
#define BrkButtonSecondarySmBorderRadius 4
#define BrkButtonSecondarySmHeight 30
#define BrkButtonSecondarySmIconSize 8
#define BrkButtonSecondarySmIconGap 4
#define BrkButtonSecondaryMdPaddingHorizontal 20
#define BrkButtonSecondaryMdBorderRadius 6
#define BrkButtonSecondaryMdHeight 40
#define BrkButtonSecondaryMdIconSize 10
#define BrkButtonSecondaryMdIconGap 6
#define BrkButtonSecondaryLgPaddingHorizontal 25
#define BrkButtonSecondaryLgBorderRadius 8
#define BrkButtonSecondaryLgHeight 50
#define BrkButtonSecondaryLgIconSize 12
#define BrkButtonSecondaryLgIconGap 8
#define BrkButtonSecondaryXlPaddingHorizontal 30
#define BrkButtonSecondaryXlBorderRadius 8
#define BrkButtonSecondaryXlHeight 60
#define BrkButtonSecondaryXlIconSize 14
#define BrkButtonSecondaryXlIconGap 10
#define BrkButtonSecondarySmLabelFontFamily Arial
#define BrkButtonSecondarySmLabelFontWeight Bold
#define BrkButtonSecondarySmLabelLineHeight 100%
#define BrkButtonSecondarySmLabelFontSize 13
#define BrkButtonSecondarySmLabelLetterSpacing 2%
#define BrkButtonSecondarySmLabelParagraphSpacing 
#define BrkButtonSecondarySmLabelTextCase none
#define BrkButtonSecondarySmLabelTextDecoration none
#define BrkButtonSecondaryMdLabelFontFamily Arial
#define BrkButtonSecondaryMdLabelFontWeight Bold
#define BrkButtonSecondaryMdLabelLineHeight 100%
#define BrkButtonSecondaryMdLabelFontSize 18
#define BrkButtonSecondaryMdLabelLetterSpacing 2%
#define BrkButtonSecondaryMdLabelParagraphSpacing 
#define BrkButtonSecondaryMdLabelTextCase none
#define BrkButtonSecondaryMdLabelTextDecoration none
#define BrkButtonSecondaryLgLabelFontFamily Arial
#define BrkButtonSecondaryLgLabelFontWeight Bold
#define BrkButtonSecondaryLgLabelLineHeight 100%
#define BrkButtonSecondaryLgLabelFontSize 22
#define BrkButtonSecondaryLgLabelLetterSpacing 2%
#define BrkButtonSecondaryLgLabelParagraphSpacing 
#define BrkButtonSecondaryLgLabelTextCase none
#define BrkButtonSecondaryLgLabelTextDecoration none
#define BrkButtonSecondaryXlLabelFontFamily Arial
#define BrkButtonSecondaryXlLabelFontWeight Bold
#define BrkButtonSecondaryXlLabelLineHeight 100%
#define BrkButtonSecondaryXlLabelFontSize 26
#define BrkButtonSecondaryXlLabelLetterSpacing 2%
#define BrkButtonSecondaryXlLabelParagraphSpacing 
#define BrkButtonSecondaryXlLabelTextCase none
#define BrkButtonSecondaryXlLabelTextDecoration none
#define BrkPromoSecondaryStandardHeadingFontColor #2e49d1
#define BrkPromoSecondaryStandardPretitleFontColor #192872
#define BrkPromoSecondaryStandardBodyFontColor #192872
#define BrkPromoSecondaryStandardBackgroundColor #ffffff
#define BrkPromoSecondaryStandardBorderColor #eaedfa
#define BrkPromoSecondaryStandardBoxShadowDefault [object Object]
#define BrkPromoSecondaryStandardBoxShadowHover [object Object]
#define BrkPromoSecondaryStandardGradientColor linear-gradient(180deg, #ffffff00 0%, #ffffff 100%)
#define BrkPromoSecondaryInvertedHeadingFontColor #ffffff
#define BrkPromoSecondaryInvertedPretitleFontColor #a6ecff
#define BrkPromoSecondaryInvertedBodyFontColor #ffffff
#define BrkPromoSecondaryInvertedBackgroundColor #121d54
#define BrkPromoSecondaryInvertedBorderColor #eaedfa
#define BrkPromoSecondaryInvertedGradientColor linear-gradient(180deg, #121d5400 0%, #121d54 100%)
#define BrkButtonSecondaryInvertedFontColorDefault #ffffff
#define BrkButtonSecondaryInvertedIconColorDefault #ffffff
#define BrkButtonSecondaryInvertedBackgroundColorDefault transparent
#define BrkButtonSecondaryInvertedBorderColorDefault #ffffff
#define BrkButtonSecondaryInvertedFontColorHover #253aa7
#define BrkButtonSecondaryInvertedIconColorHover #253aa7
#define BrkButtonSecondaryInvertedBackgroundColorHover #eaedfa
#define BrkButtonSecondaryInvertedBorderColorHover #253aa7
#define BrkButtonSecondaryInvertedFontColorFocus #253aa7
#define BrkButtonSecondaryInvertedIconColorFocus #253aa7
#define BrkButtonSecondaryInvertedBackgroundColorFocus #eaedfa
#define BrkButtonSecondaryInvertedBorderColorFocus #253aa7
#define BrkButtonSecondaryInvertedSmBoxShadowDefault [object Object]
#define BrkButtonSecondaryInvertedSmBoxShadowHover [object Object]
#define BrkButtonSecondaryInvertedSmBoxShadowFocus [object Object]
#define BrkButtonSecondaryInvertedMdBoxShadowDefault [object Object]
#define BrkButtonSecondaryInvertedMdBoxShadowHover [object Object]
#define BrkButtonSecondaryInvertedMdBoxShadowFocus [object Object]
#define BrkButtonPrimaryInvertedFontColorDefault #192872
#define BrkButtonPrimaryInvertedIconColorDefault #192872
#define BrkButtonPrimaryInvertedBackgroundColorDefault #ffffff
#define BrkButtonPrimaryInvertedBorderColorDefault transparent
#define BrkButtonPrimaryInvertedFontColorHover #ffffff
#define BrkButtonPrimaryInvertedIconColorHover #ffffff
#define BrkButtonPrimaryInvertedBackgroundColorHover #2e49d1
#define BrkButtonPrimaryInvertedBorderColorHover transparent
#define BrkButtonPrimaryInvertedFontColorFocus #ffffff
#define BrkButtonPrimaryInvertedIconColorFocus #ffffff
#define BrkButtonPrimaryInvertedBackgroundColorFocus #2e49d1
#define BrkButtonPrimaryInvertedBorderColorFocus transparent
#define BrkButtonPrimaryInvertedSmBoxShadowDefault [object Object]
#define BrkButtonPrimaryInvertedSmBoxShadowHover [object Object]
#define BrkButtonPrimaryInvertedSmBoxShadowFocus [object Object]
#define BrkButtonPrimaryInvertedMdBoxShadowDefault [object Object]
#define BrkButtonPrimaryInvertedMdBoxShadowHover [object Object]
#define BrkButtonPrimaryInvertedMdBoxShadowFocus [object Object]
#define BrkButtonSecondaryStandardSmBoxShadowDefault [object Object]
#define BrkButtonSecondaryStandardSmBoxShadowHover [object Object]
#define BrkButtonSecondaryStandardSmBoxShadowFocus [object Object]
#define BrkButtonSecondaryStandardFontColorDefault #192872
#define BrkButtonSecondaryStandardIconColorDefault #192872
#define BrkButtonSecondaryStandardBackgroundColorDefault transparent
#define BrkButtonSecondaryStandardBorderColorDefault #192872
#define BrkButtonSecondaryStandardFontColorHover #253aa7
#define BrkButtonSecondaryStandardIconColorHover #253aa7
#define BrkButtonSecondaryStandardBackgroundColorHover #eaedfa
#define BrkButtonSecondaryStandardBorderColorHover #253aa7
#define BrkButtonSecondaryStandardFontColorFocus #253aa7
#define BrkButtonSecondaryStandardIconColorFocus #253aa7
#define BrkButtonSecondaryStandardBackgroundColorFocus #eaedfa
#define BrkButtonSecondaryStandardBorderColorFocus #253aa7
#define BrkButtonSecondaryStandardMdBoxShadowDefault [object Object]
#define BrkButtonSecondaryStandardMdBoxShadowHover [object Object]
#define BrkButtonSecondaryStandardMdBoxShadowFocus [object Object]
#define BrkButtonPrimaryStandardSmBoxShadowDefault [object Object]
#define BrkButtonPrimaryStandardSmBoxShadowHover [object Object]
#define BrkButtonPrimaryStandardSmBoxShadowFocus [object Object]
#define BrkButtonPrimaryStandardMdBoxShadowDefault [object Object]
#define BrkButtonPrimaryStandardMdBoxShadowHover [object Object]
#define BrkButtonPrimaryStandardMdBoxShadowFocus [object Object]
#define BrkButtonPrimaryStandardFontColorDefault #ffffff
#define BrkButtonPrimaryStandardIconColorDefault #ffffff
#define BrkButtonPrimaryStandardBackgroundColorDefault #192872
#define BrkButtonPrimaryStandardBorderColorDefault transparent
#define BrkButtonPrimaryStandardFontColorHover #ffffff
#define BrkButtonPrimaryStandardIconColorHover #ffffff
#define BrkButtonPrimaryStandardBackgroundColorHover #2e49d1
#define BrkButtonPrimaryStandardBorderColorHover transparent
#define BrkButtonPrimaryStandardFontColorFocus #ffffff
#define BrkButtonPrimaryStandardIconColorFocus #ffffff
#define BrkButtonPrimaryStandardBackgroundColorFocus #2e49d1
#define BrkButtonPrimaryStandardBorderColorFocus transparent
#define BrkPromoPrimarySmPaddingHorizontal 10
#define BrkPromoPrimarySmPaddingVertical 16
#define BrkPromoPrimarySmContentGap 12
#define BrkPromoPrimarySmPretitleMarginBottom 4
#define BrkPromoPrimarySmBodyMarginTop 8
#define BrkPromoPrimarySmImageHeight 172
#define BrkPromoPrimarySmPretitleFontFamily Graphik
#define BrkPromoPrimarySmPretitleFontWeight Bold
#define BrkPromoPrimarySmPretitleLineHeight 10
#define BrkPromoPrimarySmPretitleFontSize 10
#define BrkPromoPrimarySmPretitleLetterSpacing -2%
#define BrkPromoPrimarySmPretitleParagraphSpacing 
#define BrkPromoPrimarySmPretitleTextCase uppercase
#define BrkPromoPrimarySmPretitleTextDecoration none
#define BrkPromoPrimarySmHeadingFontFamily Arial
#define BrkPromoPrimarySmHeadingFontWeight Regular
#define BrkPromoPrimarySmHeadingLineHeight 100%
#define BrkPromoPrimarySmHeadingFontSize 26
#define BrkPromoPrimarySmHeadingLetterSpacing -2%
#define BrkPromoPrimarySmHeadingParagraphSpacing 
#define BrkPromoPrimarySmHeadingTextCase none
#define BrkPromoPrimarySmHeadingTextDecoration none
#define BrkPromoPrimarySmBodyFontFamily Arial
#define BrkPromoPrimarySmBodyFontWeight Regular
#define BrkPromoPrimarySmBodyLineHeight 115%
#define BrkPromoPrimarySmBodyFontSize 14
#define BrkPromoPrimarySmBodyLetterSpacing 0%
#define BrkPromoPrimarySmBodyParagraphSpacing 
#define BrkPromoPrimarySmBodyTextCase none
#define BrkPromoPrimarySmBodyTextDecoration none
#define BrkPromoPrimarySmGradientHeight 43
#define BrkPromoPrimaryMdPaddingHorizontal 24
#define BrkPromoPrimaryMdPaddingVertical 24
#define BrkPromoPrimaryMdContentGap 16
#define BrkPromoPrimaryMdPretitleMarginBottom 6
#define BrkPromoPrimaryMdBodyMarginTop 8
#define BrkPromoPrimaryMdImageHeight 270
#define BrkPromoPrimaryMdPretitleFontFamily Graphik
#define BrkPromoPrimaryMdPretitleFontWeight Bold
#define BrkPromoPrimaryMdPretitleLineHeight 12
#define BrkPromoPrimaryMdPretitleFontSize 12
#define BrkPromoPrimaryMdPretitleLetterSpacing -2%
#define BrkPromoPrimaryMdPretitleParagraphSpacing 
#define BrkPromoPrimaryMdPretitleTextCase uppercase
#define BrkPromoPrimaryMdPretitleTextDecoration none
#define BrkPromoPrimaryMdHeadingFontFamily Arial
#define BrkPromoPrimaryMdHeadingFontWeight Regular
#define BrkPromoPrimaryMdHeadingLineHeight 100%
#define BrkPromoPrimaryMdHeadingFontSize 30
#define BrkPromoPrimaryMdHeadingLetterSpacing -2%
#define BrkPromoPrimaryMdHeadingParagraphSpacing 
#define BrkPromoPrimaryMdHeadingTextCase none
#define BrkPromoPrimaryMdHeadingTextDecoration none
#define BrkPromoPrimaryMdBodyFontFamily Arial
#define BrkPromoPrimaryMdBodyFontWeight Regular
#define BrkPromoPrimaryMdBodyLineHeight 115%
#define BrkPromoPrimaryMdBodyFontSize 18
#define BrkPromoPrimaryMdBodyLetterSpacing 2%
#define BrkPromoPrimaryMdBodyParagraphSpacing 
#define BrkPromoPrimaryMdBodyTextCase none
#define BrkPromoPrimaryMdBodyTextDecoration none
#define BrkPromoPrimaryMdGradientHeight 67.5
#define BrkPromoPrimaryLgPaddingHorizontal 24
#define BrkPromoPrimaryLgPaddingVertical 24
#define BrkPromoPrimaryLgContentGap 24
#define BrkPromoPrimaryLgPretitleMarginBottom 10
#define BrkPromoPrimaryLgBodyMarginTop 10
#define BrkPromoPrimaryLgImageHeight 300
#define BrkPromoPrimaryLgPretitleFontFamily Graphik
#define BrkPromoPrimaryLgPretitleFontWeight Bold
#define BrkPromoPrimaryLgPretitleLineHeight 14
#define BrkPromoPrimaryLgPretitleFontSize 14
#define BrkPromoPrimaryLgPretitleLetterSpacing -2%
#define BrkPromoPrimaryLgPretitleParagraphSpacing 
#define BrkPromoPrimaryLgPretitleTextCase uppercase
#define BrkPromoPrimaryLgPretitleTextDecoration none
#define BrkPromoPrimaryLgHeadingFontFamily Arial
#define BrkPromoPrimaryLgHeadingFontWeight Regular
#define BrkPromoPrimaryLgHeadingLineHeight 100%
#define BrkPromoPrimaryLgHeadingFontSize 36
#define BrkPromoPrimaryLgHeadingLetterSpacing -2%
#define BrkPromoPrimaryLgHeadingParagraphSpacing 
#define BrkPromoPrimaryLgHeadingTextCase none
#define BrkPromoPrimaryLgHeadingTextDecoration none
#define BrkPromoPrimaryLgBodyFontFamily Arial
#define BrkPromoPrimaryLgBodyFontWeight Regular
#define BrkPromoPrimaryLgBodyLineHeight 115%
#define BrkPromoPrimaryLgBodyFontSize 22
#define BrkPromoPrimaryLgBodyLetterSpacing 2%
#define BrkPromoPrimaryLgBodyParagraphSpacing 
#define BrkPromoPrimaryLgBodyTextCase none
#define BrkPromoPrimaryLgBodyTextDecoration none
#define BrkPromoPrimaryLgGradientHeight 75
#define BrkPromoPrimaryXlPaddingHorizontal 32
#define BrkPromoPrimaryXlPaddingVertical 32
#define BrkPromoPrimaryXlContentGap 16
#define BrkPromoPrimaryXlPretitleMarginBottom 4
#define BrkPromoPrimaryXlBodyMarginTop 12
#define BrkPromoPrimaryXlImageHeight 568
#define BrkPromoPrimaryXlPretitleFontFamily Graphik
#define BrkPromoPrimaryXlPretitleFontWeight Bold
#define BrkPromoPrimaryXlPretitleLineHeight 110%
#define BrkPromoPrimaryXlPretitleFontSize 14
#define BrkPromoPrimaryXlPretitleLetterSpacing -2%
#define BrkPromoPrimaryXlPretitleParagraphSpacing 
#define BrkPromoPrimaryXlPretitleTextCase uppercase
#define BrkPromoPrimaryXlPretitleTextDecoration none
#define BrkPromoPrimaryXlHeadingFontFamily Arial
#define BrkPromoPrimaryXlHeadingFontWeight Regular
#define BrkPromoPrimaryXlHeadingLineHeight 100%
#define BrkPromoPrimaryXlHeadingFontSize 48
#define BrkPromoPrimaryXlHeadingLetterSpacing -2%
#define BrkPromoPrimaryXlHeadingParagraphSpacing 
#define BrkPromoPrimaryXlHeadingTextCase none
#define BrkPromoPrimaryXlHeadingTextDecoration none
#define BrkPromoPrimaryXlBodyFontFamily Arial
#define BrkPromoPrimaryXlBodyFontWeight Regular
#define BrkPromoPrimaryXlBodyLineHeight 115%
#define BrkPromoPrimaryXlBodyFontSize 24
#define BrkPromoPrimaryXlBodyLetterSpacing 2%
#define BrkPromoPrimaryXlBodyParagraphSpacing 
#define BrkPromoPrimaryXlBodyTextCase none
#define BrkPromoPrimaryXlBodyTextDecoration none
#define BrkPromoPrimaryXlGradientHeight 142
#define BrkPromoPrimaryXlContentWidth 40%
#define BrkPromoPrimaryXlContentMaxWidth 470
#define BrkPromoPrimary2xlPaddingHorizontal 32
#define BrkPromoPrimary2xlPaddingVertical 32
#define BrkPromoPrimary2xlContentGap 16
#define BrkPromoPrimary2xlPretitleMarginBottom 4
#define BrkPromoPrimary2xlBodyMarginTop 12
#define BrkTemplateSmSubheadingFontFamily Arial
#define BrkTemplateSmSubheadingFontWeight Regular
#define BrkTemplateSmSubheadingLineHeight 100%
#define BrkTemplateSmSubheadingFontSize 24
#define BrkTemplateSmSubheadingLetterSpacing -2%
#define BrkTemplateSmSubheadingParagraphSpacing 
#define BrkTemplateSmSubheadingTextCase none
#define BrkTemplateSmSubheadingTextDecoration none
#define BrkTemplateSmContentGapHorizontal 16
#define BrkTemplateSmContentGapVertical 24
#define BrkTemplateSmContentGapExtra 16
#define BrkTemplateSmMarginHorizontal 32
#define BrkTemplateSmMarginTop 0
#define BrkTemplateSmMarginBottom 48
#define BrkPromoPrimaryInvertedHeadingFontColor #ffffff
#define BrkPromoPrimaryInvertedPretitleFontColor #a6ecff
#define BrkPromoPrimaryInvertedBodyFontColor #ffffff
#define BrkPromoPrimaryInvertedBackgroundColor #121d54
#define BrkPromoPrimaryInvertedBorderColor #eaedfa
#define BrkPromoPrimaryInvertedGradientColor linear-gradient(180deg, #121d5400 0%, #121d54 100%)
#define BrkPromoPrimaryStandardHeadingFontColor #2e49d1
#define BrkPromoPrimaryStandardPretitleFontColor #192872
#define BrkPromoPrimaryStandardBodyFontColor #192872
#define BrkPromoPrimaryStandardBackgroundColor #ffffff
#define BrkPromoPrimaryStandardBorderColor #eaedfa
#define BrkPromoPrimaryStandardGradientColor linear-gradient(180deg, #ffffff00 0%, #ffffff 100%)
#define BrkPageStandardSubheadingFontColor #121d54
#define BrkPromoTertiaryStandardHeadingFontColor #2e49d1
#define BrkPromoTertiaryStandardPretitleFontColor #192872
#define BrkPromoTertiaryStandardBodyFontColor #192872
#define BrkPromoTertiaryStandardBackgroundColor #121d54
#define BrkPromoTertiaryStandardBorderColor #eaedfa
#define BrkPromoTertiaryStandardGradientColor linear-gradient(180deg, #121d5400 0%, #121d54 100%)
#define BrkPromoTertiaryStandardFrameColor #ffffff
#define BrkPromoTertiaryInvertedHeadingFontColor #ffffff
#define BrkPromoTertiaryInvertedPretitleFontColor #a6ecff
#define BrkPromoTertiaryInvertedBodyFontColor #ffffff
#define BrkPromoTertiaryInvertedBackgroundColor #ffffff
#define BrkPromoTertiaryInvertedBorderColor #eaedfa
#define BrkPromoTertiaryInvertedGradientColor linear-gradient(180deg, #ffffff00 0%, #ffffff 100%)
#define BrkPromoTertiaryInvertedFrameColor #192872
#define BrkPromoTertiarySmPretitleFontFamily Graphik
#define BrkPromoTertiarySmPretitleFontWeight Bold
#define BrkPromoTertiarySmPretitleLineHeight 100%
#define BrkPromoTertiarySmPretitleFontSize 10
#define BrkPromoTertiarySmPretitleLetterSpacing -2%
#define BrkPromoTertiarySmPretitleParagraphSpacing 
#define BrkPromoTertiarySmPretitleTextCase uppercase
#define BrkPromoTertiarySmPretitleTextDecoration none
#define BrkPromoTertiarySmHeadingFontFamily Arial
#define BrkPromoTertiarySmHeadingFontWeight Regular
#define BrkPromoTertiarySmHeadingLineHeight 100%
#define BrkPromoTertiarySmHeadingFontSize 26
#define BrkPromoTertiarySmHeadingLetterSpacing -2%
#define BrkPromoTertiarySmHeadingParagraphSpacing 
#define BrkPromoTertiarySmHeadingTextCase none
#define BrkPromoTertiarySmHeadingTextDecoration none
#define BrkPromoTertiarySmPaddingHorizontal 10
#define BrkPromoTertiarySmPaddingVertical 16
#define BrkPromoTertiarySmFramePaddingHorizontal 10
#define BrkPromoTertiarySmFramePaddingVertical 10
#define BrkPromoTertiarySmContentGap 12
#define BrkPromoTertiarySmPretitleMarginBottom 4
#define BrkPromoTertiarySmImageHeight 172
#define BrkPromoTertiarySmGradientHeight 43
#define BrkPromoTertiaryMdPaddingHorizontal 16
#define BrkPromoTertiaryMdPaddingVertical 16
#define BrkPromoTertiaryMdFramePaddingHorizontal 12
#define BrkPromoTertiaryMdFramePaddingVertical 12
#define BrkPromoTertiaryMdPretitleFontFamily Graphik
#define BrkPromoTertiaryMdPretitleFontWeight Bold
#define BrkPromoTertiaryMdPretitleLineHeight 100%
#define BrkPromoTertiaryMdPretitleFontSize 12
#define BrkPromoTertiaryMdPretitleLetterSpacing -2%
#define BrkPromoTertiaryMdPretitleParagraphSpacing 
#define BrkPromoTertiaryMdPretitleTextCase uppercase
#define BrkPromoTertiaryMdPretitleTextDecoration none
#define BrkPromoTertiaryMdHeadingFontFamily Arial
#define BrkPromoTertiaryMdHeadingFontWeight Regular
#define BrkPromoTertiaryMdHeadingLineHeight 100%
#define BrkPromoTertiaryMdHeadingFontSize 30
#define BrkPromoTertiaryMdHeadingLetterSpacing -2%
#define BrkPromoTertiaryMdHeadingParagraphSpacing 
#define BrkPromoTertiaryMdHeadingTextCase none
#define BrkPromoTertiaryMdHeadingTextDecoration none
#define BrkPromoTertiaryMdContentGap 8
#define BrkPromoTertiaryMdPretitleMarginBottom 6
#define BrkPromoTertiaryMdImageHeight 270
#define BrkPromoTertiaryMdGradientHeight 67.5
#define BrkPromoTertiaryLgPaddingHorizontal 24
#define BrkPromoTertiaryLgPaddingVertical 24
#define BrkPromoTertiaryLgFramePaddingHorizontal 20
#define BrkPromoTertiaryLgFramePaddingVertical 20
#define BrkPromoTertiaryLgPretitleFontFamily Graphik
#define BrkPromoTertiaryLgPretitleFontWeight Bold
#define BrkPromoTertiaryLgPretitleLineHeight 100%
#define BrkPromoTertiaryLgPretitleFontSize 12
#define BrkPromoTertiaryLgPretitleLetterSpacing -2%
#define BrkPromoTertiaryLgPretitleParagraphSpacing 
#define BrkPromoTertiaryLgPretitleTextCase uppercase
#define BrkPromoTertiaryLgPretitleTextDecoration none
#define BrkPromoTertiaryLgHeadingFontFamily Arial
#define BrkPromoTertiaryLgHeadingFontWeight Regular
#define BrkPromoTertiaryLgHeadingLineHeight 100%
#define BrkPromoTertiaryLgHeadingFontSize 36
#define BrkPromoTertiaryLgHeadingLetterSpacing -2%
#define BrkPromoTertiaryLgHeadingParagraphSpacing 
#define BrkPromoTertiaryLgHeadingTextCase none
#define BrkPromoTertiaryLgHeadingTextDecoration none
#define BrkPromoTertiaryLgContentGap 8
#define BrkPromoTertiaryLgPretitleMarginBottom 6
#define BrkPromoTertiaryLgImageHeight 300
#define BrkPromoTertiaryLgGradientHeight 75
#define BrkPromoTertiaryXlPaddingHorizontal 32
#define BrkPromoTertiaryXlPaddingVertical 32
#define BrkPromoTertiaryXlFramePaddingHorizontal 10
#define BrkPromoTertiaryXlFramePaddingVertical 10
#define BrkPromoTertiaryXlPretitleFontFamily Graphik
#define BrkPromoTertiaryXlPretitleFontWeight Bold
#define BrkPromoTertiaryXlPretitleLineHeight 100%
#define BrkPromoTertiaryXlPretitleFontSize 14
#define BrkPromoTertiaryXlPretitleLetterSpacing -2%
#define BrkPromoTertiaryXlPretitleParagraphSpacing 
#define BrkPromoTertiaryXlPretitleTextCase uppercase
#define BrkPromoTertiaryXlPretitleTextDecoration none
#define BrkPromoTertiaryXlHeadingFontFamily Arial
#define BrkPromoTertiaryXlHeadingFontWeight Regular
#define BrkPromoTertiaryXlHeadingLineHeight 100%
#define BrkPromoTertiaryXlHeadingFontSize 48
#define BrkPromoTertiaryXlHeadingLetterSpacing -2%
#define BrkPromoTertiaryXlHeadingParagraphSpacing 
#define BrkPromoTertiaryXlHeadingTextCase none
#define BrkPromoTertiaryXlHeadingTextDecoration none
#define BrkPromoTertiaryXlContentGap 30
#define BrkPromoTertiaryXlPretitleMarginBottom 6
#define BrkPromoTertiaryXlGradientHeight 142
#define BrkPromoTertiaryXlImageHeight 568
#define BrkPromoTertiaryXlContentWidth 40%
#define BrkPromoTertiaryXlContentMaxWidth 470

