
//
// tokens.h
//

// Do not edit directly
// Generated on Fri, 14 Oct 2022 16:50:47 GMT


#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

#define BrkInteractiveStandardOutlineColorFocus #c9ff00
#define BrkInteractiveInvertedOutlineColorFocus #c9ff00
#define BrkInteractiveOutlineOffset 5
#define BrkInteractiveOutlineBorderRadius 0
#define BrkButtonTertiaryStandardSmBoxShadowDefault [object Object]
#define BrkButtonTertiaryStandardSmBoxShadowHover [object Object]
#define BrkButtonTertiaryStandardSmBoxShadowFocus [object Object]
#define BrkButtonTertiaryStandardFontColorDefault #000000
#define BrkButtonTertiaryStandardIconFillDefault #000000
#define BrkButtonTertiaryStandardBackgroundColorDefault #ffffff
#define BrkButtonTertiaryStandardBorderColorDefault transparent
#define BrkButtonTertiaryStandardFontColorHover #000000
#define BrkButtonTertiaryStandardIconFillHover #000000
#define BrkButtonTertiaryStandardBackgroundColorHover #c9ff00
#define BrkButtonTertiaryStandardBorderColorHover transparent
#define BrkButtonTertiaryStandardFontColorFocus #000000
#define BrkButtonTertiaryStandardIconFillFocus #000000
#define BrkButtonTertiaryStandardBackgroundColorFocus #c9ff00
#define BrkButtonTertiaryStandardBorderColorFocus transparent
#define BrkButtonTertiaryInvertedSmBoxShadowDefault [object Object]
#define BrkButtonTertiaryInvertedSmBoxShadowHover [object Object]
#define BrkButtonTertiaryInvertedSmBoxShadowFocus [object Object]
#define BrkButtonTertiaryInvertedFontColorDefault #000000
#define BrkButtonTertiaryInvertedIconFillDefault #000000
#define BrkButtonTertiaryInvertedBackgroundColorDefault #ffffff
#define BrkButtonTertiaryInvertedBorderColorDefault transparent
#define BrkButtonTertiaryInvertedFontColorHover #000000
#define BrkButtonTertiaryInvertedIconFillHover #000000
#define BrkButtonTertiaryInvertedBackgroundColorHover #c9ff00
#define BrkButtonTertiaryInvertedBorderColorHover transparent
#define BrkButtonTertiaryInvertedFontColorFocus #000000
#define BrkButtonTertiaryInvertedIconFillFocus #000000
#define BrkButtonTertiaryInvertedBackgroundColorFocus #c9ff00
#define BrkButtonTertiaryInvertedBorderColorFocus transparent
#define BrkButtonPrimaryBorderWidth 0
#define BrkButtonSecondaryBorderWidth 0
#define BrkButtonTertiaryBorderWidth 0
#define BrkButtonOpacityDisabled 50%
#define BrkinteractiveOutlineWidth 2
#define BrkButtonTertiarySmLabelFontFamily Roboto Condensed
#define BrkButtonTertiarySmLabelFontWeight Bold
#define BrkButtonTertiarySmLabelLineHeight 85%
#define BrkButtonTertiarySmLabelFontSize 10
#define BrkButtonTertiarySmLabelLetterSpacing 2%
#define BrkButtonTertiarySmLabelParagraphSpacing 
#define BrkButtonTertiarySmLabelTextDecoration none
#define BrkButtonTertiarySmLabelTextCase uppercase
#define BrkButtonTertiaryMdLabelFontFamily Roboto Condensed
#define BrkButtonTertiaryMdLabelFontWeight Bold
#define BrkButtonTertiaryMdLabelLineHeight 85%
#define BrkButtonTertiaryMdLabelFontSize 14
#define BrkButtonTertiaryMdLabelLetterSpacing 2%
#define BrkButtonTertiaryMdLabelParagraphSpacing 
#define BrkButtonTertiaryMdLabelTextDecoration none
#define BrkButtonTertiaryMdLabelTextCase uppercase
#define BrkButtonTertiaryLgLabelFontFamily Roboto Condensed
#define BrkButtonTertiaryLgLabelFontWeight Bold
#define BrkButtonTertiaryLgLabelLineHeight 85%
#define BrkButtonTertiaryLgLabelFontSize 18
#define BrkButtonTertiaryLgLabelLetterSpacing 2%
#define BrkButtonTertiaryLgLabelParagraphSpacing 
#define BrkButtonTertiaryLgLabelTextDecoration none
#define BrkButtonTertiaryLgLabelTextCase uppercase
#define BrkButtonTertiaryXlLabelFontFamily Roboto Condensed
#define BrkButtonTertiaryXlLabelFontWeight Bold
#define BrkButtonTertiaryXlLabelLineHeight 85%
#define BrkButtonTertiaryXlLabelFontSize 22
#define BrkButtonTertiaryXlLabelLetterSpacing 2%
#define BrkButtonTertiaryXlLabelParagraphSpacing 
#define BrkButtonTertiaryXlLabelTextDecoration none
#define BrkButtonTertiaryXlLabelTextCase uppercase
#define BrkButtonTertiarySmPaddingHorizontal 20
#define BrkButtonTertiarySmBorderRadius 0
#define BrkButtonTertiarySmHeight 30
#define BrkButtonTertiarySmIconSize 8
#define BrkButtonTertiarySmIconGap 4
#define BrkButtonTertiaryMdPaddingHorizontal 22
#define BrkButtonTertiaryMdBorderRadius 0
#define BrkButtonTertiaryMdHeight 35
#define BrkButtonTertiaryMdIconSize 10
#define BrkButtonTertiaryMdIconGap 6
#define BrkButtonTertiaryLgPaddingHorizontal 30
#define BrkButtonTertiaryLgBorderRadius 0
#define BrkButtonTertiaryLgHeight 40
#define BrkButtonTertiaryLgIconSize 12
#define BrkButtonTertiaryLgIconGap 8
#define BrkButtonTertiaryXlPaddingHorizontal 36
#define BrkButtonTertiaryXlBorderRadius 0
#define BrkButtonTertiaryXlHeight 45
#define BrkButtonTertiaryXlIconSize 14
#define BrkButtonTertiaryXlIconGap 10
#define BrkJackpotHeroSmHeadingFontFamily Roboto Condensed
#define BrkJackpotHeroSmHeadingFontWeight Bold
#define BrkJackpotHeroSmHeadingLineHeight 100%
#define BrkJackpotHeroSmHeadingFontSize 9
#define BrkJackpotHeroSmHeadingLetterSpacing 2%
#define BrkJackpotHeroSmHeadingParagraphSpacing 
#define BrkJackpotHeroSmHeadingTextDecoration none
#define BrkJackpotHeroSmHeadingTextCase uppercase
#define BrkJackpotHeroSmBodyFontFamily Roboto Condensed
#define BrkJackpotHeroSmBodyFontWeight Bold
#define BrkJackpotHeroSmBodyLineHeight 100%
#define BrkJackpotHeroSmBodyFontSize 12
#define BrkJackpotHeroSmBodyLetterSpacing 0%
#define BrkJackpotHeroSmBodyParagraphSpacing 
#define BrkJackpotHeroSmBodyTextDecoration none
#define BrkJackpotHeroSmBodyTextCase uppercase
#define BrkJackpotHeroSmContentGap 16
#define BrkJackpotHeroSmPaddingHorizontal 10
#define BrkJackpotHeroSmAmountDigitMargin 1
#define BrkJackpotHeroSmAmountGroupMargin 5
#define BrkJackpotHeroSmHeight 36
#define BrkJackpotHeroSmAmountDigitHeight 20
#define BrkJackpotHeroSmAmountDigitWidth 12
#define BrkJackpotHeroMdHeadingFontFamily Roboto Condensed
#define BrkJackpotHeroMdHeadingFontWeight Regular
#define BrkJackpotHeroMdHeadingLineHeight 100%
#define BrkJackpotHeroMdHeadingFontSize 16
#define BrkJackpotHeroMdHeadingLetterSpacing 2%
#define BrkJackpotHeroMdHeadingParagraphSpacing 
#define BrkJackpotHeroMdHeadingTextDecoration none
#define BrkJackpotHeroMdHeadingTextCase uppercase
#define BrkJackpotHeroMdBodyFontFamily Roboto Condensed
#define BrkJackpotHeroMdBodyFontWeight Regular
#define BrkJackpotHeroMdBodyLineHeight 100%
#define BrkJackpotHeroMdBodyFontSize 20
#define BrkJackpotHeroMdBodyLetterSpacing 0%
#define BrkJackpotHeroMdBodyParagraphSpacing 
#define BrkJackpotHeroMdBodyTextDecoration none
#define BrkJackpotHeroMdBodyTextCase uppercase
#define BrkJackpotHeroMdContentGap 16
#define BrkJackpotHeroMdPaddingHorizontal 16
#define BrkJackpotHeroMdAmountDigitMargin 2
#define BrkJackpotHeroMdAmountGroupMargin 6
#define BrkJackpotHeroMdHeight 60
#define BrkJackpotHeroMdAmountDigitHeight 30
#define BrkJackpotHeroMdAmountDigitWidth 18
#define BrkJackpotHeroLgHeadingFontFamily Roboto Condensed
#define BrkJackpotHeroLgHeadingFontWeight Regular
#define BrkJackpotHeroLgHeadingLineHeight 100%
#define BrkJackpotHeroLgHeadingFontSize 20
#define BrkJackpotHeroLgHeadingLetterSpacing 2%
#define BrkJackpotHeroLgHeadingParagraphSpacing 
#define BrkJackpotHeroLgHeadingTextDecoration none
#define BrkJackpotHeroLgHeadingTextCase uppercase
#define BrkJackpotHeroLgBodyFontFamily Roboto Condensed
#define BrkJackpotHeroLgBodyFontWeight Regular
#define BrkJackpotHeroLgBodyLineHeight 100%
#define BrkJackpotHeroLgBodyFontSize 24
#define BrkJackpotHeroLgBodyLetterSpacing 0%
#define BrkJackpotHeroLgBodyParagraphSpacing 
#define BrkJackpotHeroLgBodyTextDecoration none
#define BrkJackpotHeroLgBodyTextCase uppercase
#define BrkJackpotHeroLgContentGap 24
#define BrkJackpotHeroLgPaddingHorizontal 24
#define BrkJackpotHeroLgAmountDigitMargin 3
#define BrkJackpotHeroLgAmountGroupMargin 8
#define BrkJackpotHeroLgHeight 72
#define BrkJackpotHeroLgAmountDigitHeight 40
#define BrkJackpotHeroLgAmountDigitWidth 24
#define BrkJackpotHeroXlHeadingFontFamily Roboto Condensed
#define BrkJackpotHeroXlHeadingFontWeight Regular
#define BrkJackpotHeroXlHeadingLineHeight 100%
#define BrkJackpotHeroXlHeadingFontSize 22
#define BrkJackpotHeroXlHeadingLetterSpacing 2%
#define BrkJackpotHeroXlHeadingParagraphSpacing 
#define BrkJackpotHeroXlHeadingTextDecoration none
#define BrkJackpotHeroXlHeadingTextCase uppercase
#define BrkJackpotHeroXlBodyFontFamily Roboto Condensed
#define BrkJackpotHeroXlBodyFontWeight Regular
#define BrkJackpotHeroXlBodyLineHeight 100%
#define BrkJackpotHeroXlBodyFontSize 28
#define BrkJackpotHeroXlBodyLetterSpacing 0%
#define BrkJackpotHeroXlBodyParagraphSpacing 
#define BrkJackpotHeroXlBodyTextDecoration none
#define BrkJackpotHeroXlBodyTextCase uppercase
#define BrkJackpotHeroXlPaddingHorizontal 24
#define BrkJackpotHeroXlContentGap 24
#define BrkJackpotHeroXlAmountDigitMargin 4
#define BrkJackpotHeroXlAmountGroupMargin 10
#define BrkJackpotHeroXlHeight 72
#define BrkJackpotHeroXlAmountDigitHeight 44
#define BrkJackpotHeroXlAmountDigitWidth 28
#define BrkJackpotHeroAmountDigitBorderRadius 0
#define BrkJackpotHeroAmountDigitBorderWidth 1
#define BrkJackpotHeroStandardHeadingFontColor #c9ff00
#define BrkJackpotHeroStandardBodyFontColor #ffffff
#define BrkJackpotHeroStandardBodyBoxBackgroundColor #000000
#define BrkJackpotHeroStandardBodyBoxBorderColor #ffffff
#define BrkJackpotHeroStandardBackgroundColor #000000
#define BrkJackpotHeroStandardSymbolFontColor #ffffff
#define BrkCardHeroSmPretitleFontFamily Roboto Condensed
#define BrkCardHeroSmPretitleFontWeight Regular
#define BrkCardHeroSmPretitleLineHeight 9
#define BrkCardHeroSmPretitleFontSize 9
#define BrkCardHeroSmPretitleLetterSpacing 2%
#define BrkCardHeroSmPretitleParagraphSpacing 
#define BrkCardHeroSmPretitleTextDecoration none
#define BrkCardHeroSmPretitleTextCase uppercase
#define BrkCardHeroSmHeadingFontFamily Roboto Condensed
#define BrkCardHeroSmHeadingFontWeight Bold
#define BrkCardHeroSmHeadingLineHeight 100%
#define BrkCardHeroSmHeadingFontSize 14
#define BrkCardHeroSmHeadingLetterSpacing 0%
#define BrkCardHeroSmHeadingParagraphSpacing 
#define BrkCardHeroSmHeadingTextDecoration none
#define BrkCardHeroSmHeadingTextCase uppercase
#define BrkCardHeroSmBodyFontFamily Roboto Condensed
#define BrkCardHeroSmBodyFontWeight Regular
#define BrkCardHeroSmBodyLineHeight 85%
#define BrkCardHeroSmBodyFontSize 8
#define BrkCardHeroSmBodyLetterSpacing 2%
#define BrkCardHeroSmBodyParagraphSpacing 
#define BrkCardHeroSmBodyTextDecoration none
#define BrkCardHeroSmBodyTextCase uppercase
#define BrkCardHeroSmImageHeight 180
#define BrkCardHeroSmPaddingHorizontal 10
#define BrkCardHeroSmPaddingVertical 10
#define BrkCardHeroSmHeadingMarginVertical 4
#define BrkCardHeroSmContentGap 16
#define BrkCardHeroMdPretitleFontFamily Roboto Condensed
#define BrkCardHeroMdPretitleFontWeight Regular
#define BrkCardHeroMdPretitleLineHeight 12
#define BrkCardHeroMdPretitleFontSize 12
#define BrkCardHeroMdPretitleLetterSpacing 2%
#define BrkCardHeroMdPretitleParagraphSpacing 
#define BrkCardHeroMdPretitleTextDecoration none
#define BrkCardHeroMdPretitleTextCase uppercase
#define BrkCardHeroMdHeadingFontFamily Roboto Condensed
#define BrkCardHeroMdHeadingFontWeight Bold
#define BrkCardHeroMdHeadingLineHeight 100%
#define BrkCardHeroMdHeadingFontSize 24
#define BrkCardHeroMdHeadingLetterSpacing 0%
#define BrkCardHeroMdHeadingParagraphSpacing 
#define BrkCardHeroMdHeadingTextDecoration none
#define BrkCardHeroMdHeadingTextCase uppercase
#define BrkCardHeroMdBodyFontFamily Roboto Condensed
#define BrkCardHeroMdBodyFontWeight Regular
#define BrkCardHeroMdBodyLineHeight 85%
#define BrkCardHeroMdBodyFontSize 13
#define BrkCardHeroMdBodyLetterSpacing 2%
#define BrkCardHeroMdBodyParagraphSpacing 
#define BrkCardHeroMdBodyTextDecoration none
#define BrkCardHeroMdBodyTextCase uppercase
#define BrkCardHeroMdImageHeight 270
#define BrkCardHeroMdPaddingHorizontal 16
#define BrkCardHeroMdPaddingVertical 16
#define BrkCardHeroMdHeadingMarginVertical 4
#define BrkCardHeroMdContentGap 24
#define BrkCardHeroLgPretitleFontFamily Roboto Condensed
#define BrkCardHeroLgPretitleFontWeight Regular
#define BrkCardHeroLgPretitleLineHeight 16
#define BrkCardHeroLgPretitleFontSize 16
#define BrkCardHeroLgPretitleLetterSpacing 2%
#define BrkCardHeroLgPretitleParagraphSpacing 
#define BrkCardHeroLgPretitleTextDecoration none
#define BrkCardHeroLgPretitleTextCase uppercase
#define BrkCardHeroLgHeadingFontFamily Roboto Condensed
#define BrkCardHeroLgHeadingFontWeight Bold
#define BrkCardHeroLgHeadingLineHeight 100%
#define BrkCardHeroLgHeadingFontSize 28
#define BrkCardHeroLgHeadingLetterSpacing 0%
#define BrkCardHeroLgHeadingParagraphSpacing 
#define BrkCardHeroLgHeadingTextDecoration none
#define BrkCardHeroLgHeadingTextCase uppercase
#define BrkCardHeroLgBodyFontFamily Roboto Condensed
#define BrkCardHeroLgBodyFontWeight Regular
#define BrkCardHeroLgBodyLineHeight 85%
#define BrkCardHeroLgBodyFontSize 14
#define BrkCardHeroLgBodyLetterSpacing 2%
#define BrkCardHeroLgBodyParagraphSpacing 
#define BrkCardHeroLgBodyTextDecoration none
#define BrkCardHeroLgBodyTextCase uppercase
#define BrkCardHeroLgImageHeight 270
#define BrkCardHeroLgPaddingHorizontal 24
#define BrkCardHeroLgPaddingVertical 24
#define BrkCardHeroLgHeadingMarginVertical 8
#define BrkCardHeroLgContentGap 24
#define BrkCardHeroXlPretitleFontFamily Roboto Condensed
#define BrkCardHeroXlPretitleFontWeight Regular
#define BrkCardHeroXlPretitleLineHeight 20
#define BrkCardHeroXlPretitleFontSize 20
#define BrkCardHeroXlPretitleLetterSpacing 2%
#define BrkCardHeroXlPretitleParagraphSpacing 
#define BrkCardHeroXlPretitleTextDecoration none
#define BrkCardHeroXlPretitleTextCase uppercase
#define BrkCardHeroXlHeadingFontFamily Roboto Condensed
#define BrkCardHeroXlHeadingFontWeight Bold
#define BrkCardHeroXlHeadingLineHeight 100%
#define BrkCardHeroXlHeadingFontSize 36
#define BrkCardHeroXlHeadingLetterSpacing 0%
#define BrkCardHeroXlHeadingParagraphSpacing 
#define BrkCardHeroXlHeadingTextDecoration none
#define BrkCardHeroXlHeadingTextCase uppercase
#define BrkCardHeroXlBodyFontFamily Roboto Condensed
#define BrkCardHeroXlBodyFontWeight Regular
#define BrkCardHeroXlBodyLineHeight 85%
#define BrkCardHeroXlBodyFontSize 18
#define BrkCardHeroXlBodyLetterSpacing 2%
#define BrkCardHeroXlBodyParagraphSpacing 
#define BrkCardHeroXlBodyTextDecoration none
#define BrkCardHeroXlBodyTextCase uppercase
#define BrkCardHeroXlImageHeight 320
#define BrkCardHeroXlPaddingHorizontal 24
#define BrkCardHeroXlPaddingVertical 24
#define BrkCardHeroXlHeadingMarginVertical 8
#define BrkCardHeroXlContentGap 16
#define BrkCardHeroBorderWidth 1
#define BrkCardHeroBorderRadius 0
#define BrkCardHeroStandardHeadingFontColor #ffffff
#define BrkCardHeroStandardPretitleFontColor #000000
#define BrkCardHeroStandardBodyFontColor #000000
#define BrkCardHeroStandardBorderColor #000000
#define BrkCardHeroStandardBackgroundColor #e41f1f
#define BrkCardHeroStandardBoxShadowDefault [object Object]
#define BrkCardHeroStandardBoxShadowHover [object Object]
#define BrkButtonPrimarySmLabelFontFamily Roboto Condensed
#define BrkButtonPrimarySmLabelFontWeight Bold
#define BrkButtonPrimarySmLabelLineHeight 85%
#define BrkButtonPrimarySmLabelFontSize 14
#define BrkButtonPrimarySmLabelLetterSpacing 2%
#define BrkButtonPrimarySmLabelParagraphSpacing 
#define BrkButtonPrimarySmLabelTextDecoration none
#define BrkButtonPrimarySmLabelTextCase uppercase
#define BrkButtonPrimaryMdLabelFontFamily Roboto Condensed
#define BrkButtonPrimaryMdLabelFontWeight Bold
#define BrkButtonPrimaryMdLabelLineHeight 85%
#define BrkButtonPrimaryMdLabelFontSize 24
#define BrkButtonPrimaryMdLabelLetterSpacing 2%
#define BrkButtonPrimaryMdLabelParagraphSpacing 
#define BrkButtonPrimaryMdLabelTextDecoration none
#define BrkButtonPrimaryMdLabelTextCase uppercase
#define BrkButtonPrimaryLgLabelFontFamily Roboto Condensed
#define BrkButtonPrimaryLgLabelFontWeight Bold
#define BrkButtonPrimaryLgLabelLineHeight 85%
#define BrkButtonPrimaryLgLabelFontSize 28
#define BrkButtonPrimaryLgLabelLetterSpacing 2%
#define BrkButtonPrimaryLgLabelParagraphSpacing 
#define BrkButtonPrimaryLgLabelTextDecoration none
#define BrkButtonPrimaryLgLabelTextCase uppercase
#define BrkButtonPrimaryXlLabelFontFamily Roboto Condensed
#define BrkButtonPrimaryXlLabelFontWeight Bold
#define BrkButtonPrimaryXlLabelLineHeight 85%
#define BrkButtonPrimaryXlLabelFontSize 32
#define BrkButtonPrimaryXlLabelLetterSpacing 2%
#define BrkButtonPrimaryXlLabelParagraphSpacing 
#define BrkButtonPrimaryXlLabelTextDecoration none
#define BrkButtonPrimaryXlLabelTextCase uppercase

