
//
// tokens.h
//

// Do not edit directly
// Generated on Thu, 28 Jul 2022 22:07:41 GMT


#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

#define BrkOptColorNeutral0 #ffffff
#define BrkOptColorNeutral25 #f9f9f9
#define BrkOptColorNeutral50 #f2f2f2
#define BrkOptColorNeutral100 #e6e6e6
#define BrkOptColorNeutral675 #535353
#define BrkOptColorNeutral900 #1a1a1a
#define BrkOptColorNeutral975 #060606
#define BrkOptColorNeutral1000 #000000
#define BrkOptColorNeutralSaturation 0
#define BrkOptColorNeutralHue 0
#define BrkOptColorLqMain50 #eaedfa
#define BrkOptColorLqMain100 #d5dbf6
#define BrkOptColorLqMain200 #abb6ed
#define BrkOptColorLqMain500 #2e49d1
#define BrkOptColorLqMain600 #253aa7
#define BrkOptColorLqMain650 #203392
#define BrkOptColorLqMain728 #192872
#define BrkOptColorLqMain800 #121d54
#define BrkOptColorLqMain900 #090f2a
#define BrkOptColorLqMainSaturation 64
#define BrkOptColorLqMainHue 230
#define BrkOptColorMojMain #db1f1f
#define BrkOptColorMojMainWeb #e41f1f
#define BrkOptColorMojSecond #c9ff00
#define BrkOptFontFamilyBrandLq Graphik
#define BrkOptFontFamilyBrandMoj Roboto Condensed
#define BrkOptLineHeightXs 85%
#define BrkOptLineHeightSm 100%
#define BrkOptLineHeightMd 110%
#define BrkOptLineHeightLg 120%
#define BrkOptLineHeightXl 160%
#define BrkOptFontWeightRegular Regular
#define BrkOptFontWeightMedium Medium
#define BrkOptFontWeightBold Bold
#define BrkOptFontSizeSm8 8
#define BrkOptFontSizeSm9 9
#define BrkOptFontSizeSm10 10
#define BrkOptFontSizeSm11 11
#define BrkOptFontSizeSm12 12
#define BrkOptFontSizeSm13 13
#define BrkOptFontSizeSm14 14
#define BrkOptFontSizeMd15 15
#define BrkOptFontSizeMd16 16
#define BrkOptFontSizeMd18 18
#define BrkOptFontSizeMd19 18
#define BrkOptFontSizeMd20 20
#define BrkOptFontSizeMd22 22
#define BrkOptFontSizeLg24 24
#define BrkOptFontSizeLg26 26
#define BrkOptFontSizeLg28 28
#define BrkOptFontSizeLg32 32
#define BrkOptFontSizeLg36 36
#define BrkOptFontSizeLg42 42
#define BrkOptFontSizeLg48 48
#define BrkOptFontSizeXl56 56
#define BrkOptFontSizeXl72 72
#define BrkOptLetterSpacingTight -2%
#define BrkOptLetterSpacingRegular 0%
#define BrkOptLetterSpacingLoose 2%
#define BrkOptLetterSpacingXLoose 4%
#define BrkOptParagraphSpacingNone 0
#define BrkOptParagraphSpacingBody 8%
#define BrkOptParagraphSpacingHeading 12%
#define BrkOptParagraphSpacingDisplay 16%
#define BrkOptTextTransformNone none
#define BrkOptTextTransformLowercase lowercase
#define BrkOptTextTransformUppercase uppercase
#define BrkOptTextTransformCapitalize capitalize
#define BrkOptTextDecorationNone none
#define BrkOptSizeSm4 4
#define BrkOptSizeSm8 8
#define BrkOptSizeSm10 10
#define BrkOptSizeSm12 12
#define BrkOptSizeSm14 14
#define BrkOptSizeSm16 16
#define BrkOptSizeSm18 18
#define BrkOptSizeSm20 20
#define BrkOptSizeMd24 24
#define BrkOptSizeMd28 28
#define BrkOptSizeMd30 30
#define BrkOptSizeMd32 32
#define BrkOptSizeMd36 36
#define BrkOptSizeMd40 40
#define BrkOptSizeMd44 44
#define BrkOptSizeMd48 48
#define BrkOptSizeMd60 60
#define BrkOptSizeMd72 72
#define BrkOptSizeLg180 180
#define BrkOptSizeLg270 270
#define BrkOptSizeLg320 320
#define BrkOptBorderRadiusNone 0
#define BrkOptBorderRadius3xs 1
#define BrkOptBorderRadius2xs 2
#define BrkOptBorderRadiusXs 4
#define BrkOptBorderRadiusSm 8
#define BrkOptBorderRadiusMd 16
#define BrkOptBorderRadiusLg 24
#define BrkOptBorderWidthNone 0
#define BrkOptBorderWidthXs 1
#define BrkOptBorderWidthSm 2
#define BrkOptBorderWidthMd 4
#define BrkOptBoxShadowNoneX 0
#define BrkOptBoxShadowNoneY 0
#define BrkOptBoxShadowNoneBlur 0
#define BrkOptBoxShadowNoneSpread 0
#define BrkOptBoxShadowNoneColor #000000
#define BrkOptBoxShadowNoneType dropShadow
#define BrkOptBoxShadowElevationSoftOnLightX 0
#define BrkOptBoxShadowElevationSoftOnLightY 2
#define BrkOptBoxShadowElevationSoftOnLightBlur 8
#define BrkOptBoxShadowElevationSoftOnLightSpread 0
#define BrkOptBoxShadowElevationSoftOnLightColor #e6e6e6
#define BrkOptBoxShadowElevationSoftOnLightType dropShadow
#define BrkOptBoxShadowElevationSoftOnMediumX 0
#define BrkOptBoxShadowElevationSoftOnMediumY 2
#define BrkOptBoxShadowElevationSoftOnMediumBlur 8
#define BrkOptBoxShadowElevationSoftOnMediumSpread 0
#define BrkOptBoxShadowElevationSoftOnMediumColor #1a1a1a
#define BrkOptBoxShadowElevationSoftOnMediumType dropShadow
#define BrkOptBoxShadowElevationStrongOnLightX 0
#define BrkOptBoxShadowElevationStrongOnLightY 7
#define BrkOptBoxShadowElevationStrongOnLightBlur 29
#define BrkOptBoxShadowElevationStrongOnLightSpread 0
#define BrkOptBoxShadowElevationStrongOnLightColor #e6e6e6
#define BrkOptBoxShadowElevationStrongOnLightType dropShadow
#define BrkOptBoxShadowElevationStrongOnMediumX 0
#define BrkOptBoxShadowElevationStrongOnMediumY 7
#define BrkOptBoxShadowElevationStrongOnMediumBlur 29
#define BrkOptBoxShadowElevationStrongOnMediumSpread 0
#define BrkOptBoxShadowElevationStrongOnMediumColor #1a1a1a
#define BrkOptBoxShadowElevationStrongOnMediumType dropShadow
#define BrkOptBoxShadowJelLqMainSmX 3px
#define BrkOptBoxShadowJelLqMainSmY 3px
#define BrkOptBoxShadowJelLqMainSmBlur 0
#define BrkOptBoxShadowJelLqMainSmSpread 0
#define BrkOptBoxShadowJelLqMainSmColor #192872
#define BrkOptBoxShadowJelLqMainSmType dropShadow
#define BrkOptBoxShadowJelLqMainMdX 5px
#define BrkOptBoxShadowJelLqMainMdY 5px
#define BrkOptBoxShadowJelLqMainMdBlur 0
#define BrkOptBoxShadowJelLqMainMdSpread 0
#define BrkOptBoxShadowJelLqMainMdColor #192872
#define BrkOptBoxShadowJelLqMainMdType dropShadow
#define BrkOptBoxShadowJelJelMainSmX 3px
#define BrkOptBoxShadowJelJelMainSmY 3px
#define BrkOptBoxShadowJelJelMainSmBlur 0
#define BrkOptBoxShadowJelJelMainSmSpread 0
#define BrkOptBoxShadowJelJelMainSmColor #0b5db7
#define BrkOptBoxShadowJelJelMainSmType dropShadow
#define BrkOptBoxShadowJelNeutralSmX 3px
#define BrkOptBoxShadowJelNeutralSmY 3px
#define BrkOptBoxShadowJelNeutralSmBlur 0
#define BrkOptBoxShadowJelNeutralSmSpread 0
#define BrkOptBoxShadowJelNeutralSmColor #ffffff
#define BrkOptBoxShadowJelNeutralSmType dropShadow
#define BrkOptSpaceSm1 1
#define BrkOptSpaceSm2 2
#define BrkOptSpaceSm3 3
#define BrkOptSpaceSm4 4
#define BrkOptSpaceSm5 5
#define BrkOptSpaceSm6 6
#define BrkOptSpaceSm8 8
#define BrkOptSpaceSm10 10
#define BrkOptSpaceSm12 12
#define BrkOptSpaceSm15 15
#define BrkOptSpaceSm16 16
#define BrkOptSpaceSmNone 0
#define BrkOptSpaceMd20 20
#define BrkOptSpaceMd24 24
#define BrkOptSpaceMd30 30
#define BrkOptSpaceMd32 32
#define BrkOptSpaceMd40 40
#define BrkOptSpaceMd45 45
#define BrkOptSpaceMd60 60
#define BrkOptColorJelMain #0b5db7
#define BrkOptColorJelSecond #24c1ff
#define BrkOptColorJelThird #a6ecff
#define BrkOptColorJelAccent #fdfe8b
#define DocOptColorMain #7B61FF

