# This is a basic workflow that is automatically triggered

name: Workflow automatique livraison Tokens

# Controls when the action will run. 
# or API.
on:
  push:
    branches: [ dev ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow install test-tokens-npm in Storybook in automatic mode
  install-test-tokens-npm-automatic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[MAJ_Auto] Après livraison NPM')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install node modules
      run: npm ci
    - name: Install Design Tokens dernière version     
      run: npm install brk-figma-mvp1@latest --save-dev
      
    # Pause for 20 seconds     
    - run: echo "Pause de 20 secondes"    
    - name: Sleep for 20 seconds
      run: sleep 20s
      shell: bash
        
    - name: Copie des CSS - Script InstallTokens     
      run: npm run tokens 

    # Add files that were created during a run, e.g. created files from npm install test-tokens-npm.
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4.14.1
      with:
        commit_message: "[UPDATE DEPUIS TOKENS NPM]"
        push_options: '--force'
